# 08 - Multi-Horizon: Du bao 4 mat hang tai H = 1, 5, 10, 15, 20, 30, 60 (clean_data_exo_ver1.csv)

> De `CONFIG['run_all_targets'] = True` va Run All mot lan. Notebook tu chay lan luot 4 target va hien bang multihorizon tong hop o o cuoi.

Danh gia **nhieu horizon** de do **su phan ra tin hieu** (signal decay) khi du bao cang xa. **Chi in bang ket qua (MAE, RMSE, RMSE($), MAPE, SMAPE, R2 + kiem tra dat chuan) — khong ve/luu chart.**

- **Dataset:** `data/processed/clean_data_exo_ver1.csv`.
- **Horizons:** H ∈ {1, 5, 10, 15, 20, 30, 60} ngay.
- **Tieu chuan chat luong:** MAPE < 3% (ngan han 1-5 ngay), MAPE < 5% (trung han 10-20 ngay), RMSE($) < 2.
- **Them dac trung mua vu:** `Sin(Date)`, `Cos(Date)` (chu ky nam, day-of-year).
- **Mo hinh:** SARIMA, ARIMAX, Jump-Gated ARIMAX-CatBoost, Ridge/Linear, LightGBM, LSTM, iTransformer, GUMNet-Lite, GUMNet-Ultra, PatchTST, TFT. DL/PyTorch tu dong skip neu thieu thu vien.

> ARIMA/SARIMA dung **rolling H-step** (forecast H buoc tai moi moc, khong refit). ML/DL: target = gia mat hang dang chon tai t+H.
> Chay nang: 11 mo hinh × 7 horizon. Giam `CONFIG['horizons']` / tat `run_seq_dl`, `run_nf` de chay nhanh.

> **Jump-Gated ARIMAX-CatBoost duoc mo rong cho multi-horizon:** H1 hoi 'ngay mai co nhay gia khong'; H5..H60 hoi 'trong H ngay toi co bien dong lon khong'.

In [1]:
# === Setup ===
import os
os.environ.setdefault("TF_USE_LEGACY_KERAS", "1")   # repo models use Keras-2 API (TF 2.17 = Keras 3)
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
import warnings; warnings.filterwarnings("ignore")
import sys
from pathlib import Path
import numpy as np
import pandas as pd

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))

TARGETS = ["MG95", "MG92", "DO 0.001%", "DO 0.05%"]

# --- Dataset + notebook self-reference -------------------------------------------------
# This notebook loads data/processed/clean_data_exo_ver1.csv. The batch run (other targets)
# re-executes THIS notebook and inherits FORECAST_DATA_FILE so every child uses the same file.
DATA_FILENAME = os.environ.get("FORECAST_DATA_FILE", "clean_data_exo_ver1.csv")
NB_FILENAME   = "10_multihorizon.ipynb"
DATA_TAG      = Path(DATA_FILENAME).stem            # keeps outputs per-dataset (no clobber)

CONFIG = {
    "targets":      TARGETS,
    "target":       os.environ.get("FORECAST_TARGET", TARGETS[0]),
    "run_all_targets": True,
    "horizons":     [1, 5, 10, 15, 20, 30, 60],
    "train_ratio":  0.80,
    "val_ratio":    0.10,
    "exog_cols":    ["WTI", "USD_Index", "GPR", "BRT DTD", "BRT KH", "Brent_EU_Daily", "NAPHTHA"],
    "seasonal":     5,
    "seq_len_by_h": {1: 30, 5: 30, 10: 45, 15: 45, 20: 60, 30: 60, 60: 90},
    "dl_epochs":    30,      # epochs cho LSTM/iTransformer/GUMNet
    "nf_steps":     300,     # max_steps cho PatchTST/TFT
    "run_seq_dl":   True,    # LSTM/iTransformer/GUMNet (can tensorflow)
    "run_nf":       True,    # PatchTST/TFT (can neuralforecast)
    "run_jump_gated": True, # Jump-Gated ARIMAX-CatBoost multi-horizon
    "tune_lgbm":    False,
}
if CONFIG["target"] not in TARGETS:
    raise ValueError(f"Target khong hop le: {CONFIG['target']}. Chon mot trong {TARGETS}")
print("ROOT =", ROOT)
print("Dataset:", DATA_FILENAME, "| tag:", DATA_TAG)
print("Target:", CONFIG["target"], "| Horizons:", CONFIG["horizons"])

ROOT = e:\PCDOC\xangdau\XANG_DAU_FORECAST\XANG_DAU_FORECAST
Dataset: clean_data_exo_ver1.csv | tag: clean_data_exo_ver1
Target: MG95 | Horizons: [1, 5, 10, 15, 20, 30, 60]

## 1. Load du lieu + Sin(Date)/Cos(Date) + (tuy chon) News

In [2]:
from src.data_loader import load_and_engineer
TARGET = CONFIG["target"]
TARGET_SLUG = TARGET.replace("%", "pct").replace(" ", "_").replace(".", "_")
TARGET_RESULT_DIR = ROOT / "results" / DATA_TAG / "by_target" / TARGET_SLUG
TARGET_RESULT_DIR.mkdir(parents=True, exist_ok=True)

# Load the explicit dataset file (clean_data_exo_ver1.csv unless overridden by FORECAST_DATA_FILE).
DATA_FILE = ROOT / "data" / "processed" / DATA_FILENAME
df = load_and_engineer(data_path=str(DATA_FILE), target_col=TARGET)
print("Loaded:", DATA_FILE.name)

# --- Sin(Date) & Cos(Date): chu ky mua vu theo nam (day-of-year) ---
doy = df.index.dayofyear.values
df["DOY_sin"] = np.sin(2 * np.pi * doy / 365.25)
df["DOY_cos"] = np.cos(2 * np.pi * doy / 365.25)
print("Added Sin(Date)/Cos(Date): DOY_sin, DOY_cos")

# --- News (optional) ---
from pathlib import Path
news_path = Path("E:/PCDOC/xangdau/XANG_DAU_FORECAST/XANG_DAU_FORECAST/data/news/archive_2026-06-23/daily_features.csv")
news_cols = []
if news_path.exists():
    news = pd.read_csv(news_path, parse_dates=["date"]).set_index("date")
    news = news[~news.index.duplicated(keep="last")].sort_index()
    df = df.join(news, how="left"); news_cols = list(news.columns)
    df[news_cols] = df[news_cols].fillna(0.0)
    print(f"News joined: +{len(news_cols)} cot")
else:
    print("Khong co daily_features.csv -> chay khong co news.")

feature_cols = [c for c in df.columns if c != TARGET]
print("df:", df.shape, "| features:", len(feature_cols), "| range", df.index.min().date(), "->", df.index.max().date())

Loaded: clean_data_exo_ver1.csv
Added Sin(Date)/Cos(Date): DOY_sin, DOY_cos
News joined: +16 cot
df: (4619, 70) | features: 69 | range 2008-06-12 -> 2026-05-08

## 2. Chi so + cac ham chuan bi du lieu (tabular & sequence)

In [3]:
from sklearn.metrics import (mean_absolute_error, mean_squared_error, r2_score,
                             accuracy_score, f1_score)
from sklearn.preprocessing import RobustScaler

# --- Quality standard ------------------------------------------------------------------
# MAPE < 3%  : short-term  (H 1-5 ngay)
# MAPE < 5%  : mid-term    (H 10-20 ngay)
# RMSE < 2$  : prices are USD -> RMSE is already in dollars (RMSE($) == RMSE)
# Long-term (H 30/60): no MAPE threshold stated -> only the RMSE($) rule applies.
RMSE_USD_THRESHOLD = 2.0
def mape_threshold(H):
    if H <= 5:  return 3.0
    if H <= 20: return 5.0
    return np.nan

def reg_metrics(y_true, y_pred, name, H):
    yt = np.asarray(y_true, float); yp = np.asarray(y_pred, float)
    mae  = mean_absolute_error(yt, yp)
    rmse = float(np.sqrt(mean_squared_error(yt, yp)))
    mape = float(np.mean(np.abs((yt - yp) / (np.abs(yt) + 1e-8))) * 100)
    smape = float(np.mean(2.0 * np.abs(yp - yt) / (np.abs(yt) + np.abs(yp) + 1e-8)) * 100)
    thr = mape_threshold(H)
    mape_ok = bool(np.isnan(thr) or mape < thr)
    rmse_ok = bool(rmse < RMSE_USD_THRESHOLD)
    return {"Model": name, "Horizon": H, "MAE": round(mae,4), "RMSE": round(rmse,4),
            "RMSE($)": round(rmse,4),                          # RMSE in USD (prices are USD)
            "MAPE(%)": round(mape,4), "SMAPE(%)": round(smape,4), "R2": round(float(r2_score(yt,yp)),4),
            "MAPE_thr(%)": thr, "RMSE_thr($)": RMSE_USD_THRESHOLD,
            "Pass": bool(mape_ok and rmse_ok)}

def prep_tabular(H):
    w = df.copy(); w["__y"] = w[TARGET].shift(-H); w = w.dropna(subset=["__y"])
    n = len(w); ntr = int(n*CONFIG["train_ratio"]); nvl = int(n*CONFIG["val_ratio"])
    tr, vl, te = w.iloc[:ntr], w.iloc[ntr:ntr+nvl], w.iloc[ntr+nvl:]
    sx = RobustScaler().fit(tr[feature_cols])
    Xtr, Xvl, Xte = sx.transform(tr[feature_cols]), sx.transform(vl[feature_cols]), sx.transform(te[feature_cols])
    out = dict(Xtr=Xtr, Xvl=Xvl, Xte=Xte,
               ytr=tr["__y"].values, yvl=vl["__y"].values, yte=te["__y"].values,
               dir_tr=(tr["__y"].values > tr[TARGET].values).astype(int),
               dir_te=(te["__y"].values > te[TARGET].values).astype(int),
               test_dates=te.index)
    return out

def prep_sequences(H):
    from src.data_loader import make_windows
    SEQ = CONFIG["seq_len_by_h"][H]
    n_df = len(df); ntr = int(n_df*CONFIG["train_ratio"])
    sxq = RobustScaler().fit(df[feature_cols].iloc[:ntr])
    syq = RobustScaler().fit(df[[TARGET]].iloc[:ntr])
    Xall = sxq.transform(df[feature_cols].values)
    yall = syq.transform(df[[TARGET]].values).flatten()
    Xw, yw = make_windows(Xall, yall, time_steps=SEQ, horizon=H)
    nW = len(Xw); a = int(nW*0.8); b = int(nW*0.1)
    return dict(Xw_tr=Xw[:a], Xw_vl=Xw[a:a+b], Xw_te=Xw[a+b:],
                yw_tr=yw[:a], yw_vl=yw[a:a+b], yw_te=yw[a+b:],
                scaler_y=syq, SEQ=SEQ, N_FEAT=len(feature_cols))

print("Helpers ready.")

Helpers ready.

## 3. Mo hinh thong ke — rolling H-step ARIMAX & SARIMA

In [4]:
from statsmodels.tsa.statespace.sarimax import SARIMAX
exog_all = [c for c in CONFIG["exog_cols"] if c in df.columns]

def _arima_rolling(y, exog, split, order, seas, H, maxiter=50):
    # Fit tren [0:split], forecast H-step tai moi moc (append, khong refit).
    res = SARIMAX(y[:split], exog=None if exog is None else exog[:split],
                  order=order, seasonal_order=seas,
                  enforce_stationarity=False, enforce_invertibility=False).fit(disp=False, maxiter=maxiter)
    cur = res; N = len(y); o = split - 1; idxs, preds = [], []
    while o + H <= N - 1:
        if exog is None: fc = cur.forecast(steps=H)
        else: fc = cur.forecast(steps=H, exog=exog[o+1:o+1+H])
        preds.append(float(np.asarray(fc)[-1])); idxs.append(o + H)
        if exog is None: cur = cur.extend(y[o+1:o+2])            # extend = O(1), khong refit
        else: cur = cur.extend(y[o+1:o+2], exog=exog[o+1:o+2])
        o += 1
    return np.array(idxs), np.array(preds)

def fit_arimax(H):
    y = df[TARGET].reset_index(drop=True).astype(float)
    ex = df[exog_all].reset_index(drop=True).astype(float)
    split = int(len(y) * 0.9)
    idx, pred = _arima_rolling(y, ex, split, (2,1,2), (0,0,0,0), H)
    return y.values[idx], pred

def fit_sarima(H):
    y = df[TARGET].reset_index(drop=True).astype(float)
    split = int(len(y) * 0.9)
    idx, pred = _arima_rolling(y, None, split, (1,1,1), (1,0,1,CONFIG["seasonal"]), H)
    return y.values[idx], pred

print("ARIMA helpers ready.")

ARIMA helpers ready.

## 4. Champion Jump-Gated ARIMAX-CatBoost multi-horizon

In [5]:
# Import the module file directly: going through `src.models` runs src/models/__init__.py,
# which eagerly imports optuna/lightgbm/catboost (via baseline_lgbm) and can fail or leave a
# stale module cached -> "cannot import name 'load_champion_frame'". This avoids all of that.
import importlib.util as _ilu
_jg_path = ROOT / "src" / "models" / "jump_gated_arimax_catboost.py"
_jg_spec = _ilu.spec_from_file_location("jump_gated_arimax_catboost", _jg_path)
_jg = _ilu.module_from_spec(_jg_spec)
sys.modules[_jg_spec.name] = _jg          # register first so @dataclass can resolve annotations
_jg_spec.loader.exec_module(_jg)
JumpGatedConfig = _jg.JumpGatedConfig
load_champion_frame = _jg.load_champion_frame
run_jump_gated_arimax_catboost_horizon = _jg.run_jump_gated_arimax_catboost_horizon

jump_details = {}
# Use the SAME dataset as the rest of the notebook (load_champion_frame defaults to ver1).
champion_df = load_champion_frame(root=ROOT, data_path=DATA_FILE)
print("Champion frame:", champion_df.shape, "|", champion_df.index.min().date(), "->", champion_df.index.max().date())

# ver2 drops some exogenous columns (GPR / BRT KH / Brent_EU_Daily); keep only what's present.
jump_exog = [c for c in CONFIG["exog_cols"] if c in champion_df.columns]
print("Jump-Gated exog:", jump_exog)

def fit_jump_gated_arimax_catboost(H):
    cfg = JumpGatedConfig(
        target=TARGET,
        horizon=H,
        train_ratio=CONFIG["train_ratio"],
        val_ratio=CONFIG["val_ratio"],
        exog_cols=jump_exog,
        arimax_order=(2, 1, 2),
        # Tuned in notebook 06: smaller grid, more stable for H1-H60.
        oof_folds=3,
        oof_min_train_frac=0.60,
        jump_thresholds=[1.5, 2.5, 4.0, 6.0],
        soft_gammas=[0.5, 1.0],
        hard_cutoffs=[0.25, 0.40, 0.55],
    )
    out = run_jump_gated_arimax_catboost_horizon(
        champion_df,
        horizon=H,
        root=ROOT,
        config=cfg,
        exact_h1=True,
        progress=True,
    )
    jump_details[H] = out
    return out["y_test"], out["pred_jump_gated"]

print("Champion Jump-Gated ARIMAX-CatBoost multi-horizon helper ready.")

Champion frame: (4619, 17) | 2008-06-12 -> 2026-05-08
Jump-Gated exog: ['WTI', 'USD_Index', 'GPR', 'BRT DTD', 'BRT KH', 'Brent_EU_Daily', 'NAPHTHA']
Champion Jump-Gated ARIMAX-CatBoost multi-horizon helper ready.

## 5. ML models - Ridge, LightGBM, Logistic (huong)

In [6]:
from sklearn.linear_model import Ridge, LogisticRegression
import lightgbm as lgb

def fit_ridge(d):
    m = Ridge(alpha=1.0).fit(d["Xtr"], d["ytr"]); return d["yte"], m.predict(d["Xte"])

def fit_lgbm(d):
    if CONFIG["tune_lgbm"]:
        from src.models.baseline_lgbm import tune_lgbm, train_lgbm
        bp = tune_lgbm(d["Xtr"], d["ytr"], d["Xvl"], d["yvl"], n_trials=30)["best_params"]
        m = train_lgbm(d["Xtr"], d["ytr"], d["Xvl"], d["yvl"], bp)
    else:
        m = lgb.LGBMRegressor(n_estimators=600, learning_rate=0.03, max_depth=7, num_leaves=63,
                              subsample=0.8, colsample_bytree=0.8, min_child_samples=20,
                              random_state=42, n_jobs=-1, verbose=-1)
        m.fit(d["Xtr"], d["ytr"], eval_set=[(d["Xvl"], d["yvl"])],
              callbacks=[lgb.early_stopping(50, verbose=False)])
    return d["yte"], m.predict(d["Xte"])

def fit_logistic(d, H):
    clf = LogisticRegression(max_iter=2000, class_weight="balanced").fit(d["Xtr"], d["dir_tr"])
    p = clf.predict(d["Xte"])
    return {"Model": "LogisticRegression (huong)", "Horizon": H,
            "Accuracy": round(float(accuracy_score(d["dir_te"], p)),4),
            "F1": round(float(f1_score(d["dir_te"], p, zero_division=0)),4),
            "BaseUpRate": round(float(d["dir_te"].mean()),4)}
print("ML helpers ready.")

ML helpers ready.

## 6. Deep models - LSTM, iTransformer, GUMNet-Lite/Ultra (Keras); PatchTST/TFT (neuralforecast)

In [7]:
def _seq_eval(model, s):
    pred = s["scaler_y"].inverse_transform(np.asarray(model.predict(s["Xw_te"], verbose=0)).reshape(-1,1)).flatten()
    ytru = s["scaler_y"].inverse_transform(s["yw_te"].reshape(-1,1)).flatten()
    return ytru, pred

def fit_lstm(s, H):
    import tensorflow as tf
    from tensorflow.keras import layers, Model
    tf.random.set_seed(42); tf.keras.backend.clear_session()
    inp = layers.Input((s["SEQ"], s["N_FEAT"]))
    x = layers.LSTM(64, return_sequences=True)(inp); x = layers.Dropout(0.2)(x)
    x = layers.LSTM(32)(x); x = layers.Dense(16, activation="relu")(x)
    out = layers.Dense(1)(x)
    m = Model(inp, out); m.compile(optimizer="adam", loss="mse")
    es = tf.keras.callbacks.EarlyStopping(patience=8, restore_best_weights=True)
    m.fit(s["Xw_tr"], s["yw_tr"], validation_data=(s["Xw_vl"], s["yw_vl"]),
          epochs=CONFIG["dl_epochs"], batch_size=64, callbacks=[es], verbose=0)
    return _seq_eval(m, s)

def fit_itransformer(s, H):
    from src.models.hybrid_sota import train_itransformer
    m, _ = train_itransformer(s["Xw_tr"], s["yw_tr"], s["Xw_vl"], s["yw_vl"],
                              time_steps=s["SEQ"], n_features=s["N_FEAT"], horizon=H,
                              epochs=CONFIG["dl_epochs"], batch_size=64)
    return _seq_eval(m, s)

def fit_gumnet_lite(s, H):
    from src.models.hybrid_sota import train_gumnet_lite
    m, _ = train_gumnet_lite(s["Xw_tr"], s["yw_tr"], s["Xw_vl"], s["yw_vl"],
                             time_steps=s["SEQ"], n_features=s["N_FEAT"], horizon=H,
                             epochs=CONFIG["dl_epochs"], batch_size=64)
    return _seq_eval(m, s)

def fit_gumnet_ultra(s, H):
    from src.models.hybrid_sota import train_gumnet_ultra
    m, _ = train_gumnet_ultra(s["Xw_tr"], s["yw_tr"], s["Xw_vl"], s["yw_vl"],
                              time_steps=s["SEQ"], n_features=s["N_FEAT"], horizon=H,
                              epochs=CONFIG["dl_epochs"], batch_size=64)
    return _seq_eval(m, s)

def fit_neuralforecast(H):
    from neuralforecast import NeuralForecast
    from neuralforecast.models import PatchTST, TFT
    nf_exog = [c for c in CONFIG["exog_cols"] if c in df.columns]
    base = df[[TARGET] + nf_exog].copy().asfreq("B").ffill()
    long = base.reset_index(); long.columns = ["ds"] + [TARGET] + nf_exog
    long["unique_id"] = TARGET; long["y"] = long[TARGET]
    long = long[["unique_id", "ds", "y"] + nf_exog]
    n_win = min(200, max(20, int(len(df) * 0.1)))
    common = dict(h=H, input_size=CONFIG["seq_len_by_h"][H], max_steps=CONFIG["nf_steps"],
                  scaler_type="robust", hist_exog_list=nf_exog, enable_progress_bar=False)
    nf = NeuralForecast(models=[PatchTST(**common), TFT(**common)], freq="B")
    cv = nf.cross_validation(df=long, n_windows=n_win, step_size=1)
    res = {}
    for mname in ["PatchTST", "TFT"]:
        if mname in cv.columns:
            sub = cv.dropna(subset=[mname]); res[mname] = (sub["y"].values, sub[mname].values)
    return res
print("DL helpers ready.")

DL helpers ready.

## 7. Driver - chay tat ca mo hinh tren tat ca horizon

In [8]:
import time
results = []      # regression rows (co Horizon)
clf_results = []  # logistic rows

for H in CONFIG["horizons"]:
    t0 = time.time(); print("="*70); print(f"HORIZON H = {H}"); print("="*70)
    d = prep_tabular(H)

    # --- statistical ---
    for name, fn in [("ARIMAX", fit_arimax), ("SARIMA", fit_sarima)]:
        try:
            yt, yp = fn(H); results.append(reg_metrics(yt, yp, name, H)); print(" ", results[-1])
        except Exception as e:
            print(f"  {name} skipped:", repr(e))

    # --- hybrid moi: ARIMAX-CatBoost co cong nhan dien bien dong lon ---
    if CONFIG.get("run_jump_gated", True):
        try:
            yt, yp = fit_jump_gated_arimax_catboost(H)
            results.append(reg_metrics(yt, yp, "Jump-Gated ARIMAX-CatBoost", H))
            print(" ", results[-1])
        except Exception as e:
            print("  Jump-Gated ARIMAX-CatBoost skipped:", repr(e))

    # --- linear / tree ---
    for name, fn in [("Ridge (Linear)", fit_ridge), ("LightGBM", fit_lgbm)]:
        try:
            yt, yp = fn(d); results.append(reg_metrics(yt, yp, name, H)); print(" ", results[-1])
        except Exception as e:
            print(f"  {name} skipped:", repr(e))

    # # --- logistic direction ---
    # try:
    #     clf_results.append(fit_logistic(d, H)); print(" ", clf_results[-1])
    # except Exception as e:
    #     print("  Logistic skipped:", repr(e))

    # --- sequence DL (Keras) ---
    if CONFIG["run_seq_dl"]:
        try:
            s = prep_sequences(H)
            for name, fn in [("LSTM", fit_lstm), ("iTransformer", fit_itransformer),
                             ("GUMNet-Lite", fit_gumnet_lite), ("GUMNet-Ultra", fit_gumnet_ultra)]:
                try:
                    yt, yp = fn(s, H); results.append(reg_metrics(yt, yp, name, H)); print(" ", results[-1])
                except Exception as e:
                    print(f"  {name} skipped:", repr(e))
        except Exception as e:
            print("  Sequence prep skipped:", repr(e))

    # --- PatchTST / TFT (neuralforecast) ---
    if CONFIG["run_nf"]:
        try:
            for mname, (yt, yp) in fit_neuralforecast(H).items():
                results.append(reg_metrics(yt, yp, mname, H)); print(" ", results[-1])
        except Exception as e:
            print("  PatchTST/TFT skipped:", repr(e))

    print(f"  [H={H}] done in {time.time()-t0:.1f}s")

print("\nALL HORIZONS DONE. rows:", len(results))

======================================================================
HORIZON H = 1
======================================================================
  {'Model': 'ARIMAX', 'Horizon': 1, 'MAE': 0.9752, 'RMSE': 2.1116, 'RMSE($)': 2.1116, 'MAPE(%)': 0.9796, 'SMAPE(%)': 0.9759, 'R2': 0.986, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'SARIMA', 'Horizon': 1, 'MAE': 1.5108, 'RMSE': 3.0496, 'RMSE($)': 3.0496, 'MAPE(%)': 1.554, 'SMAPE(%)': 1.5528, 'R2': 0.9709, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
OOF fold 1: 2018-02-13 -> 2020-04-08 | MAE=0.6427
OOF fold 2: 2020-04-09 -> 2022-06-01 | MAE=0.7917
OOF fold 3: 2022-06-02 -> 2024-07-24 | MAE=1.1909
Jump-Gated ARIMAX-CatBoost MAE=1.0799
  {'Model': 'Jump-Gated ARIMAX-CatBoost', 'Horizon': 1, 'MAE': 1.0799, 'RMSE': 2.7229, 'RMSE($)': 2.7229, 'MAPE(%)': 1.0457, 'SMAPE(%)': 1.0432, 'R2': 0.9767, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'Ridge (Linear)', 'Horizon': 1, 'MAE': 1.4194, 'RMSE': 2.8282, 'RMSE($)': 2.8282, 'MAPE(%)': 1.4162, 'SMAPE(%)': 1.4252, 'R2': 0.9749, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LightGBM', 'Horizon': 1, 'MAE': 1.9689, 'RMSE': 3.6704, 'RMSE($)': 3.6704, 'MAPE(%)': 2.0071, 'SMAPE(%)': 2.0372, 'R2': 0.9577, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
WARNING:tensorflow:From c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

  {'Model': 'LSTM', 'Horizon': 1, 'MAE': 5.1022, 'RMSE': 7.8893, 'RMSE($)': 7.8893, 'MAPE(%)': 5.4919, 'SMAPE(%)': 5.4739, 'R2': 0.8056, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 11s 59ms/step - loss: 0.8813 - mae: 0.2723 - val_loss: 1.6616 - val_mae: 0.5025 - learning_rate: 5.0000e-04
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - loss: 0.5362 - mae: 0.1702 - val_loss: 1.2486 - val_mae: 0.3831 - learning_rate: 5.0000e-04
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.4574 - mae: 0.1461 - val_loss: 1.1341 - val_mae: 0.3501 - learning_rate: 5.0000e-04
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.3893 - mae: 0.1250 - val_loss: 0.6573 - val_mae: 0.2077 - learning_rate: 5.0000e-04
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.3365 - mae: 0.1088 - val_loss: 0.4291 - val_mae: 0.1381 - learning_rate: 5.0000e-04
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step - loss: 0.3357 - mae: 0.1085 - val_loss: 0.5802 - val_mae: 0.1845 - learning_rate: 5.0000e-04
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step - loss: 0.3231 - mae: 0.1046 - val_loss: 0.5371 - val_mae: 0.1714 - learning_rate: 5.0000e-04
Epoch 8/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step - loss: 0.3131 - mae: 0.1015 - val_loss: 0.3975 - val_mae: 0.1284 - learning_rate: 5.0000e-04
Epoch 9/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2983 - mae: 0.0968 - val_loss: 0.2713 - val_mae: 0.0884 - learning_rate: 5.0000e-04
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.2807 - mae: 0.0911 - val_loss: 0.2793 - val_mae: 0.0910 - learning_rate: 5.0000e-04
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.2544 - mae: 0.0828 - val_loss: 0.2399 - val_mae: 0.0784 - learning_rate: 5.0000e-04
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2493 - mae: 0.0812 - val_loss: 0.2669 - val_mae: 0.0870 - learning_rate: 5.0000e-04
Epoch 13/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2547 - mae: 0.0829 - val_loss: 0.2684 - val_mae: 0.0875 - learning_rate: 5.0000e-04
Epoch 14/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.2510 - mae: 0.0817 - val_loss: 0.2564 - val_mae: 0.0836 - learning_rate: 5.0000e-04
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2312 - mae: 0.0754 - val_loss: 0.2484 - val_mae: 0.0811 - learning_rate: 5.0000e-04
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.2442 - mae: 0.0795 - val_loss: 0.2370 - val_mae: 0.0775 - learning_rate: 5.0000e-04
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.2395 - mae: 0.0781 - val_loss: 0.2462 - val_mae: 0.0804 - learning_rate: 5.0000e-04
Epoch 18/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2266 - mae: 0.0739 - val_loss: 0.2128 - val_mae: 0.0696 - learning_rate: 5.0000e-04
Epoch 19/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2217 - mae: 0.0724 - val_loss: 0.2339 - val_mae: 0.0765 - learning_rate: 5.0000e-04
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2160 - mae: 0.0706 - val_loss: 0.2622 - val_mae: 0.0856 - learning_rate: 5.0000e-04
Epoch 21/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2265 - mae: 0.0739 - val_loss: 0.2100 - val_mae: 0.0687 - learning_rate: 5.0000e-04
Epoch 22/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2313 - mae: 0.0755 - val_loss: 0.2263 - val_mae: 0.0740 - learning_rate: 5.0000e-04
Epoch 23/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2190 - mae: 0.0715 - val_loss: 0.2292 - val_mae: 0.0749 - learning_rate: 5.0000e-04
Epoch 24/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2371 - mae: 0.0773 - val_loss: 0.2546 - val_mae: 0.0831 - learning_rate: 5.0000e-04
Epoch 25/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2161 - mae: 0.0706 - val_loss: 0.2138 - val_mae: 0.0700 - learning_rate: 5.0000e-04
Epoch 26/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.2396 - mae: 0.0781
Epoch 26: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.2393 - mae: 0.0779 - val_loss: 0.2262 - val_mae: 0.0740 - learning_rate: 5.0000e-04
Epoch 27/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2063 - mae: 0.0674 - val_loss: 0.2053 - val_mae: 0.0672 - learning_rate: 2.5000e-04
Epoch 28/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - loss: 0.1942 - mae: 0.0635 - val_loss: 0.2170 - val_mae: 0.0710 - learning_rate: 2.5000e-04
Epoch 29/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.1894 - mae: 0.0620 - val_loss: 0.2092 - val_mae: 0.0685 - learning_rate: 2.5000e-04
Epoch 30/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.1937 - mae: 0.0633 - val_loss: 0.2246 - val_mae: 0.0735 - learning_rate: 2.5000e-04
Restoring model weights from the end of the best epoch: 27.
  {'Model': 'iTransformer', 'Horizon': 1, 'MAE': 5.1525, 'RMSE': 11.2749, 'RMSE($)': 11.2749, 'MAPE(%)': 4.7147, 'SMAPE(%)': 5.0293, 'R2': 0.603, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 1.1851 - mae: 0.3553 - val_loss: 0.4128 - val_mae: 0.1334 - learning_rate: 0.0010
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.4983 - mae: 0.1586 - val_loss: 0.4864 - val_mae: 0.1559 - learning_rate: 0.0010
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.4269 - mae: 0.1363 - val_loss: 0.6453 - val_mae: 0.2062 - learning_rate: 0.0010
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3650 - mae: 0.1173 - val_loss: 0.2792 - val_mae: 0.0909 - learning_rate: 0.0010
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3487 - mae: 0.1123 - val_loss: 0.2737 - val_mae: 0.0893 - learning_rate: 0.0010
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3253 - mae: 0.1048 - val_loss: 0.2700 - val_mae: 0.0880 - learning_rate: 0.0010
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.3134 - mae: 0.1012 - val_loss: 0.2641 - val_mae: 0.0862 - learning_rate: 0.0010
Epoch 8/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2973 - mae: 0.0961 - val_loss: 0.2569 - val_mae: 0.0838 - learning_rate: 0.0010
Epoch 9/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3017 - mae: 0.0975 - val_loss: 0.2566 - val_mae: 0.0837 - learning_rate: 0.0010
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2795 - mae: 0.0905 - val_loss: 0.2880 - val_mae: 0.0938 - learning_rate: 0.0010
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2862 - mae: 0.0926 - val_loss: 0.2747 - val_mae: 0.0896 - learning_rate: 0.0010
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2745 - mae: 0.0890 - val_loss: 0.2638 - val_mae: 0.0860 - learning_rate: 0.0010
Epoch 13/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2687 - mae: 0.0871 - val_loss: 0.2492 - val_mae: 0.0813 - learning_rate: 0.0010
Epoch 14/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2539 - mae: 0.0823 - val_loss: 0.2709 - val_mae: 0.0883 - learning_rate: 0.0010
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2578 - mae: 0.0836 - val_loss: 0.2637 - val_mae: 0.0860 - learning_rate: 0.0010
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2503 - mae: 0.0812 - val_loss: 0.2611 - val_mae: 0.0852 - learning_rate: 0.0010
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2462 - mae: 0.0800 - val_loss: 0.2446 - val_mae: 0.0799 - learning_rate: 0.0010
Epoch 18/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2495 - mae: 0.0810 - val_loss: 0.2228 - val_mae: 0.0729 - learning_rate: 0.0010
Epoch 19/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2344 - mae: 0.0762 - val_loss: 0.2353 - val_mae: 0.0769 - learning_rate: 0.0010
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2426 - mae: 0.0788 - val_loss: 0.2492 - val_mae: 0.0814 - learning_rate: 0.0010
Epoch 21/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2268 - mae: 0.0738 - val_loss: 0.2346 - val_mae: 0.0767 - learning_rate: 0.0010
Epoch 22/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2345 - mae: 0.0762 - val_loss: 0.2497 - val_mae: 0.0816 - learning_rate: 0.0010
Epoch 23/30
57/58 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2434 - mae: 0.0791
Epoch 23: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2432 - mae: 0.0790 - val_loss: 0.2601 - val_mae: 0.0849 - learning_rate: 0.0010
Epoch 24/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2167 - mae: 0.0706 - val_loss: 0.2351 - val_mae: 0.0769 - learning_rate: 5.0000e-04
Epoch 25/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2095 - mae: 0.0683 - val_loss: 0.2604 - val_mae: 0.0850 - learning_rate: 5.0000e-04
Epoch 26/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2201 - mae: 0.0716 - val_loss: 0.2690 - val_mae: 0.0878 - learning_rate: 5.0000e-04
Epoch 27/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2039 - mae: 0.0664 - val_loss: 0.2572 - val_mae: 0.0839 - learning_rate: 5.0000e-04
Epoch 28/30
57/58 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2140 - mae: 0.0697
Epoch 28: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2141 - mae: 0.0697 - val_loss: 0.2479 - val_mae: 0.0810 - learning_rate: 5.0000e-04
Epoch 29/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.2070 - mae: 0.0675 - val_loss: 0.2587 - val_mae: 0.0845 - learning_rate: 2.5000e-04
Epoch 30/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.2066 - mae: 0.0673 - val_loss: 0.2611 - val_mae: 0.0853 - learning_rate: 2.5000e-04
Restoring model weights from the end of the best epoch: 18.
  {'Model': 'GUMNet-Lite', 'Horizon': 1, 'MAE': 5.4403, 'RMSE': 9.746, 'RMSE($)': 9.746, 'MAPE(%)': 5.4322, 'SMAPE(%)': 5.322, 'R2': 0.7034, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - loss: 0.8855 - mae: 0.2697 - val_loss: 0.4204 - val_mae: 0.1359 - learning_rate: 0.0010
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3907 - mae: 0.1254 - val_loss: 0.2796 - val_mae: 0.0911 - learning_rate: 0.0010
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.3183 - mae: 0.1030 - val_loss: 0.2535 - val_mae: 0.0828 - learning_rate: 0.0010
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2969 - mae: 0.0963 - val_loss: 0.2670 - val_mae: 0.0868 - learning_rate: 0.0010
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3082 - mae: 0.0998 - val_loss: 0.2240 - val_mae: 0.0733 - learning_rate: 0.0010
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2666 - mae: 0.0866 - val_loss: 0.2892 - val_mae: 0.0939 - learning_rate: 0.0010
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2508 - mae: 0.0816 - val_loss: 0.2354 - val_mae: 0.0770 - learning_rate: 0.0010
Epoch 8/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2455 - mae: 0.0800 - val_loss: 0.1970 - val_mae: 0.0646 - learning_rate: 0.0010
Epoch 9/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2226 - mae: 0.0727 - val_loss: 0.2215 - val_mae: 0.0725 - learning_rate: 0.0010
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2183 - mae: 0.0713 - val_loss: 0.2422 - val_mae: 0.0791 - learning_rate: 0.0010
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2310 - mae: 0.0753 - val_loss: 0.1993 - val_mae: 0.0654 - learning_rate: 0.0010
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2146 - mae: 0.0700 - val_loss: 0.1849 - val_mae: 0.0607 - learning_rate: 0.0010
Epoch 13/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2131 - mae: 0.0696 - val_loss: 0.1937 - val_mae: 0.0635 - learning_rate: 0.0010
Epoch 14/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1998 - mae: 0.0653 - val_loss: 0.1771 - val_mae: 0.0582 - learning_rate: 0.0010
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2105 - mae: 0.0687 - val_loss: 0.1896 - val_mae: 0.0622 - learning_rate: 0.0010
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1938 - mae: 0.0633 - val_loss: 0.1888 - val_mae: 0.0619 - learning_rate: 0.0010
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1918 - mae: 0.0627 - val_loss: 0.1846 - val_mae: 0.0606 - learning_rate: 0.0010
Epoch 18/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1862 - mae: 0.0609 - val_loss: 0.2083 - val_mae: 0.0683 - learning_rate: 0.0010
Epoch 19/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1959 - mae: 0.0641 - val_loss: 0.1736 - val_mae: 0.0571 - learning_rate: 0.0010
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.1928 - mae: 0.0630 - val_loss: 0.2181 - val_mae: 0.0715 - learning_rate: 0.0010
Epoch 21/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1911 - mae: 0.0624 - val_loss: 0.1901 - val_mae: 0.0624 - learning_rate: 0.0010
Epoch 22/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1933 - mae: 0.0632 - val_loss: 0.1916 - val_mae: 0.0629 - learning_rate: 0.0010
Epoch 23/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1905 - mae: 0.0623 - val_loss: 0.1696 - val_mae: 0.0558 - learning_rate: 0.0010
Epoch 24/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1916 - mae: 0.0626 - val_loss: 0.2234 - val_mae: 0.0732 - learning_rate: 0.0010
Epoch 25/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1870 - mae: 0.0611 - val_loss: 0.1748 - val_mae: 0.0574 - learning_rate: 0.0010
Epoch 26/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.1887 - mae: 0.0617 - val_loss: 0.1882 - val_mae: 0.0618 - learning_rate: 0.0010
Epoch 27/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.1831 - mae: 0.0599 - val_loss: 0.1964 - val_mae: 0.0645 - learning_rate: 0.0010
Epoch 28/30
57/58 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1823 - mae: 0.0596
Epoch 28: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.1822 - mae: 0.0596 - val_loss: 0.2444 - val_mae: 0.0799 - learning_rate: 0.0010
Epoch 29/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.1726 - mae: 0.0565 - val_loss: 0.2024 - val_mae: 0.0664 - learning_rate: 5.0000e-04
Epoch 30/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1679 - mae: 0.0550 - val_loss: 0.2032 - val_mae: 0.0667 - learning_rate: 5.0000e-04
Restoring model weights from the end of the best epoch: 23.
  {'Model': 'GUMNet-Ultra', 'Horizon': 1, 'MAE': 5.2082, 'RMSE': 8.0017, 'RMSE($)': 8.0017, 'MAPE(%)': 5.5281, 'SMAPE(%)': 5.5228, 'R2': 0.8001, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}

2026-06-24 16:02:25,414	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
2026-06-24 16:02:25,881	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
Seed set to 1

  PatchTST/TFT skipped: Exception('PatchTST does not support historical exogenous variables.')
  [H=1] done in 180.7s
======================================================================
HORIZON H = 5
======================================================================
  {'Model': 'ARIMAX', 'Horizon': 5, 'MAE': 2.2064, 'RMSE': 4.0957, 'RMSE($)': 4.0957, 'MAPE(%)': 2.237, 'SMAPE(%)': 2.227, 'R2': 0.9478, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'SARIMA', 'Horizon': 5, 'MAE': 3.7698, 'RMSE': 6.9018, 'RMSE($)': 6.9018, 'MAPE(%)': 3.8635, 'SMAPE(%)': 3.9068, 'R2': 0.8518, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

H=5 OOF fold 1: 2018-02-15 -> 2020-04-09 | MAE=1.5391
H=5 OOF fold 2: 2020-04-13 -> 2022-06-02 | MAE=1.8911

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

H=5 OOF fold 3: 2022-06-03 -> 2024-07-25 | MAE=2.9214
H=5 Jump-Gated ARIMAX-CatBoost MAPE=2.2386% | MAE=2.2081
  {'Model': 'Jump-Gated ARIMAX-CatBoost', 'Horizon': 5, 'MAE': 2.2081, 'RMSE': 4.1143, 'RMSE($)': 4.1143, 'MAPE(%)': 2.2386, 'SMAPE(%)': 2.226, 'R2': 0.947, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'Ridge (Linear)', 'Horizon': 5, 'MAE': 3.221, 'RMSE': 5.6111, 'RMSE($)': 5.6111, 'MAPE(%)': 3.3541, 'SMAPE(%)': 3.3631, 'R2': 0.9013, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LightGBM', 'Horizon': 5, 'MAE': 3.7299, 'RMSE': 6.6666, 'RMSE($)': 6.6666, 'MAPE(%)': 3.8518, 'SMAPE(%)': 3.9712, 'R2': 0.8607, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LSTM', 'Horizon': 5, 'MAE': 6.3809, 'RMSE': 12.6172, 'RMSE($)': 12.6172, 'MAPE(%)': 6.2358, 'SMAPE(%)': 6.7112, 'R2': 0.5038, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 18s 60ms/step - loss: 1.0325 - mae: 0.3131 - val_loss: 1.0267 - val_mae: 0.3179 - learning_rate: 5.0000e-04
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.5379 - mae: 0.1709 - val_loss: 1.0401 - val_mae: 0.3222 - learning_rate: 5.0000e-04
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.4417 - mae: 0.1415 - val_loss: 1.0801 - val_mae: 0.3328 - learning_rate: 5.0000e-04
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.4363 - mae: 0.1400 - val_loss: 1.0390 - val_mae: 0.3213 - learning_rate: 5.0000e-04
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.3624 - mae: 0.1170 - val_loss: 0.8464 - val_mae: 0.2650 - learning_rate: 5.0000e-04
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.3454 - mae: 0.1117 - val_loss: 0.6929 - val_mae: 0.2185 - learning_rate: 5.0000e-04
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.3313 - mae: 0.1072 - val_loss: 0.7012 - val_mae: 0.2211 - learning_rate: 5.0000e-04
Epoch 8/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.3267 - mae: 0.1058 - val_loss: 0.7927 - val_mae: 0.2481 - learning_rate: 5.0000e-04
Epoch 9/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.3256 - mae: 0.1053 - val_loss: 0.5025 - val_mae: 0.1604 - learning_rate: 5.0000e-04
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2980 - mae: 0.0967 - val_loss: 0.4648 - val_mae: 0.1492 - learning_rate: 5.0000e-04
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.3046 - mae: 0.0987 - val_loss: 0.4732 - val_mae: 0.1516 - learning_rate: 5.0000e-04
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2952 - mae: 0.0958 - val_loss: 0.5397 - val_mae: 0.1715 - learning_rate: 5.0000e-04
Epoch 13/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2972 - mae: 0.0964 - val_loss: 0.5428 - val_mae: 0.1727 - learning_rate: 5.0000e-04
Epoch 14/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.3122 - mae: 0.1012 - val_loss: 0.4734 - val_mae: 0.1516 - learning_rate: 5.0000e-04
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2839 - mae: 0.0921 - val_loss: 0.4178 - val_mae: 0.1346 - learning_rate: 5.0000e-04
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2809 - mae: 0.0913 - val_loss: 0.4487 - val_mae: 0.1439 - learning_rate: 5.0000e-04
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2695 - mae: 0.0876 - val_loss: 0.3827 - val_mae: 0.1236 - learning_rate: 5.0000e-04
Epoch 18/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.2771 - mae: 0.0901 - val_loss: 0.4320 - val_mae: 0.1394 - learning_rate: 5.0000e-04
Epoch 19/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.2696 - mae: 0.0877 - val_loss: 0.4746 - val_mae: 0.1523 - learning_rate: 5.0000e-04
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.2812 - mae: 0.0913 - val_loss: 0.5018 - val_mae: 0.1603 - learning_rate: 5.0000e-04
Epoch 21/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.2907 - mae: 0.0944 - val_loss: 0.4374 - val_mae: 0.1410 - learning_rate: 5.0000e-04
Epoch 22/30
57/58 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.2631 - mae: 0.0856
Epoch 22: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.2631 - mae: 0.0856 - val_loss: 0.4286 - val_mae: 0.1381 - learning_rate: 5.0000e-04
Epoch 23/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.2549 - mae: 0.0830 - val_loss: 0.4099 - val_mae: 0.1325 - learning_rate: 2.5000e-04
Epoch 24/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2577 - mae: 0.0839 - val_loss: 0.4143 - val_mae: 0.1338 - learning_rate: 2.5000e-04
Epoch 25/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2574 - mae: 0.0838 - val_loss: 0.3965 - val_mae: 0.1281 - learning_rate: 2.5000e-04
Epoch 26/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2609 - mae: 0.0850 - val_loss: 0.4162 - val_mae: 0.1343 - learning_rate: 2.5000e-04
Epoch 27/30
57/58 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2521 - mae: 0.0821
Epoch 27: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.2522 - mae: 0.0821 - val_loss: 0.4177 - val_mae: 0.1346 - learning_rate: 2.5000e-04
Epoch 28/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.2541 - mae: 0.0828 - val_loss: 0.3681 - val_mae: 0.1191 - learning_rate: 1.2500e-04
Epoch 29/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2294 - mae: 0.0748 - val_loss: 0.3753 - val_mae: 0.1213 - learning_rate: 1.2500e-04
Epoch 30/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2278 - mae: 0.0744 - val_loss: 0.3782 - val_mae: 0.1222 - learning_rate: 1.2500e-04
Restoring model weights from the end of the best epoch: 28.
  {'Model': 'iTransformer', 'Horizon': 5, 'MAE': 6.2496, 'RMSE': 13.3032, 'RMSE($)': 13.3032, 'MAPE(%)': 5.8013, 'SMAPE(%)': 6.2432, 'R2': 0.4484, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 1.8940 - mae: 0.5464 - val_loss: 0.7328 - val_mae: 0.2321 - learning_rate: 0.0010
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.6600 - mae: 0.2074 - val_loss: 0.4789 - val_mae: 0.1535 - learning_rate: 0.0010
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.4904 - mae: 0.1565 - val_loss: 0.4936 - val_mae: 0.1575 - learning_rate: 0.0010
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.4005 - mae: 0.1286 - val_loss: 0.4223 - val_mae: 0.1354 - learning_rate: 0.0010
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3662 - mae: 0.1179 - val_loss: 0.3903 - val_mae: 0.1256 - learning_rate: 0.0010
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3501 - mae: 0.1128 - val_loss: 0.3661 - val_mae: 0.1183 - learning_rate: 0.0010
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3230 - mae: 0.1043 - val_loss: 0.4009 - val_mae: 0.1291 - learning_rate: 0.0010
Epoch 8/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3258 - mae: 0.1052 - val_loss: 0.3959 - val_mae: 0.1278 - learning_rate: 0.0010
Epoch 9/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3111 - mae: 0.1005 - val_loss: 0.4132 - val_mae: 0.1333 - learning_rate: 0.0010
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3105 - mae: 0.1003 - val_loss: 0.3326 - val_mae: 0.1078 - learning_rate: 0.0010
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3087 - mae: 0.0998 - val_loss: 0.3644 - val_mae: 0.1177 - learning_rate: 0.0010
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2966 - mae: 0.0960 - val_loss: 0.3385 - val_mae: 0.1097 - learning_rate: 0.0010
Epoch 13/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2760 - mae: 0.0895 - val_loss: 0.3371 - val_mae: 0.1092 - learning_rate: 0.0010
Epoch 14/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2858 - mae: 0.0925 - val_loss: 0.3344 - val_mae: 0.1084 - learning_rate: 0.0010
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2933 - mae: 0.0949 - val_loss: 0.3323 - val_mae: 0.1078 - learning_rate: 0.0010
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2749 - mae: 0.0891 - val_loss: 0.3359 - val_mae: 0.1090 - learning_rate: 0.0010
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3027 - mae: 0.0978 - val_loss: 0.3563 - val_mae: 0.1154 - learning_rate: 0.0010
Epoch 18/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2826 - mae: 0.0915 - val_loss: 0.3386 - val_mae: 0.1097 - learning_rate: 0.0010
Epoch 19/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2608 - mae: 0.0846 - val_loss: 0.3517 - val_mae: 0.1138 - learning_rate: 0.0010
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2605 - mae: 0.0845 - val_loss: 0.3253 - val_mae: 0.1054 - learning_rate: 0.0010
Epoch 21/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2559 - mae: 0.0831 - val_loss: 0.4762 - val_mae: 0.1526 - learning_rate: 0.0010
Epoch 22/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2600 - mae: 0.0844 - val_loss: 0.3801 - val_mae: 0.1227 - learning_rate: 0.0010
Epoch 23/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2593 - mae: 0.0840 - val_loss: 0.4236 - val_mae: 0.1364 - learning_rate: 0.0010
Epoch 24/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2647 - mae: 0.0859 - val_loss: 0.3719 - val_mae: 0.1202 - learning_rate: 0.0010
Epoch 25/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2579 - mae: 0.0837 - val_loss: 0.3191 - val_mae: 0.1034 - learning_rate: 0.0010
Epoch 26/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2458 - mae: 0.0798 - val_loss: 0.3738 - val_mae: 0.1207 - learning_rate: 0.0010
Epoch 27/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2450 - mae: 0.0796 - val_loss: 0.3310 - val_mae: 0.1071 - learning_rate: 0.0010
Epoch 28/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2392 - mae: 0.0778 - val_loss: 0.3408 - val_mae: 0.1102 - learning_rate: 0.0010
Epoch 29/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2563 - mae: 0.0831 - val_loss: 0.3107 - val_mae: 0.1007 - learning_rate: 0.0010
Epoch 30/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2376 - mae: 0.0772 - val_loss: 0.3295 - val_mae: 0.1068 - learning_rate: 0.0010
Restoring model weights from the end of the best epoch: 29.
  {'Model': 'GUMNet-Lite', 'Horizon': 5, 'MAE': 6.9016, 'RMSE': 10.3825, 'RMSE($)': 10.3825, 'MAPE(%)': 7.3572, 'SMAPE(%)': 7.3521, 'R2': 0.664, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 1.0608 - mae: 0.3197 - val_loss: 0.3615 - val_mae: 0.1171 - learning_rate: 0.0010
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.4513 - mae: 0.1443 - val_loss: 0.3342 - val_mae: 0.1084 - learning_rate: 0.0010
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.4118 - mae: 0.1323 - val_loss: 0.3341 - val_mae: 0.1084 - learning_rate: 0.0010
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.3857 - mae: 0.1241 - val_loss: 0.2698 - val_mae: 0.0878 - learning_rate: 0.0010
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.3533 - mae: 0.1141 - val_loss: 0.3035 - val_mae: 0.0986 - learning_rate: 0.0010
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.3412 - mae: 0.1103 - val_loss: 0.3241 - val_mae: 0.1052 - learning_rate: 0.0010
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3202 - mae: 0.1036 - val_loss: 0.2912 - val_mae: 0.0947 - learning_rate: 0.0010
Epoch 8/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.3031 - mae: 0.0983 - val_loss: 0.2968 - val_mae: 0.0965 - learning_rate: 0.0010
Epoch 9/30
56/58 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2984 - mae: 0.0968
Epoch 9: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2982 - mae: 0.0968 - val_loss: 0.2865 - val_mae: 0.0932 - learning_rate: 0.0010
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2799 - mae: 0.0910 - val_loss: 0.3019 - val_mae: 0.0981 - learning_rate: 5.0000e-04
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2805 - mae: 0.0911 - val_loss: 0.3092 - val_mae: 0.1004 - learning_rate: 5.0000e-04
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2691 - mae: 0.0875 - val_loss: 0.3129 - val_mae: 0.1017 - learning_rate: 5.0000e-04
Epoch 13/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2586 - mae: 0.0842 - val_loss: 0.3248 - val_mae: 0.1054 - learning_rate: 5.0000e-04
Epoch 14/30
57/58 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2479 - mae: 0.0807
Epoch 14: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2476 - mae: 0.0807 - val_loss: 0.3077 - val_mae: 0.1000 - learning_rate: 5.0000e-04
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2364 - mae: 0.0771 - val_loss: 0.3075 - val_mae: 0.0999 - learning_rate: 2.5000e-04
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2330 - mae: 0.0760 - val_loss: 0.3120 - val_mae: 0.1014 - learning_rate: 2.5000e-04
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2339 - mae: 0.0763 - val_loss: 0.3145 - val_mae: 0.1022 - learning_rate: 2.5000e-04
Epoch 18/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2344 - mae: 0.0765 - val_loss: 0.3153 - val_mae: 0.1024 - learning_rate: 2.5000e-04
Epoch 19/30
55/58 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2260 - mae: 0.0737
Epoch 19: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2258 - mae: 0.0737 - val_loss: 0.3162 - val_mae: 0.1027 - learning_rate: 2.5000e-04
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2124 - mae: 0.0694 - val_loss: 0.3119 - val_mae: 0.1013 - learning_rate: 1.2500e-04
Epoch 21/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2126 - mae: 0.0695 - val_loss: 0.3125 - val_mae: 0.1015 - learning_rate: 1.2500e-04
Epoch 22/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2065 - mae: 0.0675 - val_loss: 0.3105 - val_mae: 0.1008 - learning_rate: 1.2500e-04
Epoch 23/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2118 - mae: 0.0692 - val_loss: 0.3080 - val_mae: 0.1001 - learning_rate: 1.2500e-04
Epoch 24/30
57/58 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2142 - mae: 0.0700
Epoch 24: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2140 - mae: 0.0699 - val_loss: 0.3201 - val_mae: 0.1039 - learning_rate: 1.2500e-04
Epoch 24: early stopping
Restoring model weights from the end of the best epoch: 4.

Seed set to 1

  {'Model': 'GUMNet-Ultra', 'Horizon': 5, 'MAE': 5.1314, 'RMSE': 11.1225, 'RMSE($)': 11.1225, 'MAPE(%)': 5.0157, 'SMAPE(%)': 5.3592, 'R2': 0.6144, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  PatchTST/TFT skipped: Exception('PatchTST does not support historical exogenous variables.')
  [H=5] done in 174.0s
======================================================================
HORIZON H = 10
======================================================================
  {'Model': 'ARIMAX', 'Horizon': 10, 'MAE': 2.7976, 'RMSE': 5.0518, 'RMSE($)': 5.0518, 'MAPE(%)': 2.8368, 'SMAPE(%)': 2.8177, 'R2': 0.9214, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'SARIMA', 'Horizon': 10, 'MAE': 4.8785, 'RMSE': 10.2419, 'RMSE($)': 10.2419, 'MAPE(%)': 4.8296, 'SMAPE(%)': 5.021, 'R2': 0.6771, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

H=10 OOF fold 1: 2018-02-19 -> 2020-04-14 | MAE=1.9766
H=10 OOF fold 2: 2020-04-15 -> 2022-06-03 | MAE=2.8092

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

H=10 OOF fold 3: 2022-06-06 -> 2024-07-25 | MAE=4.2782
H=10 Jump-Gated ARIMAX-CatBoost MAPE=2.9025% | MAE=2.8709
  {'Model': 'Jump-Gated ARIMAX-CatBoost', 'Horizon': 10, 'MAE': 2.8709, 'RMSE': 5.2355, 'RMSE($)': 5.2355, 'MAPE(%)': 2.9025, 'SMAPE(%)': 2.8713, 'R2': 0.9141, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'Ridge (Linear)', 'Horizon': 10, 'MAE': 4.9014, 'RMSE': 9.8235, 'RMSE($)': 9.8235, 'MAPE(%)': 4.8589, 'SMAPE(%)': 4.8678, 'R2': 0.6976, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LightGBM', 'Horizon': 10, 'MAE': 6.9878, 'RMSE': 13.5859, 'RMSE($)': 13.5859, 'MAPE(%)': 6.7443, 'SMAPE(%)': 7.1135, 'R2': 0.4216, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LSTM', 'Horizon': 10, 'MAE': 7.1767, 'RMSE': 13.8675, 'RMSE($)': 13.8675, 'MAPE(%)': 6.9301, 'SMAPE(%)': 7.3777, 'R2': 0.4029, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 18s 62ms/step - loss: 1.0523 - mae: 0.3187 - val_loss: 1.3479 - val_mae: 0.4101 - learning_rate: 5.0000e-04
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.5695 - mae: 0.1804 - val_loss: 1.2374 - val_mae: 0.3781 - learning_rate: 5.0000e-04
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.5280 - mae: 0.1678 - val_loss: 1.3414 - val_mae: 0.4051 - learning_rate: 5.0000e-04
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.4663 - mae: 0.1491 - val_loss: 1.3423 - val_mae: 0.4068 - learning_rate: 5.0000e-04
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.4146 - mae: 0.1331 - val_loss: 1.2339 - val_mae: 0.3762 - learning_rate: 5.0000e-04
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.4113 - mae: 0.1321 - val_loss: 0.9860 - val_mae: 0.3058 - learning_rate: 5.0000e-04
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.3547 - mae: 0.1144 - val_loss: 0.8215 - val_mae: 0.2586 - learning_rate: 5.0000e-04
Epoch 8/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.3773 - mae: 0.1216 - val_loss: 0.6883 - val_mae: 0.2181 - learning_rate: 5.0000e-04
Epoch 9/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.3466 - mae: 0.1119 - val_loss: 0.8275 - val_mae: 0.2602 - learning_rate: 5.0000e-04
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.3244 - mae: 0.1049 - val_loss: 0.8554 - val_mae: 0.2675 - learning_rate: 5.0000e-04
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.3180 - mae: 0.1030 - val_loss: 1.0483 - val_mae: 0.3239 - learning_rate: 5.0000e-04
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.3222 - mae: 0.1043 - val_loss: 0.7932 - val_mae: 0.2488 - learning_rate: 5.0000e-04
Epoch 13/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.3132 - mae: 0.1015
Epoch 13: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.3131 - mae: 0.1014 - val_loss: 1.1131 - val_mae: 0.3426 - learning_rate: 5.0000e-04
Epoch 14/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.3026 - mae: 0.0981 - val_loss: 0.8295 - val_mae: 0.2601 - learning_rate: 2.5000e-04
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.2904 - mae: 0.0942 - val_loss: 0.7997 - val_mae: 0.2511 - learning_rate: 2.5000e-04
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.2888 - mae: 0.0937 - val_loss: 0.7858 - val_mae: 0.2469 - learning_rate: 2.5000e-04
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.2873 - mae: 0.0932 - val_loss: 0.7220 - val_mae: 0.2279 - learning_rate: 2.5000e-04
Epoch 18/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.2864 - mae: 0.0930 - val_loss: 0.6576 - val_mae: 0.2084 - learning_rate: 2.5000e-04
Epoch 19/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 0.2739 - mae: 0.0890 - val_loss: 0.6258 - val_mae: 0.1992 - learning_rate: 2.5000e-04
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.2823 - mae: 0.0916 - val_loss: 0.7360 - val_mae: 0.2322 - learning_rate: 2.5000e-04
Epoch 21/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2756 - mae: 0.0896 - val_loss: 0.6871 - val_mae: 0.2174 - learning_rate: 2.5000e-04
Epoch 22/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2743 - mae: 0.0891 - val_loss: 0.7220 - val_mae: 0.2280 - learning_rate: 2.5000e-04
Epoch 23/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2708 - mae: 0.0881 - val_loss: 0.8141 - val_mae: 0.2552 - learning_rate: 2.5000e-04
Epoch 24/30
57/58 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.2720 - mae: 0.0884
Epoch 24: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.2721 - mae: 0.0884 - val_loss: 0.7332 - val_mae: 0.2313 - learning_rate: 2.5000e-04
Epoch 25/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.2596 - mae: 0.0845 - val_loss: 0.7478 - val_mae: 0.2356 - learning_rate: 1.2500e-04
Epoch 26/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2606 - mae: 0.0848 - val_loss: 0.7020 - val_mae: 0.2219 - learning_rate: 1.2500e-04
Epoch 27/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2527 - mae: 0.0823 - val_loss: 0.6888 - val_mae: 0.2179 - learning_rate: 1.2500e-04
Epoch 28/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2468 - mae: 0.0804 - val_loss: 0.7614 - val_mae: 0.2397 - learning_rate: 1.2500e-04
Epoch 29/30
57/58 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.2526 - mae: 0.0822
Epoch 29: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2526 - mae: 0.0822 - val_loss: 0.6935 - val_mae: 0.2193 - learning_rate: 1.2500e-04
Epoch 30/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.2420 - mae: 0.0789 - val_loss: 0.7631 - val_mae: 0.2402 - learning_rate: 6.2500e-05
Restoring model weights from the end of the best epoch: 19.
  {'Model': 'iTransformer', 'Horizon': 10, 'MAE': 8.8148, 'RMSE': 16.6898, 'RMSE($)': 16.6898, 'MAPE(%)': 8.3307, 'SMAPE(%)': 8.9964, 'R2': 0.1352, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 1.9362 - mae: 0.5594 - val_loss: 0.8679 - val_mae: 0.2726 - learning_rate: 0.0010
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.6581 - mae: 0.2067 - val_loss: 0.4880 - val_mae: 0.1555 - learning_rate: 0.0010
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.4907 - mae: 0.1561 - val_loss: 0.4888 - val_mae: 0.1554 - learning_rate: 0.0010
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.4231 - mae: 0.1354 - val_loss: 0.4917 - val_mae: 0.1564 - learning_rate: 0.0010
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.4029 - mae: 0.1292 - val_loss: 0.4724 - val_mae: 0.1510 - learning_rate: 0.0010
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3761 - mae: 0.1210 - val_loss: 0.5081 - val_mae: 0.1618 - learning_rate: 0.0010
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3668 - mae: 0.1179 - val_loss: 0.4925 - val_mae: 0.1575 - learning_rate: 0.0010
Epoch 8/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3629 - mae: 0.1167 - val_loss: 0.4462 - val_mae: 0.1434 - learning_rate: 0.0010
Epoch 9/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3366 - mae: 0.1087 - val_loss: 0.4697 - val_mae: 0.1503 - learning_rate: 0.0010
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3321 - mae: 0.1071 - val_loss: 0.4871 - val_mae: 0.1555 - learning_rate: 0.0010
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3320 - mae: 0.1071 - val_loss: 0.4661 - val_mae: 0.1492 - learning_rate: 0.0010
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3192 - mae: 0.1030 - val_loss: 0.4332 - val_mae: 0.1394 - learning_rate: 0.0010
Epoch 13/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3152 - mae: 0.1019 - val_loss: 0.4733 - val_mae: 0.1517 - learning_rate: 0.0010
Epoch 14/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3088 - mae: 0.0998 - val_loss: 0.4613 - val_mae: 0.1478 - learning_rate: 0.0010
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3211 - mae: 0.1037 - val_loss: 0.4432 - val_mae: 0.1424 - learning_rate: 0.0010
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3019 - mae: 0.0976 - val_loss: 0.4201 - val_mae: 0.1351 - learning_rate: 0.0010
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2924 - mae: 0.0946 - val_loss: 0.4436 - val_mae: 0.1429 - learning_rate: 0.0010
Epoch 18/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2875 - mae: 0.0931 - val_loss: 0.4300 - val_mae: 0.1383 - learning_rate: 0.0010
Epoch 19/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2791 - mae: 0.0905 - val_loss: 0.4574 - val_mae: 0.1468 - learning_rate: 0.0010
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2705 - mae: 0.0876 - val_loss: 0.4524 - val_mae: 0.1456 - learning_rate: 0.0010
Epoch 21/30
57/58 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3100 - mae: 0.1002
Epoch 21: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3096 - mae: 0.1001 - val_loss: 0.4409 - val_mae: 0.1421 - learning_rate: 0.0010
Epoch 22/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2605 - mae: 0.0846 - val_loss: 0.4588 - val_mae: 0.1477 - learning_rate: 5.0000e-04
Epoch 23/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2462 - mae: 0.0800 - val_loss: 0.4298 - val_mae: 0.1384 - learning_rate: 5.0000e-04
Epoch 24/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2435 - mae: 0.0790 - val_loss: 0.4357 - val_mae: 0.1405 - learning_rate: 5.0000e-04
Epoch 25/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2463 - mae: 0.0800 - val_loss: 0.4211 - val_mae: 0.1356 - learning_rate: 5.0000e-04
Epoch 26/30
55/58 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2527 - mae: 0.0820
Epoch 26: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2524 - mae: 0.0819 - val_loss: 0.4306 - val_mae: 0.1385 - learning_rate: 5.0000e-04
Epoch 27/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2425 - mae: 0.0788 - val_loss: 0.4165 - val_mae: 0.1342 - learning_rate: 2.5000e-04
Epoch 28/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2223 - mae: 0.0724 - val_loss: 0.4365 - val_mae: 0.1406 - learning_rate: 2.5000e-04
Epoch 29/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2366 - mae: 0.0770 - val_loss: 0.4421 - val_mae: 0.1424 - learning_rate: 2.5000e-04
Epoch 30/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2299 - mae: 0.0748 - val_loss: 0.4309 - val_mae: 0.1388 - learning_rate: 2.5000e-04
Restoring model weights from the end of the best epoch: 27.
  {'Model': 'GUMNet-Lite', 'Horizon': 10, 'MAE': 8.6404, 'RMSE': 14.488, 'RMSE($)': 14.488, 'MAPE(%)': 8.8074, 'SMAPE(%)': 9.3575, 'R2': 0.3483, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 1.0927 - mae: 0.3296 - val_loss: 0.4913 - val_mae: 0.1577 - learning_rate: 0.0010
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.4548 - mae: 0.1456 - val_loss: 0.3271 - val_mae: 0.1061 - learning_rate: 0.0010
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3866 - mae: 0.1244 - val_loss: 0.3310 - val_mae: 0.1074 - learning_rate: 0.0010
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3517 - mae: 0.1136 - val_loss: 0.3032 - val_mae: 0.0985 - learning_rate: 0.0010
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.3479 - mae: 0.1123 - val_loss: 0.3345 - val_mae: 0.1085 - learning_rate: 0.0010
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3290 - mae: 0.1064 - val_loss: 0.3462 - val_mae: 0.1123 - learning_rate: 0.0010
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.3159 - mae: 0.1023 - val_loss: 0.3905 - val_mae: 0.1263 - learning_rate: 0.0010
Epoch 8/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3104 - mae: 0.1005 - val_loss: 0.3764 - val_mae: 0.1218 - learning_rate: 0.0010
Epoch 9/30
56/58 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2954 - mae: 0.0958
Epoch 9: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2952 - mae: 0.0957 - val_loss: 0.3764 - val_mae: 0.1219 - learning_rate: 0.0010
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2943 - mae: 0.0955 - val_loss: 0.3590 - val_mae: 0.1164 - learning_rate: 5.0000e-04
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2630 - mae: 0.0856 - val_loss: 0.3599 - val_mae: 0.1166 - learning_rate: 5.0000e-04
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2596 - mae: 0.0845 - val_loss: 0.3534 - val_mae: 0.1147 - learning_rate: 5.0000e-04
Epoch 13/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2526 - mae: 0.0822 - val_loss: 0.3758 - val_mae: 0.1217 - learning_rate: 5.0000e-04
Epoch 14/30
56/58 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2567 - mae: 0.0835
Epoch 14: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2565 - mae: 0.0835 - val_loss: 0.3794 - val_mae: 0.1229 - learning_rate: 5.0000e-04
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2497 - mae: 0.0814 - val_loss: 0.3884 - val_mae: 0.1258 - learning_rate: 2.5000e-04
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2404 - mae: 0.0784 - val_loss: 0.3941 - val_mae: 0.1275 - learning_rate: 2.5000e-04
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2285 - mae: 0.0746 - val_loss: 0.3767 - val_mae: 0.1220 - learning_rate: 2.5000e-04
Epoch 18/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2374 - mae: 0.0774 - val_loss: 0.3832 - val_mae: 0.1240 - learning_rate: 2.5000e-04
Epoch 19/30
54/58 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2245 - mae: 0.0733
Epoch 19: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2248 - mae: 0.0734 - val_loss: 0.3931 - val_mae: 0.1272 - learning_rate: 2.5000e-04
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2334 - mae: 0.0761 - val_loss: 0.3820 - val_mae: 0.1237 - learning_rate: 1.2500e-04
Epoch 21/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2176 - mae: 0.0711 - val_loss: 0.3829 - val_mae: 0.1240 - learning_rate: 1.2500e-04
Epoch 22/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2168 - mae: 0.0708 - val_loss: 0.3932 - val_mae: 0.1272 - learning_rate: 1.2500e-04
Epoch 23/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2190 - mae: 0.0715 - val_loss: 0.3825 - val_mae: 0.1239 - learning_rate: 1.2500e-04
Epoch 24/30
55/58 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2212 - mae: 0.0722
Epoch 24: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2213 - mae: 0.0722 - val_loss: 0.3731 - val_mae: 0.1209 - learning_rate: 1.2500e-04
Epoch 24: early stopping
Restoring model weights from the end of the best epoch: 4.

Seed set to 1

  {'Model': 'GUMNet-Ultra', 'Horizon': 10, 'MAE': 7.3008, 'RMSE': 12.9087, 'RMSE($)': 12.9087, 'MAPE(%)': 7.4027, 'SMAPE(%)': 7.6685, 'R2': 0.4826, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  PatchTST/TFT skipped: Exception('PatchTST does not support historical exogenous variables.')
  [H=10] done in 188.7s
======================================================================
HORIZON H = 15
======================================================================
  {'Model': 'ARIMAX', 'Horizon': 15, 'MAE': 3.4452, 'RMSE': 6.0917, 'RMSE($)': 6.0917, 'MAPE(%)': 3.4864, 'SMAPE(%)': 3.4515, 'R2': 0.887, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'SARIMA', 'Horizon': 15, 'MAE': 5.989, 'RMSE': 13.2602, 'RMSE($)': 13.2602, 'MAPE(%)': 5.7751, 'SMAPE(%)': 6.1194, 'R2': 0.4644, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
H=15 OOF fold 1: 2018-02-21 -> 2020-04-15 | MAE=2.2350

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

H=15 OOF fold 2: 2020-04-16 -> 2022-06-06 | MAE=3.5623

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

H=15 OOF fold 3: 2022-06-07 -> 2024-07-26 | MAE=5.3024
H=15 Jump-Gated ARIMAX-CatBoost MAPE=3.7851% | MAE=3.8155
  {'Model': 'Jump-Gated ARIMAX-CatBoost', 'Horizon': 15, 'MAE': 3.8155, 'RMSE': 7.1464, 'RMSE($)': 7.1464, 'MAPE(%)': 3.7851, 'SMAPE(%)': 3.7098, 'R2': 0.8402, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'Ridge (Linear)', 'Horizon': 15, 'MAE': 6.9117, 'RMSE': 14.1907, 'RMSE($)': 14.1907, 'MAPE(%)': 6.6103, 'SMAPE(%)': 6.6098, 'R2': 0.3701, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LightGBM', 'Horizon': 15, 'MAE': 5.8184, 'RMSE': 12.972, 'RMSE($)': 12.972, 'MAPE(%)': 5.5677, 'SMAPE(%)': 5.9632, 'R2': 0.4736, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LSTM', 'Horizon': 15, 'MAE': 7.987, 'RMSE': 16.2082, 'RMSE($)': 16.2082, 'MAPE(%)': 7.4945, 'SMAPE(%)': 8.1589, 'R2': 0.1859, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 12s 46ms/step - loss: 1.0283 - mae: 0.3118 - val_loss: 1.2163 - val_mae: 0.3745 - learning_rate: 5.0000e-04
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.5805 - mae: 0.1839 - val_loss: 1.2327 - val_mae: 0.3775 - learning_rate: 5.0000e-04
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.5236 - mae: 0.1665 - val_loss: 1.1826 - val_mae: 0.3623 - learning_rate: 5.0000e-04
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.4680 - mae: 0.1496 - val_loss: 0.9686 - val_mae: 0.3011 - learning_rate: 5.0000e-04
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.4377 - mae: 0.1402 - val_loss: 1.0025 - val_mae: 0.3108 - learning_rate: 5.0000e-04
Epoch 6/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.4020 - mae: 0.1291 - val_loss: 1.2079 - val_mae: 0.3713 - learning_rate: 5.0000e-04
Epoch 7/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.3999 - mae: 0.1285 - val_loss: 1.1782 - val_mae: 0.3616 - learning_rate: 5.0000e-04
Epoch 8/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.3593 - mae: 0.1158 - val_loss: 0.9805 - val_mae: 0.3046 - learning_rate: 5.0000e-04
Epoch 9/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.3659 - mae: 0.1178
Epoch 9: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.3659 - mae: 0.1178 - val_loss: 1.0086 - val_mae: 0.3124 - learning_rate: 5.0000e-04
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.3473 - mae: 0.1120 - val_loss: 0.7529 - val_mae: 0.2375 - learning_rate: 2.5000e-04
Epoch 11/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.3428 - mae: 0.1106 - val_loss: 0.7607 - val_mae: 0.2399 - learning_rate: 2.5000e-04
Epoch 12/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.3390 - mae: 0.1094 - val_loss: 0.8018 - val_mae: 0.2517 - learning_rate: 2.5000e-04
Epoch 13/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.3374 - mae: 0.1089 - val_loss: 0.7186 - val_mae: 0.2272 - learning_rate: 2.5000e-04
Epoch 14/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.3269 - mae: 0.1056 - val_loss: 0.8260 - val_mae: 0.2591 - learning_rate: 2.5000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.3209 - mae: 0.1037 - val_loss: 0.7724 - val_mae: 0.2429 - learning_rate: 2.5000e-04
Epoch 16/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.3288 - mae: 0.1062 - val_loss: 0.7577 - val_mae: 0.2389 - learning_rate: 2.5000e-04
Epoch 17/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.3232 - mae: 0.1045 - val_loss: 0.8300 - val_mae: 0.2603 - learning_rate: 2.5000e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.3055 - mae: 0.0989
Epoch 18: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.3055 - mae: 0.0988 - val_loss: 0.7818 - val_mae: 0.2462 - learning_rate: 2.5000e-04
Epoch 19/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.3120 - mae: 0.1009 - val_loss: 0.8568 - val_mae: 0.2680 - learning_rate: 1.2500e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.3007 - mae: 0.0973 - val_loss: 0.8196 - val_mae: 0.2571 - learning_rate: 1.2500e-04
Epoch 21/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.3052 - mae: 0.0988 - val_loss: 0.8397 - val_mae: 0.2631 - learning_rate: 1.2500e-04
Epoch 22/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.2998 - mae: 0.0970 - val_loss: 0.8487 - val_mae: 0.2656 - learning_rate: 1.2500e-04
Epoch 23/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.2899 - mae: 0.0940
Epoch 23: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.2899 - mae: 0.0940 - val_loss: 0.7986 - val_mae: 0.2509 - learning_rate: 1.2500e-04
Epoch 24/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.2932 - mae: 0.0951 - val_loss: 0.8816 - val_mae: 0.2752 - learning_rate: 6.2500e-05
Epoch 25/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2906 - mae: 0.0941 - val_loss: 0.8228 - val_mae: 0.2580 - learning_rate: 6.2500e-05
Epoch 26/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.2868 - mae: 0.0930 - val_loss: 0.8548 - val_mae: 0.2673 - learning_rate: 6.2500e-05
Epoch 27/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.2825 - mae: 0.0916 - val_loss: 0.8533 - val_mae: 0.2672 - learning_rate: 6.2500e-05
Epoch 28/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.2789 - mae: 0.0905
Epoch 28: ReduceLROnPlateau reducing learning rate to 3.125000148429535e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.2790 - mae: 0.0905 - val_loss: 0.8660 - val_mae: 0.2708 - learning_rate: 6.2500e-05
Epoch 29/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.2840 - mae: 0.0921 - val_loss: 0.8716 - val_mae: 0.2724 - learning_rate: 3.1250e-05
Epoch 30/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.2847 - mae: 0.0923 - val_loss: 0.8095 - val_mae: 0.2543 - learning_rate: 3.1250e-05
Restoring model weights from the end of the best epoch: 13.
  {'Model': 'iTransformer', 'Horizon': 15, 'MAE': 9.9165, 'RMSE': 16.8872, 'RMSE($)': 16.8872, 'MAPE(%)': 9.8041, 'SMAPE(%)': 10.272, 'R2': 0.1163, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - loss: 1.9423 - mae: 0.5595 - val_loss: 0.4057 - val_mae: 0.1308 - learning_rate: 0.0010
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.5889 - mae: 0.1861 - val_loss: 0.6075 - val_mae: 0.1926 - learning_rate: 0.0010
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.4719 - mae: 0.1505 - val_loss: 0.6053 - val_mae: 0.1914 - learning_rate: 0.0010
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.4335 - mae: 0.1385 - val_loss: 0.5542 - val_mae: 0.1766 - learning_rate: 0.0010
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.4027 - mae: 0.1290 - val_loss: 0.5269 - val_mae: 0.1678 - learning_rate: 0.0010
Epoch 6/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3736 - mae: 0.1200
Epoch 6: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3735 - mae: 0.1200 - val_loss: 0.6047 - val_mae: 0.1922 - learning_rate: 0.0010
Epoch 7/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3512 - mae: 0.1129 - val_loss: 0.5854 - val_mae: 0.1861 - learning_rate: 5.0000e-04
Epoch 8/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.3324 - mae: 0.1071 - val_loss: 0.6011 - val_mae: 0.1911 - learning_rate: 5.0000e-04
Epoch 9/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3325 - mae: 0.1071 - val_loss: 0.5770 - val_mae: 0.1832 - learning_rate: 5.0000e-04
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3224 - mae: 0.1041 - val_loss: 0.6116 - val_mae: 0.1941 - learning_rate: 5.0000e-04
Epoch 11/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3221 - mae: 0.1039
Epoch 11: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3218 - mae: 0.1038 - val_loss: 0.6054 - val_mae: 0.1925 - learning_rate: 5.0000e-04
Epoch 12/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3097 - mae: 0.1001 - val_loss: 0.5913 - val_mae: 0.1881 - learning_rate: 2.5000e-04
Epoch 13/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.3060 - mae: 0.0988 - val_loss: 0.5951 - val_mae: 0.1892 - learning_rate: 2.5000e-04
Epoch 14/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2955 - mae: 0.0955 - val_loss: 0.5770 - val_mae: 0.1835 - learning_rate: 2.5000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3031 - mae: 0.0979 - val_loss: 0.5936 - val_mae: 0.1887 - learning_rate: 2.5000e-04
Epoch 16/30
55/57 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2929 - mae: 0.0946
Epoch 16: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2929 - mae: 0.0946 - val_loss: 0.6013 - val_mae: 0.1912 - learning_rate: 2.5000e-04
Epoch 17/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2985 - mae: 0.0964 - val_loss: 0.5611 - val_mae: 0.1784 - learning_rate: 1.2500e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2890 - mae: 0.0935 - val_loss: 0.5872 - val_mae: 0.1866 - learning_rate: 1.2500e-04
Epoch 19/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2877 - mae: 0.0930 - val_loss: 0.5810 - val_mae: 0.1848 - learning_rate: 1.2500e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2819 - mae: 0.0911 - val_loss: 0.5924 - val_mae: 0.1885 - learning_rate: 1.2500e-04
Epoch 21/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2816 - mae: 0.0912
Epoch 21: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2816 - mae: 0.0912 - val_loss: 0.5781 - val_mae: 0.1839 - learning_rate: 1.2500e-04
Epoch 21: early stopping
Restoring model weights from the end of the best epoch: 1.
  {'Model': 'GUMNet-Lite', 'Horizon': 15, 'MAE': 9.535, 'RMSE': 18.1597, 'RMSE($)': 18.1597, 'MAPE(%)': 9.2869, 'SMAPE(%)': 10.3792, 'R2': -0.0219, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - loss: 1.1123 - mae: 0.3361 - val_loss: 0.4126 - val_mae: 0.1328 - learning_rate: 0.0010
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.4727 - mae: 0.1509 - val_loss: 0.4295 - val_mae: 0.1380 - learning_rate: 0.0010
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.4144 - mae: 0.1331 - val_loss: 0.3801 - val_mae: 0.1228 - learning_rate: 0.0010
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3853 - mae: 0.1238 - val_loss: 0.4090 - val_mae: 0.1318 - learning_rate: 0.0010
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3532 - mae: 0.1141 - val_loss: 0.4052 - val_mae: 0.1307 - learning_rate: 0.0010
Epoch 6/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3515 - mae: 0.1135 - val_loss: 0.4096 - val_mae: 0.1318 - learning_rate: 0.0010
Epoch 7/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3237 - mae: 0.1048 - val_loss: 0.4328 - val_mae: 0.1392 - learning_rate: 0.0010
Epoch 8/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3091 - mae: 0.1001
Epoch 8: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3092 - mae: 0.1001 - val_loss: 0.4959 - val_mae: 0.1588 - learning_rate: 0.0010
Epoch 9/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2886 - mae: 0.0937 - val_loss: 0.4600 - val_mae: 0.1476 - learning_rate: 5.0000e-04
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2811 - mae: 0.0913 - val_loss: 0.4582 - val_mae: 0.1470 - learning_rate: 5.0000e-04
Epoch 11/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2701 - mae: 0.0878 - val_loss: 0.4440 - val_mae: 0.1427 - learning_rate: 5.0000e-04
Epoch 12/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2647 - mae: 0.0861 - val_loss: 0.4306 - val_mae: 0.1384 - learning_rate: 5.0000e-04
Epoch 13/30
54/57 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.2581 - mae: 0.0840
Epoch 13: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.2583 - mae: 0.0840 - val_loss: 0.4497 - val_mae: 0.1445 - learning_rate: 5.0000e-04
Epoch 14/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2486 - mae: 0.0810 - val_loss: 0.4998 - val_mae: 0.1600 - learning_rate: 2.5000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2425 - mae: 0.0790 - val_loss: 0.4933 - val_mae: 0.1580 - learning_rate: 2.5000e-04
Epoch 16/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2311 - mae: 0.0753 - val_loss: 0.4574 - val_mae: 0.1468 - learning_rate: 2.5000e-04
Epoch 17/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2334 - mae: 0.0761 - val_loss: 0.4442 - val_mae: 0.1427 - learning_rate: 2.5000e-04
Epoch 18/30
55/57 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2360 - mae: 0.0769
Epoch 18: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2357 - mae: 0.0768 - val_loss: 0.4461 - val_mae: 0.1434 - learning_rate: 2.5000e-04
Epoch 19/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2260 - mae: 0.0737 - val_loss: 0.4618 - val_mae: 0.1482 - learning_rate: 1.2500e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2170 - mae: 0.0709 - val_loss: 0.4739 - val_mae: 0.1520 - learning_rate: 1.2500e-04
Epoch 21/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2181 - mae: 0.0712 - val_loss: 0.4657 - val_mae: 0.1494 - learning_rate: 1.2500e-04
Epoch 22/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2193 - mae: 0.0716 - val_loss: 0.4591 - val_mae: 0.1474 - learning_rate: 1.2500e-04
Epoch 23/30
54/57 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2117 - mae: 0.0692
Epoch 23: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2119 - mae: 0.0693 - val_loss: 0.4615 - val_mae: 0.1481 - learning_rate: 1.2500e-04
Epoch 23: early stopping
Restoring model weights from the end of the best epoch: 3.

Seed set to 1

  {'Model': 'GUMNet-Ultra', 'Horizon': 15, 'MAE': 7.9173, 'RMSE': 14.64, 'RMSE($)': 14.64, 'MAPE(%)': 7.7827, 'SMAPE(%)': 8.1845, 'R2': 0.3359, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  PatchTST/TFT skipped: Exception('PatchTST does not support historical exogenous variables.')
  [H=15] done in 187.6s
======================================================================
HORIZON H = 20
======================================================================
  {'Model': 'ARIMAX', 'Horizon': 20, 'MAE': 3.7859, 'RMSE': 6.7586, 'RMSE($)': 6.7586, 'MAPE(%)': 3.8622, 'SMAPE(%)': 3.8016, 'R2': 0.8624, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'SARIMA', 'Horizon': 20, 'MAE': 7.1636, 'RMSE': 15.4098, 'RMSE($)': 15.4098, 'MAPE(%)': 6.833, 'SMAPE(%)': 7.3191, 'R2': 0.2847, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
H=20 OOF fold 1: 2018-02-23 -> 2020-04-17 | MAE=2.4591
H=20 OOF fold 2: 2020-04-20 -> 2022-06-07 | MAE=4.1888
H=20 OOF fold 3: 2022-06-08 -> 2024-07-26 | MAE=6.0517
H=20 Jump-Gated ARIMAX-CatBoost MAPE=4.3419% | MAE=4.3955
  {'Model': 'Jump-Gated ARIMAX-CatBoost', 'Horizon': 20, 'MAE': 4.3955, 'RMSE': 8.6984, 'RMSE($)': 8.6984, 'MAPE(%)': 4.3419, 'SMAPE(%)': 4.2022, 'R2': 0.7633, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'Ridge (Linear)', 'Horizon': 20, 'MAE': 8.5732, 'RMSE': 17.7561, 'RMSE($)': 17.7561, 'MAPE(%)': 8.092, 'SMAPE(%)': 7.9662, 'R2': 0.0137, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LightGBM', 'Horizon': 20, 'MAE': 8.821, 'RMSE': 16.1713, 'RMSE($)': 16.1713, 'MAPE(%)': 8.6723, 'SMAPE(%)': 9.1415, 'R2': 0.1819, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LSTM', 'Horizon': 20, 'MAE': 8.5956, 'RMSE': 17.3112, 'RMSE($)': 17.3112, 'MAPE(%)': 8.0355, 'SMAPE(%)': 8.8246, 'R2': 0.0755, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 12s 51ms/step - loss: 0.9175 - mae: 0.2814 - val_loss: 2.0626 - val_mae: 0.6091 - learning_rate: 5.0000e-04
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.5665 - mae: 0.1796 - val_loss: 1.9103 - val_mae: 0.5645 - learning_rate: 5.0000e-04
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.5123 - mae: 0.1630 - val_loss: 1.8320 - val_mae: 0.5434 - learning_rate: 5.0000e-04
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.4738 - mae: 0.1513 - val_loss: 1.6046 - val_mae: 0.4813 - learning_rate: 5.0000e-04
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.4414 - mae: 0.1411 - val_loss: 1.4944 - val_mae: 0.4515 - learning_rate: 5.0000e-04
Epoch 6/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.4186 - mae: 0.1341 - val_loss: 1.3681 - val_mae: 0.4164 - learning_rate: 5.0000e-04
Epoch 7/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.4109 - mae: 0.1317 - val_loss: 1.4402 - val_mae: 0.4361 - learning_rate: 5.0000e-04
Epoch 8/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.4075 - mae: 0.1307 - val_loss: 1.4404 - val_mae: 0.4360 - learning_rate: 5.0000e-04
Epoch 9/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.3726 - mae: 0.1198 - val_loss: 1.5648 - val_mae: 0.4716 - learning_rate: 5.0000e-04
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.3704 - mae: 0.1191 - val_loss: 1.4008 - val_mae: 0.4260 - learning_rate: 5.0000e-04
Epoch 11/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.3749 - mae: 0.1206 - val_loss: 1.2129 - val_mae: 0.3732 - learning_rate: 5.0000e-04
Epoch 12/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.3646 - mae: 0.1173 - val_loss: 1.4202 - val_mae: 0.4322 - learning_rate: 5.0000e-04
Epoch 13/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.3401 - mae: 0.1096 - val_loss: 1.2994 - val_mae: 0.3970 - learning_rate: 5.0000e-04
Epoch 14/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.3393 - mae: 0.1095 - val_loss: 1.1595 - val_mae: 0.3581 - learning_rate: 5.0000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.3344 - mae: 0.1078 - val_loss: 1.3827 - val_mae: 0.4211 - learning_rate: 5.0000e-04
Epoch 16/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.3289 - mae: 0.1062 - val_loss: 1.1680 - val_mae: 0.3598 - learning_rate: 5.0000e-04
Epoch 17/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.3065 - mae: 0.0992 - val_loss: 1.3048 - val_mae: 0.3990 - learning_rate: 5.0000e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.3161 - mae: 0.1022 - val_loss: 1.4711 - val_mae: 0.4474 - learning_rate: 5.0000e-04
Epoch 19/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.3231 - mae: 0.1044
Epoch 19: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.3232 - mae: 0.1045 - val_loss: 1.3650 - val_mae: 0.4171 - learning_rate: 5.0000e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - loss: 0.2919 - mae: 0.0945 - val_loss: 1.0872 - val_mae: 0.3362 - learning_rate: 2.5000e-04
Epoch 21/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.2897 - mae: 0.0939 - val_loss: 1.0672 - val_mae: 0.3303 - learning_rate: 2.5000e-04
Epoch 22/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.2875 - mae: 0.0932 - val_loss: 1.0671 - val_mae: 0.3302 - learning_rate: 2.5000e-04
Epoch 23/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.2890 - mae: 0.0937 - val_loss: 1.1603 - val_mae: 0.3577 - learning_rate: 2.5000e-04
Epoch 24/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.2753 - mae: 0.0894 - val_loss: 1.0843 - val_mae: 0.3350 - learning_rate: 2.5000e-04
Epoch 25/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - loss: 0.2683 - mae: 0.0872 - val_loss: 1.0640 - val_mae: 0.3295 - learning_rate: 2.5000e-04
Epoch 26/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.2655 - mae: 0.0862 - val_loss: 1.3259 - val_mae: 0.4046 - learning_rate: 2.5000e-04
Epoch 27/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.2645 - mae: 0.0859 - val_loss: 0.9172 - val_mae: 0.2860 - learning_rate: 2.5000e-04
Epoch 28/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.2824 - mae: 0.0916 - val_loss: 1.1494 - val_mae: 0.3542 - learning_rate: 2.5000e-04
Epoch 29/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.2554 - mae: 0.0830 - val_loss: 1.1568 - val_mae: 0.3560 - learning_rate: 2.5000e-04
Epoch 30/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - loss: 0.2541 - mae: 0.0827 - val_loss: 0.9670 - val_mae: 0.3006 - learning_rate: 2.5000e-04
Restoring model weights from the end of the best epoch: 27.
  {'Model': 'iTransformer', 'Horizon': 20, 'MAE': 12.0124, 'RMSE': 19.6481, 'RMSE($)': 19.6481, 'MAPE(%)': 11.9704, 'SMAPE(%)': 12.4992, 'R2': -0.191, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 5s 23ms/step - loss: 1.8564 - mae: 0.5391 - val_loss: 0.4641 - val_mae: 0.1486 - learning_rate: 0.0010
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.6206 - mae: 0.1956 - val_loss: 0.5626 - val_mae: 0.1783 - learning_rate: 0.0010
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.4567 - mae: 0.1458 - val_loss: 0.4586 - val_mae: 0.1467 - learning_rate: 0.0010
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.4285 - mae: 0.1371 - val_loss: 0.4387 - val_mae: 0.1404 - learning_rate: 0.0010
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.3890 - mae: 0.1248 - val_loss: 0.4459 - val_mae: 0.1430 - learning_rate: 0.0010
Epoch 6/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.3930 - mae: 0.1261 - val_loss: 0.5158 - val_mae: 0.1647 - learning_rate: 0.0010
Epoch 7/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.3447 - mae: 0.1109 - val_loss: 0.6577 - val_mae: 0.2093 - learning_rate: 0.0010
Epoch 8/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.3639 - mae: 0.1171 - val_loss: 0.5250 - val_mae: 0.1682 - learning_rate: 0.0010
Epoch 9/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.3340 - mae: 0.1076
Epoch 9: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.3343 - mae: 0.1077 - val_loss: 0.5124 - val_mae: 0.1642 - learning_rate: 0.0010
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.3298 - mae: 0.1064 - val_loss: 0.5227 - val_mae: 0.1672 - learning_rate: 5.0000e-04
Epoch 11/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.3047 - mae: 0.0985 - val_loss: 0.5209 - val_mae: 0.1667 - learning_rate: 5.0000e-04
Epoch 12/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.2968 - mae: 0.0961 - val_loss: 0.5150 - val_mae: 0.1648 - learning_rate: 5.0000e-04
Epoch 13/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.2970 - mae: 0.0961 - val_loss: 0.5715 - val_mae: 0.1826 - learning_rate: 5.0000e-04
Epoch 14/30
55/57 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2879 - mae: 0.0932
Epoch 14: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.2881 - mae: 0.0933 - val_loss: 0.5485 - val_mae: 0.1751 - learning_rate: 5.0000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2754 - mae: 0.0893 - val_loss: 0.5545 - val_mae: 0.1771 - learning_rate: 2.5000e-04
Epoch 16/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2803 - mae: 0.0909 - val_loss: 0.5402 - val_mae: 0.1725 - learning_rate: 2.5000e-04
Epoch 17/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2796 - mae: 0.0906 - val_loss: 0.5403 - val_mae: 0.1726 - learning_rate: 2.5000e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2586 - mae: 0.0839 - val_loss: 0.5732 - val_mae: 0.1829 - learning_rate: 2.5000e-04
Epoch 19/30
54/57 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.2730 - mae: 0.0885
Epoch 19: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2728 - mae: 0.0884 - val_loss: 0.5801 - val_mae: 0.1851 - learning_rate: 2.5000e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2676 - mae: 0.0867 - val_loss: 0.5862 - val_mae: 0.1870 - learning_rate: 1.2500e-04
Epoch 21/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2625 - mae: 0.0851 - val_loss: 0.5750 - val_mae: 0.1835 - learning_rate: 1.2500e-04
Epoch 22/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2591 - mae: 0.0841 - val_loss: 0.5771 - val_mae: 0.1841 - learning_rate: 1.2500e-04
Epoch 23/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2514 - mae: 0.0816 - val_loss: 0.5723 - val_mae: 0.1826 - learning_rate: 1.2500e-04
Epoch 24/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2538 - mae: 0.0824
Epoch 24: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2539 - mae: 0.0825 - val_loss: 0.5941 - val_mae: 0.1894 - learning_rate: 1.2500e-04
Epoch 24: early stopping
Restoring model weights from the end of the best epoch: 4.
  {'Model': 'GUMNet-Lite', 'Horizon': 20, 'MAE': 10.3704, 'RMSE': 19.0705, 'RMSE($)': 19.0705, 'MAPE(%)': 9.8575, 'SMAPE(%)': 11.0134, 'R2': -0.122, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 5s 25ms/step - loss: 1.0884 - mae: 0.3289 - val_loss: 0.4266 - val_mae: 0.1371 - learning_rate: 0.0010
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.4834 - mae: 0.1541 - val_loss: 0.4102 - val_mae: 0.1320 - learning_rate: 0.0010
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.4018 - mae: 0.1289 - val_loss: 0.4490 - val_mae: 0.1442 - learning_rate: 0.0010
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.3613 - mae: 0.1165 - val_loss: 0.4875 - val_mae: 0.1560 - learning_rate: 0.0010
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.3510 - mae: 0.1133 - val_loss: 0.5272 - val_mae: 0.1681 - learning_rate: 0.0010
Epoch 6/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.3308 - mae: 0.1070 - val_loss: 0.5516 - val_mae: 0.1754 - learning_rate: 0.0010
Epoch 7/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.3184 - mae: 0.1031
Epoch 7: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.3184 - mae: 0.1031 - val_loss: 0.6052 - val_mae: 0.1913 - learning_rate: 0.0010
Epoch 8/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2902 - mae: 0.0943 - val_loss: 0.4990 - val_mae: 0.1595 - learning_rate: 5.0000e-04
Epoch 9/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2793 - mae: 0.0907 - val_loss: 0.5650 - val_mae: 0.1796 - learning_rate: 5.0000e-04
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2735 - mae: 0.0889 - val_loss: 0.4915 - val_mae: 0.1572 - learning_rate: 5.0000e-04
Epoch 11/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2813 - mae: 0.0914 - val_loss: 0.5127 - val_mae: 0.1638 - learning_rate: 5.0000e-04
Epoch 12/30
55/57 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.2673 - mae: 0.0870
Epoch 12: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2674 - mae: 0.0870 - val_loss: 0.5190 - val_mae: 0.1657 - learning_rate: 5.0000e-04
Epoch 13/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2588 - mae: 0.0842 - val_loss: 0.5251 - val_mae: 0.1674 - learning_rate: 2.5000e-04
Epoch 14/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2375 - mae: 0.0774 - val_loss: 0.5406 - val_mae: 0.1722 - learning_rate: 2.5000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2393 - mae: 0.0780 - val_loss: 0.5363 - val_mae: 0.1710 - learning_rate: 2.5000e-04
Epoch 16/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2391 - mae: 0.0779 - val_loss: 0.5311 - val_mae: 0.1695 - learning_rate: 2.5000e-04
Epoch 17/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.2277 - mae: 0.0743
Epoch 17: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2277 - mae: 0.0743 - val_loss: 0.5340 - val_mae: 0.1704 - learning_rate: 2.5000e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2342 - mae: 0.0764 - val_loss: 0.5396 - val_mae: 0.1721 - learning_rate: 1.2500e-04
Epoch 19/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.2291 - mae: 0.0747 - val_loss: 0.5354 - val_mae: 0.1708 - learning_rate: 1.2500e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2188 - mae: 0.0714 - val_loss: 0.5360 - val_mae: 0.1709 - learning_rate: 1.2500e-04
Epoch 21/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2224 - mae: 0.0726 - val_loss: 0.5405 - val_mae: 0.1723 - learning_rate: 1.2500e-04
Epoch 22/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.2196 - mae: 0.0718
Epoch 22: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2197 - mae: 0.0718 - val_loss: 0.5353 - val_mae: 0.1707 - learning_rate: 1.2500e-04
Epoch 22: early stopping
Restoring model weights from the end of the best epoch: 2.

Seed set to 1

  {'Model': 'GUMNet-Ultra', 'Horizon': 20, 'MAE': 8.984, 'RMSE': 17.0031, 'RMSE($)': 17.0031, 'MAPE(%)': 8.7813, 'SMAPE(%)': 9.4322, 'R2': 0.1081, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  PatchTST/TFT skipped: Exception('PatchTST does not support historical exogenous variables.')
  [H=20] done in 246.4s
======================================================================
HORIZON H = 30
======================================================================
  {'Model': 'ARIMAX', 'Horizon': 30, 'MAE': 4.2465, 'RMSE': 7.0969, 'RMSE($)': 7.0969, 'MAPE(%)': 4.3669, 'SMAPE(%)': 4.2878, 'R2': 0.8517, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'SARIMA', 'Horizon': 30, 'MAE': 8.5796, 'RMSE': 18.1749, 'RMSE($)': 18.1749, 'MAPE(%)': 8.0477, 'SMAPE(%)': 8.8458, 'R2': 0.0272, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
H=30 OOF fold 1: 2018-03-02 -> 2020-04-22 | MAE=2.8853
H=30 OOF fold 2: 2020-04-23 -> 2022-06-09 | MAE=5.0934

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

H=30 OOF fold 3: 2022-06-10 -> 2024-07-29 | MAE=7.1638
H=30 Jump-Gated ARIMAX-CatBoost MAPE=4.9592% | MAE=4.9482
  {'Model': 'Jump-Gated ARIMAX-CatBoost', 'Horizon': 30, 'MAE': 4.9482, 'RMSE': 9.427, 'RMSE($)': 9.427, 'MAPE(%)': 4.9592, 'SMAPE(%)': 4.8323, 'R2': 0.7225, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'Ridge (Linear)', 'Horizon': 30, 'MAE': 10.2983, 'RMSE': 20.4803, 'RMSE($)': 20.4803, 'MAPE(%)': 9.8031, 'SMAPE(%)': 9.6579, 'R2': -0.3098, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LightGBM', 'Horizon': 30, 'MAE': 9.2668, 'RMSE': 17.1683, 'RMSE($)': 17.1683, 'MAPE(%)': 9.0095, 'SMAPE(%)': 9.5888, 'R2': 0.0796, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LSTM', 'Horizon': 30, 'MAE': 10.7871, 'RMSE': 19.8118, 'RMSE($)': 19.8118, 'MAPE(%)': 10.4328, 'SMAPE(%)': 11.1174, 'R2': -0.2083, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 54s 160ms/step - loss: 0.9603 - mae: 0.2929 - val_loss: 1.3587 - val_mae: 0.4139 - learning_rate: 5.0000e-04
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 61ms/step - loss: 0.6333 - mae: 0.1992 - val_loss: 1.6744 - val_mae: 0.5015 - learning_rate: 5.0000e-04
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 61ms/step - loss: 0.5894 - mae: 0.1860 - val_loss: 1.6070 - val_mae: 0.4828 - learning_rate: 5.0000e-04
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 67ms/step - loss: 0.5609 - mae: 0.1773 - val_loss: 1.7303 - val_mae: 0.5164 - learning_rate: 5.0000e-04
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 68ms/step - loss: 0.5334 - mae: 0.1689 - val_loss: 1.4533 - val_mae: 0.4398 - learning_rate: 5.0000e-04
Epoch 6/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.5090 - mae: 0.1615
Epoch 6: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 73ms/step - loss: 0.5090 - mae: 0.1615 - val_loss: 1.5317 - val_mae: 0.4633 - learning_rate: 5.0000e-04
Epoch 7/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 74ms/step - loss: 0.4821 - mae: 0.1531 - val_loss: 1.3643 - val_mae: 0.4155 - learning_rate: 2.5000e-04
Epoch 8/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 61ms/step - loss: 0.4589 - mae: 0.1458 - val_loss: 1.4995 - val_mae: 0.4544 - learning_rate: 2.5000e-04
Epoch 9/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 70ms/step - loss: 0.4439 - mae: 0.1413 - val_loss: 1.4527 - val_mae: 0.4412 - learning_rate: 2.5000e-04
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 71ms/step - loss: 0.4387 - mae: 0.1399 - val_loss: 1.2794 - val_mae: 0.3920 - learning_rate: 2.5000e-04
Epoch 11/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 73ms/step - loss: 0.4439 - mae: 0.1412 - val_loss: 1.4071 - val_mae: 0.4285 - learning_rate: 2.5000e-04
Epoch 12/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 69ms/step - loss: 0.4194 - mae: 0.1336 - val_loss: 1.3124 - val_mae: 0.4009 - learning_rate: 2.5000e-04
Epoch 13/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 73ms/step - loss: 0.4189 - mae: 0.1338 - val_loss: 1.3660 - val_mae: 0.4167 - learning_rate: 2.5000e-04
Epoch 14/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 5s 73ms/step - loss: 0.4031 - mae: 0.1287 - val_loss: 1.2938 - val_mae: 0.3965 - learning_rate: 2.5000e-04
Epoch 15/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.4008 - mae: 0.1281
Epoch 15: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - loss: 0.4010 - mae: 0.1281 - val_loss: 1.3097 - val_mae: 0.4008 - learning_rate: 2.5000e-04
Epoch 16/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.3969 - mae: 0.1269 - val_loss: 1.3937 - val_mae: 0.4257 - learning_rate: 1.2500e-04
Epoch 17/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - loss: 0.3808 - mae: 0.1217 - val_loss: 1.5014 - val_mae: 0.4557 - learning_rate: 1.2500e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - loss: 0.3793 - mae: 0.1215 - val_loss: 1.5354 - val_mae: 0.4655 - learning_rate: 1.2500e-04
Epoch 19/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.3778 - mae: 0.1211 - val_loss: 1.4711 - val_mae: 0.4475 - learning_rate: 1.2500e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.3818 - mae: 0.1221
Epoch 20: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - loss: 0.3817 - mae: 0.1221 - val_loss: 1.5771 - val_mae: 0.4769 - learning_rate: 1.2500e-04
Epoch 21/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.3739 - mae: 0.1198 - val_loss: 1.3984 - val_mae: 0.4270 - learning_rate: 6.2500e-05
Epoch 22/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - loss: 0.3596 - mae: 0.1153 - val_loss: 1.3877 - val_mae: 0.4241 - learning_rate: 6.2500e-05
Epoch 23/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - loss: 0.3651 - mae: 0.1170 - val_loss: 1.3700 - val_mae: 0.4191 - learning_rate: 6.2500e-05
Epoch 24/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.3682 - mae: 0.1179 - val_loss: 1.4685 - val_mae: 0.4467 - learning_rate: 6.2500e-05
Epoch 25/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.3554 - mae: 0.1141
Epoch 25: ReduceLROnPlateau reducing learning rate to 3.125000148429535e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - loss: 0.3553 - mae: 0.1140 - val_loss: 1.3765 - val_mae: 0.4208 - learning_rate: 6.2500e-05
Epoch 26/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - loss: 0.3474 - mae: 0.1116 - val_loss: 1.4146 - val_mae: 0.4316 - learning_rate: 3.1250e-05
Epoch 27/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.3488 - mae: 0.1120 - val_loss: 1.3967 - val_mae: 0.4265 - learning_rate: 3.1250e-05
Epoch 28/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - loss: 0.3464 - mae: 0.1112 - val_loss: 1.4434 - val_mae: 0.4396 - learning_rate: 3.1250e-05
Epoch 29/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.3546 - mae: 0.1138 - val_loss: 1.4080 - val_mae: 0.4297 - learning_rate: 3.1250e-05
Epoch 30/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.3485 - mae: 0.1119
Epoch 30: ReduceLROnPlateau reducing learning rate to 1.5625000742147677e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.3485 - mae: 0.1119 - val_loss: 1.4067 - val_mae: 0.4292 - learning_rate: 3.1250e-05
Epoch 30: early stopping
Restoring model weights from the end of the best epoch: 10.
  {'Model': 'iTransformer', 'Horizon': 30, 'MAE': 15.0476, 'RMSE': 22.7348, 'RMSE($)': 22.7348, 'MAPE(%)': 15.4732, 'SMAPE(%)': 15.827, 'R2': -0.5911, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 7s 30ms/step - loss: 1.9068 - mae: 0.5511 - val_loss: 0.6156 - val_mae: 0.1949 - learning_rate: 0.0010
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.6232 - mae: 0.1958 - val_loss: 0.5632 - val_mae: 0.1785 - learning_rate: 0.0010
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.4899 - mae: 0.1558 - val_loss: 0.5807 - val_mae: 0.1841 - learning_rate: 0.0010
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.4438 - mae: 0.1417 - val_loss: 0.5272 - val_mae: 0.1683 - learning_rate: 0.0010
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.4217 - mae: 0.1349 - val_loss: 0.5358 - val_mae: 0.1701 - learning_rate: 0.0010
Epoch 6/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.4041 - mae: 0.1295 - val_loss: 0.5768 - val_mae: 0.1830 - learning_rate: 0.0010
Epoch 7/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.3764 - mae: 0.1210 - val_loss: 0.5700 - val_mae: 0.1809 - learning_rate: 0.0010
Epoch 8/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.3679 - mae: 0.1183 - val_loss: 0.5530 - val_mae: 0.1758 - learning_rate: 0.0010
Epoch 9/30
55/57 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.3660 - mae: 0.1175
Epoch 9: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.3660 - mae: 0.1175 - val_loss: 0.5939 - val_mae: 0.1882 - learning_rate: 0.0010
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.3511 - mae: 0.1129 - val_loss: 0.5276 - val_mae: 0.1680 - learning_rate: 5.0000e-04
Epoch 11/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.3241 - mae: 0.1044 - val_loss: 0.5479 - val_mae: 0.1742 - learning_rate: 5.0000e-04
Epoch 12/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.3155 - mae: 0.1018 - val_loss: 0.5808 - val_mae: 0.1845 - learning_rate: 5.0000e-04
Epoch 13/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.3118 - mae: 0.1006 - val_loss: 0.5846 - val_mae: 0.1861 - learning_rate: 5.0000e-04
Epoch 14/30
55/57 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.3028 - mae: 0.0978
Epoch 14: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.3031 - mae: 0.0980 - val_loss: 0.6269 - val_mae: 0.1990 - learning_rate: 5.0000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.3000 - mae: 0.0970 - val_loss: 0.6003 - val_mae: 0.1907 - learning_rate: 2.5000e-04
Epoch 16/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2882 - mae: 0.0932 - val_loss: 0.5989 - val_mae: 0.1902 - learning_rate: 2.5000e-04
Epoch 17/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.2850 - mae: 0.0921 - val_loss: 0.6320 - val_mae: 0.2001 - learning_rate: 2.5000e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2899 - mae: 0.0937 - val_loss: 0.5769 - val_mae: 0.1834 - learning_rate: 2.5000e-04
Epoch 19/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.2911 - mae: 0.0941
Epoch 19: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2912 - mae: 0.0941 - val_loss: 0.5872 - val_mae: 0.1865 - learning_rate: 2.5000e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.2811 - mae: 0.0908 - val_loss: 0.5931 - val_mae: 0.1883 - learning_rate: 1.2500e-04
Epoch 21/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.2812 - mae: 0.0908 - val_loss: 0.6069 - val_mae: 0.1925 - learning_rate: 1.2500e-04
Epoch 22/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.2857 - mae: 0.0923 - val_loss: 0.6081 - val_mae: 0.1929 - learning_rate: 1.2500e-04
Epoch 23/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.2676 - mae: 0.0866 - val_loss: 0.5970 - val_mae: 0.1895 - learning_rate: 1.2500e-04
Epoch 24/30
55/57 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.2720 - mae: 0.0881
Epoch 24: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2723 - mae: 0.0882 - val_loss: 0.6292 - val_mae: 0.1993 - learning_rate: 1.2500e-04
Epoch 24: early stopping
Restoring model weights from the end of the best epoch: 4.
  {'Model': 'GUMNet-Lite', 'Horizon': 30, 'MAE': 10.8521, 'RMSE': 22.0131, 'RMSE($)': 22.0131, 'MAPE(%)': 9.9826, 'SMAPE(%)': 11.489, 'R2': -0.4917, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 5s 26ms/step - loss: 1.1440 - mae: 0.3443 - val_loss: 0.5537 - val_mae: 0.1766 - learning_rate: 0.0010
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.5109 - mae: 0.1623 - val_loss: 0.4743 - val_mae: 0.1520 - learning_rate: 0.0010
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.4387 - mae: 0.1403 - val_loss: 0.4893 - val_mae: 0.1564 - learning_rate: 0.0010
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.3965 - mae: 0.1271 - val_loss: 0.5571 - val_mae: 0.1775 - learning_rate: 0.0010
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.3774 - mae: 0.1212 - val_loss: 0.5091 - val_mae: 0.1627 - learning_rate: 0.0010
Epoch 6/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.3637 - mae: 0.1170 - val_loss: 0.6218 - val_mae: 0.1973 - learning_rate: 0.0010
Epoch 7/30
55/57 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.3323 - mae: 0.1072
Epoch 7: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.3325 - mae: 0.1072 - val_loss: 0.6126 - val_mae: 0.1939 - learning_rate: 0.0010
Epoch 8/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.3131 - mae: 0.1013 - val_loss: 0.6143 - val_mae: 0.1951 - learning_rate: 5.0000e-04
Epoch 9/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2781 - mae: 0.0903 - val_loss: 0.6002 - val_mae: 0.1909 - learning_rate: 5.0000e-04
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2872 - mae: 0.0933 - val_loss: 0.5968 - val_mae: 0.1898 - learning_rate: 5.0000e-04
Epoch 11/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2759 - mae: 0.0896 - val_loss: 0.6480 - val_mae: 0.2055 - learning_rate: 5.0000e-04
Epoch 12/30
55/57 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.2753 - mae: 0.0894
Epoch 12: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2753 - mae: 0.0894 - val_loss: 0.6081 - val_mae: 0.1933 - learning_rate: 5.0000e-04
Epoch 13/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2665 - mae: 0.0867 - val_loss: 0.6268 - val_mae: 0.1991 - learning_rate: 2.5000e-04
Epoch 14/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2622 - mae: 0.0854 - val_loss: 0.6332 - val_mae: 0.2010 - learning_rate: 2.5000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2515 - mae: 0.0818 - val_loss: 0.6108 - val_mae: 0.1942 - learning_rate: 2.5000e-04
Epoch 16/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2502 - mae: 0.0814 - val_loss: 0.6167 - val_mae: 0.1960 - learning_rate: 2.5000e-04
Epoch 17/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.2445 - mae: 0.0796
Epoch 17: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2443 - mae: 0.0796 - val_loss: 0.6436 - val_mae: 0.2043 - learning_rate: 2.5000e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2326 - mae: 0.0758 - val_loss: 0.6444 - val_mae: 0.2045 - learning_rate: 1.2500e-04
Epoch 19/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2331 - mae: 0.0759 - val_loss: 0.6475 - val_mae: 0.2054 - learning_rate: 1.2500e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2283 - mae: 0.0745 - val_loss: 0.6466 - val_mae: 0.2051 - learning_rate: 1.2500e-04
Epoch 21/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2284 - mae: 0.0745 - val_loss: 0.6414 - val_mae: 0.2036 - learning_rate: 1.2500e-04
Epoch 22/30
54/57 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2371 - mae: 0.0772
Epoch 22: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2367 - mae: 0.0771 - val_loss: 0.6381 - val_mae: 0.2025 - learning_rate: 1.2500e-04
Epoch 22: early stopping
Restoring model weights from the end of the best epoch: 2.

Seed set to 1

  {'Model': 'GUMNet-Ultra', 'Horizon': 30, 'MAE': 11.1782, 'RMSE': 19.2034, 'RMSE($)': 19.2034, 'MAPE(%)': 11.0063, 'SMAPE(%)': 11.8027, 'R2': -0.1352, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  PatchTST/TFT skipped: Exception('PatchTST does not support historical exogenous variables.')
  [H=30] done in 337.9s
======================================================================
HORIZON H = 60
======================================================================
  {'Model': 'ARIMAX', 'Horizon': 60, 'MAE': 3.8244, 'RMSE': 5.266, 'RMSE($)': 5.266, 'MAPE(%)': 4.2186, 'SMAPE(%)': 4.1709, 'R2': 0.9237, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'SARIMA', 'Horizon': 60, 'MAE': 10.9924, 'RMSE': 22.4086, 'RMSE($)': 22.4086, 'MAPE(%)': 9.9718, 'SMAPE(%)': 11.3846, 'R2': -0.382, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

H=60 OOF fold 1: 2018-03-22 -> 2020-05-07 | MAE=4.0287
H=60 OOF fold 2: 2020-05-08 -> 2022-06-20 | MAE=7.1760

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

H=60 OOF fold 3: 2022-06-21 -> 2024-08-01 | MAE=7.3316
H=60 Jump-Gated ARIMAX-CatBoost MAPE=5.7799% | MAE=5.1450
  {'Model': 'Jump-Gated ARIMAX-CatBoost', 'Horizon': 60, 'MAE': 5.145, 'RMSE': 6.1706, 'RMSE($)': 6.1706, 'MAPE(%)': 5.7799, 'SMAPE(%)': 5.8271, 'R2': 0.8818, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'Ridge (Linear)', 'Horizon': 60, 'MAE': 9.4396, 'RMSE': 18.189, 'RMSE($)': 18.189, 'MAPE(%)': 8.8327, 'SMAPE(%)': 9.8017, 'R2': -0.0272, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LightGBM', 'Horizon': 60, 'MAE': 12.4454, 'RMSE': 20.4288, 'RMSE($)': 20.4288, 'MAPE(%)': 12.5123, 'SMAPE(%)': 13.1065, 'R2': -0.2958, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LSTM', 'Horizon': 60, 'MAE': 15.4875, 'RMSE': 27.637, 'RMSE($)': 27.637, 'MAPE(%)': 14.7858, 'SMAPE(%)': 17.9182, 'R2': -1.3213, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 20s 60ms/step - loss: 1.1012 - mae: 0.3314 - val_loss: 1.6704 - val_mae: 0.5018 - learning_rate: 5.0000e-04
Epoch 2/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.7002 - mae: 0.2188 - val_loss: 1.5273 - val_mae: 0.4626 - learning_rate: 5.0000e-04
Epoch 3/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.6670 - mae: 0.2090 - val_loss: 1.3969 - val_mae: 0.4266 - learning_rate: 5.0000e-04
Epoch 4/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - loss: 0.6344 - mae: 0.1991 - val_loss: 1.7035 - val_mae: 0.5106 - learning_rate: 5.0000e-04
Epoch 5/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 4s 63ms/step - loss: 0.5907 - mae: 0.1856 - val_loss: 1.4482 - val_mae: 0.4409 - learning_rate: 5.0000e-04
Epoch 6/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 5s 63ms/step - loss: 0.5566 - mae: 0.1755 - val_loss: 1.4938 - val_mae: 0.4546 - learning_rate: 5.0000e-04
Epoch 7/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 5s 64ms/step - loss: 0.5258 - mae: 0.1660 - val_loss: 1.4002 - val_mae: 0.4269 - learning_rate: 5.0000e-04
Epoch 8/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.5056 - mae: 0.1601
Epoch 8: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - loss: 0.5055 - mae: 0.1601 - val_loss: 1.5677 - val_mae: 0.4760 - learning_rate: 5.0000e-04
Epoch 9/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 57ms/step - loss: 0.4506 - mae: 0.1433 - val_loss: 1.2968 - val_mae: 0.3966 - learning_rate: 2.5000e-04
Epoch 10/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - loss: 0.4426 - mae: 0.1410 - val_loss: 1.3462 - val_mae: 0.4102 - learning_rate: 2.5000e-04
Epoch 11/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - loss: 0.4178 - mae: 0.1331 - val_loss: 1.3076 - val_mae: 0.4003 - learning_rate: 2.5000e-04
Epoch 12/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - loss: 0.4022 - mae: 0.1285 - val_loss: 1.4570 - val_mae: 0.4433 - learning_rate: 2.5000e-04
Epoch 13/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - loss: 0.3896 - mae: 0.1245 - val_loss: 1.2085 - val_mae: 0.3712 - learning_rate: 2.5000e-04
Epoch 14/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - loss: 0.3860 - mae: 0.1236 - val_loss: 1.3310 - val_mae: 0.4058 - learning_rate: 2.5000e-04
Epoch 15/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - loss: 0.3702 - mae: 0.1186 - val_loss: 1.3825 - val_mae: 0.4209 - learning_rate: 2.5000e-04
Epoch 16/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.3583 - mae: 0.1149 - val_loss: 1.1487 - val_mae: 0.3518 - learning_rate: 2.5000e-04
Epoch 17/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.3597 - mae: 0.1154 - val_loss: 1.2071 - val_mae: 0.3681 - learning_rate: 2.5000e-04
Epoch 18/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.3521 - mae: 0.1131 - val_loss: 1.1901 - val_mae: 0.3633 - learning_rate: 2.5000e-04
Epoch 19/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - loss: 0.3359 - mae: 0.1080 - val_loss: 1.1869 - val_mae: 0.3632 - learning_rate: 2.5000e-04
Epoch 20/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - loss: 0.3232 - mae: 0.1040 - val_loss: 1.4276 - val_mae: 0.4322 - learning_rate: 2.5000e-04
Epoch 21/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - loss: 0.3231 - mae: 0.1040 - val_loss: 1.0746 - val_mae: 0.3289 - learning_rate: 2.5000e-04
Epoch 22/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - loss: 0.3325 - mae: 0.1068 - val_loss: 1.1113 - val_mae: 0.3388 - learning_rate: 2.5000e-04
Epoch 23/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - loss: 0.3050 - mae: 0.0982 - val_loss: 1.0102 - val_mae: 0.3103 - learning_rate: 2.5000e-04
Epoch 24/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - loss: 0.3013 - mae: 0.0972 - val_loss: 1.1322 - val_mae: 0.3456 - learning_rate: 2.5000e-04
Epoch 25/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - loss: 0.3026 - mae: 0.0975 - val_loss: 1.0863 - val_mae: 0.3315 - learning_rate: 2.5000e-04
Epoch 26/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.3012 - mae: 0.0972 - val_loss: 1.0853 - val_mae: 0.3319 - learning_rate: 2.5000e-04
Epoch 27/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2973 - mae: 0.0960 - val_loss: 1.1614 - val_mae: 0.3547 - learning_rate: 2.5000e-04
Epoch 28/30
55/56 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.2761 - mae: 0.0892
Epoch 28: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2762 - mae: 0.0892 - val_loss: 1.3316 - val_mae: 0.4037 - learning_rate: 2.5000e-04
Epoch 29/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.2719 - mae: 0.0879 - val_loss: 1.1269 - val_mae: 0.3451 - learning_rate: 1.2500e-04
Epoch 30/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.2678 - mae: 0.0866 - val_loss: 1.2031 - val_mae: 0.3658 - learning_rate: 1.2500e-04
Restoring model weights from the end of the best epoch: 23.
  {'Model': 'iTransformer', 'Horizon': 60, 'MAE': 16.0737, 'RMSE': 27.3623, 'RMSE($)': 27.3623, 'MAPE(%)': 15.7833, 'SMAPE(%)': 17.2676, 'R2': -1.2754, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - loss: 1.9605 - mae: 0.5665 - val_loss: 1.0019 - val_mae: 0.3132 - learning_rate: 0.0010
Epoch 2/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.6180 - mae: 0.1945 - val_loss: 0.5726 - val_mae: 0.1821 - learning_rate: 0.0010
Epoch 3/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.5016 - mae: 0.1596 - val_loss: 0.6752 - val_mae: 0.2134 - learning_rate: 0.0010
Epoch 4/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.4214 - mae: 0.1349 - val_loss: 0.6903 - val_mae: 0.2181 - learning_rate: 0.0010
Epoch 5/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.3963 - mae: 0.1270 - val_loss: 0.8656 - val_mae: 0.2713 - learning_rate: 0.0010
Epoch 6/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.3795 - mae: 0.1219 - val_loss: 0.8785 - val_mae: 0.2746 - learning_rate: 0.0010
Epoch 7/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.3602 - mae: 0.1159
Epoch 7: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.3603 - mae: 0.1159 - val_loss: 0.7747 - val_mae: 0.2438 - learning_rate: 0.0010
Epoch 8/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.3465 - mae: 0.1117 - val_loss: 0.8039 - val_mae: 0.2531 - learning_rate: 5.0000e-04
Epoch 9/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.3224 - mae: 0.1041 - val_loss: 0.9136 - val_mae: 0.2857 - learning_rate: 5.0000e-04
Epoch 10/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.3280 - mae: 0.1058 - val_loss: 0.7986 - val_mae: 0.2512 - learning_rate: 5.0000e-04
Epoch 11/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.3200 - mae: 0.1033 - val_loss: 0.8655 - val_mae: 0.2714 - learning_rate: 5.0000e-04
Epoch 12/30
55/56 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.3085 - mae: 0.0997
Epoch 12: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.3086 - mae: 0.0998 - val_loss: 0.8276 - val_mae: 0.2602 - learning_rate: 5.0000e-04
Epoch 13/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.3088 - mae: 0.0998 - val_loss: 0.8843 - val_mae: 0.2774 - learning_rate: 2.5000e-04
Epoch 14/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.3076 - mae: 0.0992 - val_loss: 0.8880 - val_mae: 0.2784 - learning_rate: 2.5000e-04
Epoch 15/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.2908 - mae: 0.0941 - val_loss: 0.8218 - val_mae: 0.2588 - learning_rate: 2.5000e-04
Epoch 16/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.2894 - mae: 0.0936 - val_loss: 0.8781 - val_mae: 0.2757 - learning_rate: 2.5000e-04
Epoch 17/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.2910 - mae: 0.0941
Epoch 17: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.2911 - mae: 0.0942 - val_loss: 0.8513 - val_mae: 0.2675 - learning_rate: 2.5000e-04
Epoch 18/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.2937 - mae: 0.0950 - val_loss: 0.8032 - val_mae: 0.2531 - learning_rate: 1.2500e-04
Epoch 19/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.2947 - mae: 0.0953 - val_loss: 0.8336 - val_mae: 0.2622 - learning_rate: 1.2500e-04
Epoch 20/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.2840 - mae: 0.0919 - val_loss: 0.8291 - val_mae: 0.2608 - learning_rate: 1.2500e-04
Epoch 21/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.2732 - mae: 0.0885 - val_loss: 0.8035 - val_mae: 0.2530 - learning_rate: 1.2500e-04
Epoch 22/30
55/56 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2791 - mae: 0.0904
Epoch 22: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.2793 - mae: 0.0904 - val_loss: 0.8549 - val_mae: 0.2686 - learning_rate: 1.2500e-04
Epoch 22: early stopping
Restoring model weights from the end of the best epoch: 2.
  {'Model': 'GUMNet-Lite', 'Horizon': 60, 'MAE': 14.3895, 'RMSE': 26.7456, 'RMSE($)': 26.7456, 'MAPE(%)': 13.5191, 'SMAPE(%)': 16.3188, 'R2': -1.174, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 8s 46ms/step - loss: 1.2498 - mae: 0.3737 - val_loss: 0.4992 - val_mae: 0.1597 - learning_rate: 0.0010
Epoch 2/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 0.5717 - mae: 0.1800 - val_loss: 0.5682 - val_mae: 0.1810 - learning_rate: 0.0010
Epoch 3/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.4849 - mae: 0.1539 - val_loss: 0.5864 - val_mae: 0.1867 - learning_rate: 0.0010
Epoch 4/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.4326 - mae: 0.1378 - val_loss: 0.6614 - val_mae: 0.2091 - learning_rate: 0.0010
Epoch 5/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.4100 - mae: 0.1312 - val_loss: 0.6264 - val_mae: 0.1986 - learning_rate: 0.0010
Epoch 6/30
55/56 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.3661 - mae: 0.1177
Epoch 6: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.3660 - mae: 0.1177 - val_loss: 0.6664 - val_mae: 0.2106 - learning_rate: 0.0010
Epoch 7/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.3343 - mae: 0.1077 - val_loss: 0.6525 - val_mae: 0.2064 - learning_rate: 5.0000e-04
Epoch 8/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.3079 - mae: 0.0998 - val_loss: 0.6565 - val_mae: 0.2074 - learning_rate: 5.0000e-04
Epoch 9/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.3068 - mae: 0.0995 - val_loss: 0.6165 - val_mae: 0.1956 - learning_rate: 5.0000e-04
Epoch 10/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.3087 - mae: 0.0999 - val_loss: 0.6557 - val_mae: 0.2073 - learning_rate: 5.0000e-04
Epoch 11/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.3044 - mae: 0.0987
Epoch 11: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.3045 - mae: 0.0987 - val_loss: 0.6784 - val_mae: 0.2138 - learning_rate: 5.0000e-04
Epoch 12/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.2832 - mae: 0.0920 - val_loss: 0.6637 - val_mae: 0.2099 - learning_rate: 2.5000e-04
Epoch 13/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step - loss: 0.2485 - mae: 0.0809 - val_loss: 0.6657 - val_mae: 0.2106 - learning_rate: 2.5000e-04
Epoch 14/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - loss: 0.2498 - mae: 0.0814 - val_loss: 0.6431 - val_mae: 0.2037 - learning_rate: 2.5000e-04
Epoch 15/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step - loss: 0.2623 - mae: 0.0852 - val_loss: 0.6402 - val_mae: 0.2030 - learning_rate: 2.5000e-04
Epoch 16/30
55/56 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.2549 - mae: 0.0829
Epoch 16: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.2549 - mae: 0.0829 - val_loss: 0.6295 - val_mae: 0.1996 - learning_rate: 2.5000e-04
Epoch 17/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.2377 - mae: 0.0775 - val_loss: 0.6307 - val_mae: 0.2001 - learning_rate: 1.2500e-04
Epoch 18/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2410 - mae: 0.0785 - val_loss: 0.6385 - val_mae: 0.2023 - learning_rate: 1.2500e-04
Epoch 19/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - loss: 0.2419 - mae: 0.0788 - val_loss: 0.6327 - val_mae: 0.2006 - learning_rate: 1.2500e-04
Epoch 20/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 53ms/step - loss: 0.2332 - mae: 0.0761 - val_loss: 0.6490 - val_mae: 0.2057 - learning_rate: 1.2500e-04
Epoch 21/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.2313 - mae: 0.0754
Epoch 21: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 53ms/step - loss: 0.2313 - mae: 0.0754 - val_loss: 0.6489 - val_mae: 0.2056 - learning_rate: 1.2500e-04
Epoch 21: early stopping
Restoring model weights from the end of the best epoch: 1.
  {'Model': 'GUMNet-Ultra', 'Horizon': 60, 'MAE': 11.4503, 'RMSE': 21.2237, 'RMSE($)': 21.2237, 'MAPE(%)': 10.8524, 'SMAPE(%)': 12.0994, 'R2': -0.369, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}

Seed set to 1

  PatchTST/TFT skipped: Exception('PatchTST does not support historical exogenous variables.')
  [H=60] done in 378.8s

ALL HORIZONS DONE. rows: 63

## 8. Ket qua - bang + signal decay theo horizon

In [9]:
res_df = pd.DataFrame(results)
res_df.insert(0, "Target", TARGET)
target_csv = TARGET_RESULT_DIR / "multihorizon_results_10.csv"
res_df.to_csv(target_csv, index=False)

combined_path = ROOT / "results" / DATA_TAG / "multihorizon_results_all_targets_10.csv"
if combined_path.exists():
    previous_rows = pd.read_csv(combined_path)
    previous_rows = previous_rows[previous_rows["Target"] != TARGET]
    combined_rows = pd.concat([previous_rows, res_df], ignore_index=True)
else:
    combined_rows = res_df.copy()
combined_rows.to_csv(combined_path, index=False)

if TARGET == "MG95":
    res_df.drop(columns=["Target"]).to_csv(ROOT / "results" / DATA_TAG / "multihorizon_results_1095.csv", index=False)

print("=== Full results (long) ===")
display(res_df)

# Pivot: metrics theo (Model x Horizon)
for met in ["R2", "MAPE(%)", "MAE", "RMSE", "RMSE($)", "SMAPE(%)"]:
    piv = res_df.pivot_table(index="Model", columns="Horizon", values=met)
    print(f"\n--- {met} (Model x Horizon) ---"); display(piv)

# --- Quality-standard check: MAPE<3% (H1-5), MAPE<5% (H10-20), RMSE($)<2 ---
qa = res_df[["Model", "Horizon", "MAPE(%)", "MAPE_thr(%)", "RMSE($)", "RMSE_thr($)", "Pass"]].copy()
print("\n=== Quality check vs standard (MAPE<3% H1-5 | MAPE<5% H10-20 | RMSE($)<2) ===")
display(qa)
pass_piv = res_df.pivot_table(index="Model", columns="Horizon", values="Pass", aggfunc="first")
print("\n--- Pass (Model x Horizon) ---"); display(pass_piv)
print(f"Models meeting standard: {int(res_df['Pass'].sum())}/{len(res_df)}")

print(f"Saved -> {target_csv}")
print(f"Updated -> {combined_path}")

=== Full results (long) ===

,Target,Model,Horizon,MAE,RMSE,RMSE($),MAPE(%),SMAPE(%),R2,MAPE_thr(%),RMSE_thr($),Pass
0,MG95,ARIMAX,1,0.9752,2.1116,2.1116,0.9796,0.9759,0.9860,3.0,2.0,False
1,MG95,SARIMA,1,1.5108,3.0496,3.0496,1.5540,1.5528,0.9709,3.0,2.0,False
2,MG95,Jump-Gated ARIMAX-CatBoost,1,1.0799,2.7229,2.7229,1.0457,1.0432,0.9767,3.0,2.0,False
3,MG95,Ridge (Linear),1,1.4194,2.8282,2.8282,1.4162,1.4252,0.9749,3.0,2.0,False
4,MG95,LightGBM,1,1.9689,3.6704,3.6704,2.0071,2.0372,0.9577,3.0,2.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...
58,MG95,LightGBM,60,12.4454,20.4288,20.4288,12.5123,13.1065,-0.2958,NaN,2.0,False
59,MG95,LSTM,60,15.4875,27.6370,27.6370,14.7858,17.9182,-1.3213,NaN,2.0,False
60,MG95,iTransformer,60,16.0737,27.3623,27.3623,15.7833,17.2676,-1.2754,NaN,2.0,False
61,MG95,GUMNet-Lite,60,14.3895,26.7456,26.7456,13.5191,16.3188,-1.1740,NaN,2.0,False
62,MG95,GUMNet-Ultra,60,11.4503,21.2237,21.2237,10.8524,12.0994,-0.3690,NaN,2.0,False

--- R2 (Model x Horizon) ---

Horizon,1,5,10,15,20,30,60
Model,,,,,,,
ARIMAX,0.9860,0.9478,0.9214,0.8870,0.8624,0.8517,0.9237
GUMNet-Lite,0.7034,0.6640,0.3483,-0.0219,-0.1220,-0.4917,-1.1740
GUMNet-Ultra,0.8001,0.6144,0.4826,0.3359,0.1081,-0.1352,-0.3690
Jump-Gated ARIMAX-CatBoost,0.9767,0.9470,0.9141,0.8402,0.7633,0.7225,0.8818
LSTM,0.8056,0.5038,0.4029,0.1859,0.0755,-0.2083,-1.3213
LightGBM,0.9577,0.8607,0.4216,0.4736,0.1819,0.0796,-0.2958
Ridge (Linear),0.9749,0.9013,0.6976,0.3701,0.0137,-0.3098,-0.0272
SARIMA,0.9709,0.8518,0.6771,0.4644,0.2847,0.0272,-0.3820
iTransformer,0.6030,0.4484,0.1352,0.1163,-0.1910,-0.5911,-1.2754

--- MAPE(%) (Model x Horizon) ---

Horizon,1,5,10,15,20,30,60
Model,,,,,,,
ARIMAX,0.9796,2.2370,2.8368,3.4864,3.8622,4.3669,4.2186
GUMNet-Lite,5.4322,7.3572,8.8074,9.2869,9.8575,9.9826,13.5191
GUMNet-Ultra,5.5281,5.0157,7.4027,7.7827,8.7813,11.0063,10.8524
Jump-Gated ARIMAX-CatBoost,1.0457,2.2386,2.9025,3.7851,4.3419,4.9592,5.7799
LSTM,5.4919,6.2358,6.9301,7.4945,8.0355,10.4328,14.7858
LightGBM,2.0071,3.8518,6.7443,5.5677,8.6723,9.0095,12.5123
Ridge (Linear),1.4162,3.3541,4.8589,6.6103,8.0920,9.8031,8.8327
SARIMA,1.5540,3.8635,4.8296,5.7751,6.8330,8.0477,9.9718
iTransformer,4.7147,5.8013,8.3307,9.8041,11.9704,15.4732,15.7833

--- MAE (Model x Horizon) ---

Horizon,1,5,10,15,20,30,60
Model,,,,,,,
ARIMAX,0.9752,2.2064,2.7976,3.4452,3.7859,4.2465,3.8244
GUMNet-Lite,5.4403,6.9016,8.6404,9.5350,10.3704,10.8521,14.3895
GUMNet-Ultra,5.2082,5.1314,7.3008,7.9173,8.9840,11.1782,11.4503
Jump-Gated ARIMAX-CatBoost,1.0799,2.2081,2.8709,3.8155,4.3955,4.9482,5.1450
LSTM,5.1022,6.3809,7.1767,7.9870,8.5956,10.7871,15.4875
LightGBM,1.9689,3.7299,6.9878,5.8184,8.8210,9.2668,12.4454
Ridge (Linear),1.4194,3.2210,4.9014,6.9117,8.5732,10.2983,9.4396
SARIMA,1.5108,3.7698,4.8785,5.9890,7.1636,8.5796,10.9924
iTransformer,5.1525,6.2496,8.8148,9.9165,12.0124,15.0476,16.0737

--- RMSE (Model x Horizon) ---

Horizon,1,5,10,15,20,30,60
Model,,,,,,,
ARIMAX,2.1116,4.0957,5.0518,6.0917,6.7586,7.0969,5.2660
GUMNet-Lite,9.7460,10.3825,14.4880,18.1597,19.0705,22.0131,26.7456
GUMNet-Ultra,8.0017,11.1225,12.9087,14.6400,17.0031,19.2034,21.2237
Jump-Gated ARIMAX-CatBoost,2.7229,4.1143,5.2355,7.1464,8.6984,9.4270,6.1706
LSTM,7.8893,12.6172,13.8675,16.2082,17.3112,19.8118,27.6370
LightGBM,3.6704,6.6666,13.5859,12.9720,16.1713,17.1683,20.4288
Ridge (Linear),2.8282,5.6111,9.8235,14.1907,17.7561,20.4803,18.1890
SARIMA,3.0496,6.9018,10.2419,13.2602,15.4098,18.1749,22.4086
iTransformer,11.2749,13.3032,16.6898,16.8872,19.6481,22.7348,27.3623

--- RMSE($) (Model x Horizon) ---

Horizon,1,5,10,15,20,30,60
Model,,,,,,,
ARIMAX,2.1116,4.0957,5.0518,6.0917,6.7586,7.0969,5.2660
GUMNet-Lite,9.7460,10.3825,14.4880,18.1597,19.0705,22.0131,26.7456
GUMNet-Ultra,8.0017,11.1225,12.9087,14.6400,17.0031,19.2034,21.2237
Jump-Gated ARIMAX-CatBoost,2.7229,4.1143,5.2355,7.1464,8.6984,9.4270,6.1706
LSTM,7.8893,12.6172,13.8675,16.2082,17.3112,19.8118,27.6370
LightGBM,3.6704,6.6666,13.5859,12.9720,16.1713,17.1683,20.4288
Ridge (Linear),2.8282,5.6111,9.8235,14.1907,17.7561,20.4803,18.1890
SARIMA,3.0496,6.9018,10.2419,13.2602,15.4098,18.1749,22.4086
iTransformer,11.2749,13.3032,16.6898,16.8872,19.6481,22.7348,27.3623

--- SMAPE(%) (Model x Horizon) ---

Horizon,1,5,10,15,20,30,60
Model,,,,,,,
ARIMAX,0.9759,2.2270,2.8177,3.4515,3.8016,4.2878,4.1709
GUMNet-Lite,5.3220,7.3521,9.3575,10.3792,11.0134,11.4890,16.3188
GUMNet-Ultra,5.5228,5.3592,7.6685,8.1845,9.4322,11.8027,12.0994
Jump-Gated ARIMAX-CatBoost,1.0432,2.2260,2.8713,3.7098,4.2022,4.8323,5.8271
LSTM,5.4739,6.7112,7.3777,8.1589,8.8246,11.1174,17.9182
LightGBM,2.0372,3.9712,7.1135,5.9632,9.1415,9.5888,13.1065
Ridge (Linear),1.4252,3.3631,4.8678,6.6098,7.9662,9.6579,9.8017
SARIMA,1.5528,3.9068,5.0210,6.1194,7.3191,8.8458,11.3846
iTransformer,5.0293,6.2432,8.9964,10.2720,12.4992,15.8270,17.2676

=== Quality check vs standard (MAPE<3% H1-5 | MAPE<5% H10-20 | RMSE($)<2) ===

,Model,Horizon,MAPE(%),MAPE_thr(%),RMSE($),RMSE_thr($),Pass
0,ARIMAX,1,0.9796,3.0,2.1116,2.0,False
1,SARIMA,1,1.5540,3.0,3.0496,2.0,False
2,Jump-Gated ARIMAX-CatBoost,1,1.0457,3.0,2.7229,2.0,False
3,Ridge (Linear),1,1.4162,3.0,2.8282,2.0,False
4,LightGBM,1,2.0071,3.0,3.6704,2.0,False
...,...,...,...,...,...,...,...
58,LightGBM,60,12.5123,NaN,20.4288,2.0,False
59,LSTM,60,14.7858,NaN,27.6370,2.0,False
60,iTransformer,60,15.7833,NaN,27.3623,2.0,False
61,GUMNet-Lite,60,13.5191,NaN,26.7456,2.0,False
62,GUMNet-Ultra,60,10.8524,NaN,21.2237,2.0,False

--- Pass (Model x Horizon) ---

Horizon                        1      5      10     15     20     30     60
Model
ARIMAX                      False  False  False  False  False  False  False
GUMNet-Lite                 False  False  False  False  False  False  False
GUMNet-Ultra                False  False  False  False  False  False  False
Jump-Gated ARIMAX-CatBoost  False  False  False  False  False  False  False
LSTM                        False  False  False  False  False  False  False
LightGBM                    False  False  False  False  False  False  False
Ridge (Linear)              False  False  False  False  False  False  False
SARIMA                      False  False  False  False  False  False  False
iTransformer                False  False  False  False  False  False  False

Models meeting standard: 0/63
Saved -> e:\PCDOC\xangdau\XANG_DAU_FORECAST\XANG_DAU_FORECAST\results\clean_data_exo_ver1\by_target\MG95\multihorizon_results_10.csv
Updated -> e:\PCDOC\xangdau\XANG_DAU_FORECAST\XANG_DAU_FORECAST\results\clean_data_exo_ver1\multihorizon_results_all_targets_10.csv

## 9. Ghi chu

- **Signal decay:** do chinh xac giam khi H tang (R2 giam, MAPE/MAE tang) — bang pivot (Model x Horizon) o tren dinh luong dieu nay cho tung mo hinh. **Khong ve chart, chi in bang.**
- **Dataset:** `data/processed/clean_data_exo_ver1.csv` (doc tuong minh qua `DATA_FILENAME`). Ket qua luu theo tag dataset: `results/{DATA_TAG}/...`.
- **Sin(Date)/Cos(Date):** `DOY_sin/cos` (chu ky nam) bo sung mua vu; co the giup nhat o H lon (30/60).
- ARIMA/SARIMA: rolling H-step (append, khong refit) — nhanh va cong bang.
- DL Keras + PatchTST/TFT skip neu thieu thu vien; cai xong chay lai. Giam `CONFIG['horizons']` hoac tat `run_seq_dl`/`run_nf` neu muon nhanh.
- Ket qua: `results/{DATA_TAG}/multihorizon_results.csv`, `results/{DATA_TAG}/multihorizon_results_all_targets.csv`.

In [10]:
# Chay cac target con lai bang kernel phu, khong tao them file notebook.
is_batch_child = os.environ.get("FORECAST_BATCH_CHILD") == "1"
if CONFIG.get("run_all_targets", False) and not is_batch_child:
    from src.notebook_batch_runner import run_notebook_targets

    os.environ["FORECAST_DATA_FILE"] = DATA_FILENAME   # children inherit the same dataset
    remaining_targets = [t for t in CONFIG["targets"] if t != TARGET]
    run_notebook_targets(
        ROOT / "notebooks" / NB_FILENAME,
        remaining_targets,
        timeout=None,
    )

    all_results_path = ROOT / "results" / DATA_TAG / "multihorizon_results_all_targets_10.csv"
    all_results = pd.read_csv(all_results_path)
    target_order = {name: pos for pos, name in enumerate(CONFIG["targets"])}
    all_results["__target_order"] = all_results["Target"].map(target_order)
    all_results = all_results.sort_values(["__target_order", "Horizon", "MAPE(%)"]).drop(columns="__target_order")
    print("HOAN TAT 4 TARGETS - KET QUA MULTIHORIZON")
    display(all_results)

[Batch 1/3] Bat dau target: MG92
[Batch 1/3] Hoan tat MG92 sau 2456.0s
[Batch 2/3] Bat dau target: DO 0.001%
[Batch 2/3] Hoan tat DO 0.001% sau 2230.1s
[Batch 3/3] Bat dau target: DO 0.05%
[Batch 3/3] Hoan tat DO 0.05% sau 2145.0s
HOAN TAT 4 TARGETS - KET QUA MULTIHORIZON

,Target,Model,Horizon,MAE,RMSE,MAPE(%),SMAPE(%),R2,RMSE($),MAPE_thr(%),RMSE_thr($),Pass
0,MG95,ARIMAX,1,0.9752,2.1116,0.9796,0.9759,0.9860,2.1116,3.0,2.0,False
2,MG95,Jump-Gated ARIMAX-CatBoost,1,1.0799,2.7229,1.0457,1.0432,0.9767,2.7229,3.0,2.0,False
3,MG95,Ridge (Linear),1,1.4194,2.8282,1.4162,1.4252,0.9749,2.8282,3.0,2.0,False
1,MG95,SARIMA,1,1.5108,3.0496,1.5540,1.5528,0.9709,3.0496,3.0,2.0,False
4,MG95,LightGBM,1,1.9689,3.6704,2.0071,2.0372,0.9577,3.6704,3.0,2.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...
247,DO 0.05%,LightGBM,60,17.3920,38.1193,13.2559,15.3162,-0.3906,38.1193,NaN,2.0,False
251,DO 0.05%,GUMNet-Ultra,60,18.4899,37.0230,14.4683,16.6278,-0.2839,37.0230,NaN,2.0,False
248,DO 0.05%,LSTM,60,22.6142,47.9797,17.1324,21.9426,-1.1563,47.9797,NaN,2.0,False
250,DO 0.05%,GUMNet-Lite,60,26.5757,45.2368,22.1931,27.5020,-0.9168,45.2368,NaN,2.0,False
249,DO 0.05%,iTransformer,60,29.5240,44.9995,26.7257,28.3428,-0.8967,44.9995,NaN,2.0,False