# 09 - Multi-Horizon: Du bao 4 mat hang tai H = 1, 5, 10, 15, 20, 30, 60 (data_exo_ver2.csv)

> De `CONFIG['run_all_targets'] = True` va Run All mot lan. Notebook tu chay lan luot 4 target va hien bang multihorizon tong hop o o cuoi.

Danh gia **nhieu horizon** de do **su phan ra tin hieu** (signal decay) khi du bao cang xa. **Chi in bang ket qua (MAE, RMSE, RMSE($), MAPE, SMAPE, R2 + kiem tra dat chuan) — khong ve/luu chart.**

- **Dataset:** `data/processed/data_exo_ver2.csv`.
- **Horizons:** H ∈ {1, 5, 10, 15, 20, 30, 60} ngay.
- **Tieu chuan chat luong:** MAPE < 3% (ngan han 1-5 ngay), MAPE < 5% (trung han 10-20 ngay), RMSE($) < 2.
- **Them dac trung mua vu:** `Sin(Date)`, `Cos(Date)` (chu ky nam, day-of-year).
- **Mo hinh:** SARIMA, ARIMAX, Jump-Gated ARIMAX-CatBoost, Ridge/Linear, LightGBM, LSTM, iTransformer, GUMNet-Lite, GUMNet-Ultra, PatchTST, TFT. DL/PyTorch tu dong skip neu thieu thu vien.

> ARIMA/SARIMA dung **rolling H-step** (forecast H buoc tai moi moc, khong refit). ML/DL: target = gia mat hang dang chon tai t+H.
> Chay nang: 11 mo hinh × 7 horizon. Giam `CONFIG['horizons']` / tat `run_seq_dl`, `run_nf` de chay nhanh.

> **Jump-Gated ARIMAX-CatBoost duoc mo rong cho multi-horizon:** H1 hoi 'ngay mai co nhay gia khong'; H5..H60 hoi 'trong H ngay toi co bien dong lon khong'.

In [1]:
# === Setup ===
import os
os.environ.setdefault("TF_USE_LEGACY_KERAS", "1")   # repo models use Keras-2 API (TF 2.17 = Keras 3)
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
import warnings; warnings.filterwarnings("ignore")
import sys
from pathlib import Path
import numpy as np
import pandas as pd

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))

TARGETS = ["MG95", "MG92", "DO 0.001%", "DO 0.05%"]

# --- Dataset + notebook self-reference -------------------------------------------------
# This notebook loads data/processed/data_exo_ver2.csv. The batch run (other targets)
# re-executes THIS notebook and inherits FORECAST_DATA_FILE so every child uses the same file.
DATA_FILENAME = os.environ.get("FORECAST_DATA_FILE", "data_exo_ver2.csv")
NB_FILENAME   = "11_multihorizon.ipynb"
DATA_TAG      = Path(DATA_FILENAME).stem            # keeps outputs per-dataset (no clobber)

CONFIG = {
    "targets":      TARGETS,
    "target":       os.environ.get("FORECAST_TARGET", TARGETS[0]),
    "run_all_targets": True,
    "horizons":     [1, 5, 10, 15, 20, 30, 60],
    "train_ratio":  0.80,
    "val_ratio":    0.10,
    "exog_cols":    ["WTI", "USD_Index", "GPR", "BRT DTD", "BRT KH", "Brent_EU_Daily", "NAPHTHA"],
    "seasonal":     5,
    "seq_len_by_h": {1: 30, 5: 30, 10: 45, 15: 45, 20: 60, 30: 60, 60: 90},
    "dl_epochs":    30,      # epochs cho LSTM/iTransformer/GUMNet
    "nf_steps":     300,     # max_steps cho PatchTST/TFT
    "run_seq_dl":   True,    # LSTM/iTransformer/GUMNet (can tensorflow)
    "run_nf":       True,    # PatchTST/TFT (can neuralforecast)
    "run_jump_gated": True, # Jump-Gated ARIMAX-CatBoost multi-horizon
    "tune_lgbm":    False,
}
if CONFIG["target"] not in TARGETS:
    raise ValueError(f"Target khong hop le: {CONFIG['target']}. Chon mot trong {TARGETS}")
print("ROOT =", ROOT)
print("Dataset:", DATA_FILENAME, "| tag:", DATA_TAG)
print("Target:", CONFIG["target"], "| Horizons:", CONFIG["horizons"])

ROOT = e:\PCDOC\xangdau\XANG_DAU_FORECAST\XANG_DAU_FORECAST
Dataset: data_exo_ver2.csv | tag: data_exo_ver2
Target: MG95 | Horizons: [1, 5, 10, 15, 20, 30, 60]

## 1. Load du lieu + Sin(Date)/Cos(Date) + (tuy chon) News

In [2]:
from src.data_loader import load_and_engineer
TARGET = CONFIG["target"]
TARGET_SLUG = TARGET.replace("%", "pct").replace(" ", "_").replace(".", "_")
TARGET_RESULT_DIR = ROOT / "results" / DATA_TAG / "by_target" / TARGET_SLUG
TARGET_RESULT_DIR.mkdir(parents=True, exist_ok=True)

# Load the explicit dataset file (data_exo_ver2.csv unless overridden by FORECAST_DATA_FILE).
DATA_FILE = ROOT / "data" / "processed" / DATA_FILENAME
df = load_and_engineer(data_path=str(DATA_FILE), target_col=TARGET)
print("Loaded:", DATA_FILE.name)

# --- Sin(Date) & Cos(Date): chu ky mua vu theo nam (day-of-year) ---
doy = df.index.dayofyear.values
df["DOY_sin"] = np.sin(2 * np.pi * doy / 365.25)
df["DOY_cos"] = np.cos(2 * np.pi * doy / 365.25)
print("Added Sin(Date)/Cos(Date): DOY_sin, DOY_cos")

# --- News (optional) ---
news_path = Path("E:/PCDOC/xangdau/XANG_DAU_FORECAST/XANG_DAU_FORECAST/data/news/archive_2026-06-23/daily_features.csv")
news_cols = []
if news_path.exists():
    news = pd.read_csv(news_path, parse_dates=["date"]).set_index("date")
    news = news[~news.index.duplicated(keep="last")].sort_index()
    df = df.join(news, how="left"); news_cols = list(news.columns)
    df[news_cols] = df[news_cols].fillna(0.0)
    print(f"News joined: +{len(news_cols)} cot")
else:
    print("Khong co daily_features.csv -> chay khong co news.")

feature_cols = [c for c in df.columns if c != TARGET]
print("df:", df.shape, "| features:", len(feature_cols), "| range", df.index.min().date(), "->", df.index.max().date())

Loaded: data_exo_ver2.csv
Added Sin(Date)/Cos(Date): DOY_sin, DOY_cos
News joined: +16 cot
df: (4619, 64) | features: 63 | range 2008-06-12 -> 2026-05-08

## 2. Chi so + cac ham chuan bi du lieu (tabular & sequence)

In [3]:
from sklearn.metrics import (mean_absolute_error, mean_squared_error, r2_score,
                             accuracy_score, f1_score)
from sklearn.preprocessing import RobustScaler

# --- Quality standard ------------------------------------------------------------------
# MAPE < 3%  : short-term  (H 1-5 ngay)
# MAPE < 5%  : mid-term    (H 10-20 ngay)
# RMSE < 2$  : prices are USD -> RMSE is already in dollars (RMSE($) == RMSE)
# Long-term (H 30/60): no MAPE threshold stated -> only the RMSE($) rule applies.
RMSE_USD_THRESHOLD = 2.0
def mape_threshold(H):
    if H <= 5:  return 3.0
    if H <= 20: return 5.0
    return np.nan

def reg_metrics(y_true, y_pred, name, H):
    yt = np.asarray(y_true, float); yp = np.asarray(y_pred, float)
    mae  = mean_absolute_error(yt, yp)
    rmse = float(np.sqrt(mean_squared_error(yt, yp)))
    mape = float(np.mean(np.abs((yt - yp) / (np.abs(yt) + 1e-8))) * 100)
    smape = float(np.mean(2.0 * np.abs(yp - yt) / (np.abs(yt) + np.abs(yp) + 1e-8)) * 100)
    thr = mape_threshold(H)
    mape_ok = bool(np.isnan(thr) or mape < thr)
    rmse_ok = bool(rmse < RMSE_USD_THRESHOLD)
    return {"Model": name, "Horizon": H, "MAE": round(mae,4), "RMSE": round(rmse,4),
            "RMSE($)": round(rmse,4),                          # RMSE in USD (prices are USD)
            "MAPE(%)": round(mape,4), "SMAPE(%)": round(smape,4), "R2": round(float(r2_score(yt,yp)),4),
            "MAPE_thr(%)": thr, "RMSE_thr($)": RMSE_USD_THRESHOLD,
            "Pass": bool(mape_ok and rmse_ok)}

def prep_tabular(H):
    w = df.copy(); w["__y"] = w[TARGET].shift(-H); w = w.dropna(subset=["__y"])
    n = len(w); ntr = int(n*CONFIG["train_ratio"]); nvl = int(n*CONFIG["val_ratio"])
    tr, vl, te = w.iloc[:ntr], w.iloc[ntr:ntr+nvl], w.iloc[ntr+nvl:]
    sx = RobustScaler().fit(tr[feature_cols])
    Xtr, Xvl, Xte = sx.transform(tr[feature_cols]), sx.transform(vl[feature_cols]), sx.transform(te[feature_cols])
    out = dict(Xtr=Xtr, Xvl=Xvl, Xte=Xte,
               ytr=tr["__y"].values, yvl=vl["__y"].values, yte=te["__y"].values,
               dir_tr=(tr["__y"].values > tr[TARGET].values).astype(int),
               dir_te=(te["__y"].values > te[TARGET].values).astype(int),
               test_dates=te.index)
    return out

def prep_sequences(H):
    from src.data_loader import make_windows
    SEQ = CONFIG["seq_len_by_h"][H]
    n_df = len(df); ntr = int(n_df*CONFIG["train_ratio"])
    sxq = RobustScaler().fit(df[feature_cols].iloc[:ntr])
    syq = RobustScaler().fit(df[[TARGET]].iloc[:ntr])
    Xall = sxq.transform(df[feature_cols].values)
    yall = syq.transform(df[[TARGET]].values).flatten()
    Xw, yw = make_windows(Xall, yall, time_steps=SEQ, horizon=H)
    nW = len(Xw); a = int(nW*0.8); b = int(nW*0.1)
    return dict(Xw_tr=Xw[:a], Xw_vl=Xw[a:a+b], Xw_te=Xw[a+b:],
                yw_tr=yw[:a], yw_vl=yw[a:a+b], yw_te=yw[a+b:],
                scaler_y=syq, SEQ=SEQ, N_FEAT=len(feature_cols))

print("Helpers ready.")

Helpers ready.

## 3. Mo hinh thong ke — rolling H-step ARIMAX & SARIMA

In [4]:
from statsmodels.tsa.statespace.sarimax import SARIMAX
exog_all = [c for c in CONFIG["exog_cols"] if c in df.columns]

def _arima_rolling(y, exog, split, order, seas, H, maxiter=50):
    # Fit tren [0:split], forecast H-step tai moi moc (append, khong refit).
    res = SARIMAX(y[:split], exog=None if exog is None else exog[:split],
                  order=order, seasonal_order=seas,
                  enforce_stationarity=False, enforce_invertibility=False).fit(disp=False, maxiter=maxiter)
    cur = res; N = len(y); o = split - 1; idxs, preds = [], []
    while o + H <= N - 1:
        if exog is None: fc = cur.forecast(steps=H)
        else: fc = cur.forecast(steps=H, exog=exog[o+1:o+1+H])
        preds.append(float(np.asarray(fc)[-1])); idxs.append(o + H)
        if exog is None: cur = cur.extend(y[o+1:o+2])            # extend = O(1), khong refit
        else: cur = cur.extend(y[o+1:o+2], exog=exog[o+1:o+2])
        o += 1
    return np.array(idxs), np.array(preds)

def fit_arimax(H):
    y = df[TARGET].reset_index(drop=True).astype(float)
    ex = df[exog_all].reset_index(drop=True).astype(float)
    split = int(len(y) * 0.9)
    idx, pred = _arima_rolling(y, ex, split, (2,1,2), (0,0,0,0), H)
    return y.values[idx], pred

def fit_sarima(H):
    y = df[TARGET].reset_index(drop=True).astype(float)
    split = int(len(y) * 0.9)
    idx, pred = _arima_rolling(y, None, split, (1,1,1), (1,0,1,CONFIG["seasonal"]), H)
    return y.values[idx], pred

print("ARIMA helpers ready.")

ARIMA helpers ready.

## 4. Champion Jump-Gated ARIMAX-CatBoost multi-horizon

In [5]:
# Import the module file directly: going through `src.models` runs src/models/__init__.py,
# which eagerly imports optuna/lightgbm/catboost (via baseline_lgbm) and can fail or leave a
# stale module cached -> "cannot import name 'load_champion_frame'". This avoids all of that.
import importlib.util as _ilu
_jg_path = ROOT / "src" / "models" / "jump_gated_arimax_catboost.py"
_jg_spec = _ilu.spec_from_file_location("jump_gated_arimax_catboost", _jg_path)
_jg = _ilu.module_from_spec(_jg_spec)
sys.modules[_jg_spec.name] = _jg          # register first so @dataclass can resolve annotations
_jg_spec.loader.exec_module(_jg)
JumpGatedConfig = _jg.JumpGatedConfig
load_champion_frame = _jg.load_champion_frame
run_jump_gated_arimax_catboost_horizon = _jg.run_jump_gated_arimax_catboost_horizon

jump_details = {}
# Use the SAME dataset as the rest of the notebook (load_champion_frame defaults to ver1).
champion_df = load_champion_frame(root=ROOT, data_path=DATA_FILE)
print("Champion frame:", champion_df.shape, "|", champion_df.index.min().date(), "->", champion_df.index.max().date())

# ver2 drops some exogenous columns (GPR / BRT KH / Brent_EU_Daily); keep only what's present.
jump_exog = [c for c in CONFIG["exog_cols"] if c in champion_df.columns]
print("Jump-Gated exog:", jump_exog)

def fit_jump_gated_arimax_catboost(H):
    cfg = JumpGatedConfig(
        target=TARGET,
        horizon=H,
        train_ratio=CONFIG["train_ratio"],
        val_ratio=CONFIG["val_ratio"],
        exog_cols=jump_exog,
        arimax_order=(2, 1, 2),
        # Tuned in notebook 06: smaller grid, more stable for H1-H60.
        oof_folds=3,
        oof_min_train_frac=0.60,
        jump_thresholds=[1.5, 2.5, 4.0, 6.0],
        soft_gammas=[0.5, 1.0],
        hard_cutoffs=[0.25, 0.40, 0.55],
    )
    out = run_jump_gated_arimax_catboost_horizon(
        champion_df,
        horizon=H,
        root=ROOT,
        config=cfg,
        exact_h1=True,
        progress=True,
    )
    jump_details[H] = out
    return out["y_test"], out["pred_jump_gated"]

print("Champion Jump-Gated ARIMAX-CatBoost multi-horizon helper ready.")

Champion frame: (4619, 11) | 2008-06-12 -> 2026-05-08
Jump-Gated exog: ['WTI', 'USD_Index', 'BRT DTD', 'NAPHTHA']
Champion Jump-Gated ARIMAX-CatBoost multi-horizon helper ready.

## 5. ML models - Ridge, LightGBM, Logistic (huong)

In [6]:
from sklearn.linear_model import Ridge, LogisticRegression
import lightgbm as lgb

def fit_ridge(d):
    m = Ridge(alpha=1.0).fit(d["Xtr"], d["ytr"]); return d["yte"], m.predict(d["Xte"])

def fit_lgbm(d):
    if CONFIG["tune_lgbm"]:
        from src.models.baseline_lgbm import tune_lgbm, train_lgbm
        bp = tune_lgbm(d["Xtr"], d["ytr"], d["Xvl"], d["yvl"], n_trials=30)["best_params"]
        m = train_lgbm(d["Xtr"], d["ytr"], d["Xvl"], d["yvl"], bp)
    else:
        m = lgb.LGBMRegressor(n_estimators=600, learning_rate=0.03, max_depth=7, num_leaves=63,
                              subsample=0.8, colsample_bytree=0.8, min_child_samples=20,
                              random_state=42, n_jobs=-1, verbose=-1)
        m.fit(d["Xtr"], d["ytr"], eval_set=[(d["Xvl"], d["yvl"])],
              callbacks=[lgb.early_stopping(50, verbose=False)])
    return d["yte"], m.predict(d["Xte"])

def fit_logistic(d, H):
    clf = LogisticRegression(max_iter=2000, class_weight="balanced").fit(d["Xtr"], d["dir_tr"])
    p = clf.predict(d["Xte"])
    return {"Model": "LogisticRegression (huong)", "Horizon": H,
            "Accuracy": round(float(accuracy_score(d["dir_te"], p)),4),
            "F1": round(float(f1_score(d["dir_te"], p, zero_division=0)),4),
            "BaseUpRate": round(float(d["dir_te"].mean()),4)}
print("ML helpers ready.")

ML helpers ready.

## 6. Deep models - LSTM, iTransformer, GUMNet-Lite/Ultra (Keras); PatchTST/TFT (neuralforecast)

In [7]:
def _seq_eval(model, s):
    pred = s["scaler_y"].inverse_transform(np.asarray(model.predict(s["Xw_te"], verbose=0)).reshape(-1,1)).flatten()
    ytru = s["scaler_y"].inverse_transform(s["yw_te"].reshape(-1,1)).flatten()
    return ytru, pred

def fit_lstm(s, H):
    import tensorflow as tf
    from tensorflow.keras import layers, Model
    tf.random.set_seed(42); tf.keras.backend.clear_session()
    inp = layers.Input((s["SEQ"], s["N_FEAT"]))
    x = layers.LSTM(64, return_sequences=True)(inp); x = layers.Dropout(0.2)(x)
    x = layers.LSTM(32)(x); x = layers.Dense(16, activation="relu")(x)
    out = layers.Dense(1)(x)
    m = Model(inp, out); m.compile(optimizer="adam", loss="mse")
    es = tf.keras.callbacks.EarlyStopping(patience=8, restore_best_weights=True)
    m.fit(s["Xw_tr"], s["yw_tr"], validation_data=(s["Xw_vl"], s["yw_vl"]),
          epochs=CONFIG["dl_epochs"], batch_size=64, callbacks=[es], verbose=0)
    return _seq_eval(m, s)

def fit_itransformer(s, H):
    from src.models.hybrid_sota import train_itransformer
    m, _ = train_itransformer(s["Xw_tr"], s["yw_tr"], s["Xw_vl"], s["yw_vl"],
                              time_steps=s["SEQ"], n_features=s["N_FEAT"], horizon=H,
                              epochs=CONFIG["dl_epochs"], batch_size=64)
    return _seq_eval(m, s)

def fit_gumnet_lite(s, H):
    from src.models.hybrid_sota import train_gumnet_lite
    m, _ = train_gumnet_lite(s["Xw_tr"], s["yw_tr"], s["Xw_vl"], s["yw_vl"],
                             time_steps=s["SEQ"], n_features=s["N_FEAT"], horizon=H,
                             epochs=CONFIG["dl_epochs"], batch_size=64)
    return _seq_eval(m, s)

def fit_gumnet_ultra(s, H):
    from src.models.hybrid_sota import train_gumnet_ultra
    m, _ = train_gumnet_ultra(s["Xw_tr"], s["yw_tr"], s["Xw_vl"], s["yw_vl"],
                              time_steps=s["SEQ"], n_features=s["N_FEAT"], horizon=H,
                              epochs=CONFIG["dl_epochs"], batch_size=64)
    return _seq_eval(m, s)

def fit_neuralforecast(H):
    from neuralforecast import NeuralForecast
    from neuralforecast.models import PatchTST, TFT
    nf_exog = [c for c in CONFIG["exog_cols"] if c in df.columns]
    base = df[[TARGET] + nf_exog].copy().asfreq("B").ffill()
    long = base.reset_index(); long.columns = ["ds"] + [TARGET] + nf_exog
    long["unique_id"] = TARGET; long["y"] = long[TARGET]
    long = long[["unique_id", "ds", "y"] + nf_exog]
    n_win = min(200, max(20, int(len(df) * 0.1)))
    common = dict(h=H, input_size=CONFIG["seq_len_by_h"][H], max_steps=CONFIG["nf_steps"],
                  scaler_type="robust", hist_exog_list=nf_exog, enable_progress_bar=False)
    nf = NeuralForecast(models=[PatchTST(**common), TFT(**common)], freq="B")
    cv = nf.cross_validation(df=long, n_windows=n_win, step_size=1)
    res = {}
    for mname in ["PatchTST", "TFT"]:
        if mname in cv.columns:
            sub = cv.dropna(subset=[mname]); res[mname] = (sub["y"].values, sub[mname].values)
    return res
print("DL helpers ready.")

DL helpers ready.

## 7. Driver - chay tat ca mo hinh tren tat ca horizon

In [8]:
import time
results = []      # regression rows (co Horizon)
clf_results = []  # logistic rows

for H in CONFIG["horizons"]:
    t0 = time.time(); print("="*70); print(f"HORIZON H = {H}"); print("="*70)
    d = prep_tabular(H)

    # --- statistical ---
    for name, fn in [("ARIMAX", fit_arimax), ("SARIMA", fit_sarima)]:
        try:
            yt, yp = fn(H); results.append(reg_metrics(yt, yp, name, H)); print(" ", results[-1])
        except Exception as e:
            print(f"  {name} skipped:", repr(e))

    # --- hybrid moi: ARIMAX-CatBoost co cong nhan dien bien dong lon ---
    if CONFIG.get("run_jump_gated", True):
        try:
            yt, yp = fit_jump_gated_arimax_catboost(H)
            results.append(reg_metrics(yt, yp, "Jump-Gated ARIMAX-CatBoost", H))
            print(" ", results[-1])
        except Exception as e:
            print("  Jump-Gated ARIMAX-CatBoost skipped:", repr(e))

    # --- linear / tree ---
    for name, fn in [("Ridge (Linear)", fit_ridge), ("LightGBM", fit_lgbm)]:
        try:
            yt, yp = fn(d); results.append(reg_metrics(yt, yp, name, H)); print(" ", results[-1])
        except Exception as e:
            print(f"  {name} skipped:", repr(e))

    # # --- logistic direction ---
    # try:
    #     clf_results.append(fit_logistic(d, H)); print(" ", clf_results[-1])
    # except Exception as e:
    #     print("  Logistic skipped:", repr(e))

    # --- sequence DL (Keras) ---
    if CONFIG["run_seq_dl"]:
        try:
            s = prep_sequences(H)
            for name, fn in [("LSTM", fit_lstm), ("iTransformer", fit_itransformer),
                             ("GUMNet-Lite", fit_gumnet_lite), ("GUMNet-Ultra", fit_gumnet_ultra)]:
                try:
                    yt, yp = fn(s, H); results.append(reg_metrics(yt, yp, name, H)); print(" ", results[-1])
                except Exception as e:
                    print(f"  {name} skipped:", repr(e))
        except Exception as e:
            print("  Sequence prep skipped:", repr(e))

    # --- PatchTST / TFT (neuralforecast) ---
    if CONFIG["run_nf"]:
        try:
            for mname, (yt, yp) in fit_neuralforecast(H).items():
                results.append(reg_metrics(yt, yp, mname, H)); print(" ", results[-1])
        except Exception as e:
            print("  PatchTST/TFT skipped:", repr(e))

    print(f"  [H={H}] done in {time.time()-t0:.1f}s")

print("\nALL HORIZONS DONE. rows:", len(results))

======================================================================
HORIZON H = 1
======================================================================
  {'Model': 'ARIMAX', 'Horizon': 1, 'MAE': 0.9543, 'RMSE': 2.0175, 'RMSE($)': 2.0175, 'MAPE(%)': 0.9639, 'SMAPE(%)': 0.9608, 'R2': 0.9872, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'SARIMA', 'Horizon': 1, 'MAE': 1.5108, 'RMSE': 3.0496, 'RMSE($)': 3.0496, 'MAPE(%)': 1.554, 'SMAPE(%)': 1.5528, 'R2': 0.9709, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
OOF fold 1: 2018-02-13 -> 2020-04-08 | MAE=0.6384
OOF fold 2: 2020-04-09 -> 2022-06-01 | MAE=0.7909
OOF fold 3: 2022-06-02 -> 2024-07-24 | MAE=1.2044
Jump-Gated ARIMAX-CatBoost MAE=1.0608
  {'Model': 'Jump-Gated ARIMAX-CatBoost', 'Horizon': 1, 'MAE': 1.0608, 'RMSE': 2.7247, 'RMSE($)': 2.7247, 'MAPE(%)': 1.0239, 'SMAPE(%)': 1.0211, 'R2': 0.9767, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'Ridge (Linear)', 'Horizon': 1, 'MAE': 1.3958, 'RMSE': 2.8454, 'RMSE($)': 2.8454, 'MAPE(%)': 1.4263, 'SMAPE(%)': 1.4276, 'R2': 0.9746, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LightGBM', 'Horizon': 1, 'MAE': 1.9601, 'RMSE': 3.6035, 'RMSE($)': 3.6035, 'MAPE(%)': 2.0137, 'SMAPE(%)': 2.0422, 'R2': 0.9592, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
WARNING:tensorflow:From c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

  {'Model': 'LSTM', 'Horizon': 1, 'MAE': 3.9072, 'RMSE': 7.2541, 'RMSE($)': 7.2541, 'MAPE(%)': 3.9658, 'SMAPE(%)': 4.0746, 'R2': 0.8357, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - loss: 0.9301 - mae: 0.2851 - val_loss: 1.3233 - val_mae: 0.4069 - learning_rate: 5.0000e-04
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.5305 - mae: 0.1685 - val_loss: 0.8359 - val_mae: 0.2618 - learning_rate: 5.0000e-04
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - loss: 0.4552 - mae: 0.1456 - val_loss: 0.7570 - val_mae: 0.2381 - learning_rate: 5.0000e-04
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.4137 - mae: 0.1329 - val_loss: 0.3676 - val_mae: 0.1190 - learning_rate: 5.0000e-04
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.3624 - mae: 0.1170 - val_loss: 0.4063 - val_mae: 0.1308 - learning_rate: 5.0000e-04
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step - loss: 0.3370 - mae: 0.1090 - val_loss: 0.3217 - val_mae: 0.1045 - learning_rate: 5.0000e-04
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.3448 - mae: 0.1115 - val_loss: 0.3054 - val_mae: 0.0993 - learning_rate: 5.0000e-04
Epoch 8/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step - loss: 0.3021 - mae: 0.0980 - val_loss: 0.5314 - val_mae: 0.1700 - learning_rate: 5.0000e-04
Epoch 9/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - loss: 0.2892 - mae: 0.0938 - val_loss: 0.2871 - val_mae: 0.0936 - learning_rate: 5.0000e-04
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step - loss: 0.2718 - mae: 0.0884 - val_loss: 0.2745 - val_mae: 0.0896 - learning_rate: 5.0000e-04
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2775 - mae: 0.0902 - val_loss: 0.2414 - val_mae: 0.0789 - learning_rate: 5.0000e-04
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.2645 - mae: 0.0861 - val_loss: 0.2420 - val_mae: 0.0791 - learning_rate: 5.0000e-04
Epoch 13/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.2825 - mae: 0.0917 - val_loss: 0.2454 - val_mae: 0.0801 - learning_rate: 5.0000e-04
Epoch 14/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2577 - mae: 0.0839 - val_loss: 0.2498 - val_mae: 0.0816 - learning_rate: 5.0000e-04
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2548 - mae: 0.0829 - val_loss: 0.2840 - val_mae: 0.0924 - learning_rate: 5.0000e-04
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2359 - mae: 0.0769 - val_loss: 0.2321 - val_mae: 0.0759 - learning_rate: 5.0000e-04
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2418 - mae: 0.0788 - val_loss: 0.2402 - val_mae: 0.0785 - learning_rate: 5.0000e-04
Epoch 18/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2504 - mae: 0.0816 - val_loss: 0.2685 - val_mae: 0.0876 - learning_rate: 5.0000e-04
Epoch 19/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2558 - mae: 0.0833 - val_loss: 0.4423 - val_mae: 0.1424 - learning_rate: 5.0000e-04
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2324 - mae: 0.0758 - val_loss: 0.2125 - val_mae: 0.0696 - learning_rate: 5.0000e-04
Epoch 21/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2281 - mae: 0.0745 - val_loss: 0.2365 - val_mae: 0.0773 - learning_rate: 5.0000e-04
Epoch 22/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2368 - mae: 0.0772 - val_loss: 0.2378 - val_mae: 0.0778 - learning_rate: 5.0000e-04
Epoch 23/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2242 - mae: 0.0732 - val_loss: 0.2251 - val_mae: 0.0737 - learning_rate: 5.0000e-04
Epoch 24/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2431 - mae: 0.0792 - val_loss: 0.2261 - val_mae: 0.0740 - learning_rate: 5.0000e-04
Epoch 25/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.2345 - mae: 0.0765
Epoch 25: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2344 - mae: 0.0764 - val_loss: 0.2274 - val_mae: 0.0744 - learning_rate: 5.0000e-04
Epoch 26/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2041 - mae: 0.0668 - val_loss: 0.2350 - val_mae: 0.0768 - learning_rate: 2.5000e-04
Epoch 27/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.1976 - mae: 0.0647 - val_loss: 0.2016 - val_mae: 0.0661 - learning_rate: 2.5000e-04
Epoch 28/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2056 - mae: 0.0672 - val_loss: 0.2198 - val_mae: 0.0719 - learning_rate: 2.5000e-04
Epoch 29/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.1996 - mae: 0.0653 - val_loss: 0.2068 - val_mae: 0.0677 - learning_rate: 2.5000e-04
Epoch 30/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.1964 - mae: 0.0643 - val_loss: 0.2093 - val_mae: 0.0686 - learning_rate: 2.5000e-04
Restoring model weights from the end of the best epoch: 27.
  {'Model': 'iTransformer', 'Horizon': 1, 'MAE': 5.7601, 'RMSE': 12.0129, 'RMSE($)': 12.0129, 'MAPE(%)': 5.3123, 'SMAPE(%)': 5.6518, 'R2': 0.5494, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 1.6284 - mae: 0.4765 - val_loss: 0.4385 - val_mae: 0.1414 - learning_rate: 0.0010
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.5476 - mae: 0.1731 - val_loss: 0.5056 - val_mae: 0.1623 - learning_rate: 0.0010
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.4087 - mae: 0.1311 - val_loss: 0.5535 - val_mae: 0.1774 - learning_rate: 0.0010
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.3571 - mae: 0.1149 - val_loss: 0.3560 - val_mae: 0.1154 - learning_rate: 0.0010
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3418 - mae: 0.1103 - val_loss: 0.3310 - val_mae: 0.1074 - learning_rate: 0.0010
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.3107 - mae: 0.1005 - val_loss: 0.2885 - val_mae: 0.0939 - learning_rate: 0.0010
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2961 - mae: 0.0957 - val_loss: 0.2648 - val_mae: 0.0862 - learning_rate: 0.0010
Epoch 8/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2744 - mae: 0.0890 - val_loss: 0.2564 - val_mae: 0.0836 - learning_rate: 0.0010
Epoch 9/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2726 - mae: 0.0884 - val_loss: 0.2316 - val_mae: 0.0757 - learning_rate: 0.0010
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2792 - mae: 0.0904 - val_loss: 0.2262 - val_mae: 0.0740 - learning_rate: 0.0010
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2609 - mae: 0.0847 - val_loss: 0.2256 - val_mae: 0.0738 - learning_rate: 0.0010
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2629 - mae: 0.0852 - val_loss: 0.2371 - val_mae: 0.0774 - learning_rate: 0.0010
Epoch 13/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2565 - mae: 0.0832 - val_loss: 0.2066 - val_mae: 0.0676 - learning_rate: 0.0010
Epoch 14/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2508 - mae: 0.0814 - val_loss: 0.1969 - val_mae: 0.0645 - learning_rate: 0.0010
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2483 - mae: 0.0806 - val_loss: 0.1953 - val_mae: 0.0640 - learning_rate: 0.0010
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2423 - mae: 0.0788 - val_loss: 0.2031 - val_mae: 0.0665 - learning_rate: 0.0010
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2348 - mae: 0.0764 - val_loss: 0.1756 - val_mae: 0.0577 - learning_rate: 0.0010
Epoch 18/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2348 - mae: 0.0763 - val_loss: 0.2350 - val_mae: 0.0768 - learning_rate: 0.0010
Epoch 19/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2405 - mae: 0.0781 - val_loss: 0.1671 - val_mae: 0.0549 - learning_rate: 0.0010
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2359 - mae: 0.0767 - val_loss: 0.1696 - val_mae: 0.0557 - learning_rate: 0.0010
Epoch 21/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2135 - mae: 0.0696 - val_loss: 0.1608 - val_mae: 0.0529 - learning_rate: 0.0010
Epoch 22/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2227 - mae: 0.0725 - val_loss: 0.1719 - val_mae: 0.0565 - learning_rate: 0.0010
Epoch 23/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2281 - mae: 0.0742 - val_loss: 0.1696 - val_mae: 0.0557 - learning_rate: 0.0010
Epoch 24/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2291 - mae: 0.0745 - val_loss: 0.2093 - val_mae: 0.0686 - learning_rate: 0.0010
Epoch 25/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2212 - mae: 0.0721 - val_loss: 0.1996 - val_mae: 0.0654 - learning_rate: 0.0010
Epoch 26/30
57/58 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2189 - mae: 0.0712
Epoch 26: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2190 - mae: 0.0713 - val_loss: 0.1946 - val_mae: 0.0638 - learning_rate: 0.0010
Epoch 27/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2255 - mae: 0.0734 - val_loss: 0.1925 - val_mae: 0.0631 - learning_rate: 5.0000e-04
Epoch 28/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2114 - mae: 0.0689 - val_loss: 0.1819 - val_mae: 0.0597 - learning_rate: 5.0000e-04
Epoch 29/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2057 - mae: 0.0671 - val_loss: 0.2010 - val_mae: 0.0658 - learning_rate: 5.0000e-04
Epoch 30/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2089 - mae: 0.0681 - val_loss: 0.2112 - val_mae: 0.0691 - learning_rate: 5.0000e-04
Restoring model weights from the end of the best epoch: 21.
  {'Model': 'GUMNet-Lite', 'Horizon': 1, 'MAE': 5.0667, 'RMSE': 9.757, 'RMSE($)': 9.757, 'MAPE(%)': 5.1384, 'SMAPE(%)': 5.2097, 'R2': 0.7027, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 1.4534 - mae: 0.4301 - val_loss: 0.3091 - val_mae: 0.1005 - learning_rate: 0.0010
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.4488 - mae: 0.1436 - val_loss: 0.2861 - val_mae: 0.0928 - learning_rate: 0.0010
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.3787 - mae: 0.1219 - val_loss: 0.2326 - val_mae: 0.0761 - learning_rate: 0.0010
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.3295 - mae: 0.1066 - val_loss: 0.2021 - val_mae: 0.0662 - learning_rate: 0.0010
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3040 - mae: 0.0985 - val_loss: 0.3048 - val_mae: 0.0991 - learning_rate: 0.0010
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2888 - mae: 0.0937 - val_loss: 0.2085 - val_mae: 0.0683 - learning_rate: 0.0010
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2732 - mae: 0.0887 - val_loss: 0.2724 - val_mae: 0.0888 - learning_rate: 0.0010
Epoch 8/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2513 - mae: 0.0818 - val_loss: 0.2220 - val_mae: 0.0726 - learning_rate: 0.0010
Epoch 9/30
56/58 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2531 - mae: 0.0824
Epoch 9: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2529 - mae: 0.0823 - val_loss: 0.2463 - val_mae: 0.0805 - learning_rate: 0.0010
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2347 - mae: 0.0765 - val_loss: 0.2184 - val_mae: 0.0715 - learning_rate: 5.0000e-04
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2270 - mae: 0.0740 - val_loss: 0.1831 - val_mae: 0.0602 - learning_rate: 5.0000e-04
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2196 - mae: 0.0717 - val_loss: 0.2082 - val_mae: 0.0683 - learning_rate: 5.0000e-04
Epoch 13/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2431 - mae: 0.0792 - val_loss: 0.1693 - val_mae: 0.0557 - learning_rate: 5.0000e-04
Epoch 14/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2123 - mae: 0.0693 - val_loss: 0.1996 - val_mae: 0.0655 - learning_rate: 5.0000e-04
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2136 - mae: 0.0698 - val_loss: 0.1830 - val_mae: 0.0601 - learning_rate: 5.0000e-04
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2019 - mae: 0.0660 - val_loss: 0.1843 - val_mae: 0.0605 - learning_rate: 5.0000e-04
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2139 - mae: 0.0698 - val_loss: 0.1690 - val_mae: 0.0556 - learning_rate: 5.0000e-04
Epoch 18/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2137 - mae: 0.0697 - val_loss: 0.1709 - val_mae: 0.0562 - learning_rate: 5.0000e-04
Epoch 19/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2103 - mae: 0.0686 - val_loss: 0.1713 - val_mae: 0.0563 - learning_rate: 5.0000e-04
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2012 - mae: 0.0658 - val_loss: 0.1720 - val_mae: 0.0565 - learning_rate: 5.0000e-04
Epoch 21/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1936 - mae: 0.0633 - val_loss: 0.1712 - val_mae: 0.0562 - learning_rate: 5.0000e-04
Epoch 22/30
57/58 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1977 - mae: 0.0646
Epoch 22: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1974 - mae: 0.0645 - val_loss: 0.1767 - val_mae: 0.0580 - learning_rate: 5.0000e-04
Epoch 23/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1887 - mae: 0.0617 - val_loss: 0.1732 - val_mae: 0.0569 - learning_rate: 2.5000e-04
Epoch 24/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1940 - mae: 0.0634 - val_loss: 0.1595 - val_mae: 0.0525 - learning_rate: 2.5000e-04
Epoch 25/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.1884 - mae: 0.0616 - val_loss: 0.1582 - val_mae: 0.0521 - learning_rate: 2.5000e-04
Epoch 26/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1801 - mae: 0.0589 - val_loss: 0.1538 - val_mae: 0.0506 - learning_rate: 2.5000e-04
Epoch 27/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.1808 - mae: 0.0591 - val_loss: 0.1576 - val_mae: 0.0519 - learning_rate: 2.5000e-04
Epoch 28/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1826 - mae: 0.0598 - val_loss: 0.1652 - val_mae: 0.0543 - learning_rate: 2.5000e-04
Epoch 29/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1776 - mae: 0.0582 - val_loss: 0.1581 - val_mae: 0.0520 - learning_rate: 2.5000e-04
Epoch 30/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1737 - mae: 0.0569 - val_loss: 0.1577 - val_mae: 0.0519 - learning_rate: 2.5000e-04
Restoring model weights from the end of the best epoch: 26.
  {'Model': 'GUMNet-Ultra', 'Horizon': 1, 'MAE': 4.9087, 'RMSE': 7.8533, 'RMSE($)': 7.8533, 'MAPE(%)': 5.1781, 'SMAPE(%)': 5.0668, 'R2': 0.8074, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}

2026-06-24 16:02:23,988	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
2026-06-24 16:02:24,461	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
Seed set to 1

  PatchTST/TFT skipped: Exception('PatchTST does not support historical exogenous variables.')
  [H=1] done in 174.2s
======================================================================
HORIZON H = 5
======================================================================
  {'Model': 'ARIMAX', 'Horizon': 5, 'MAE': 2.1357, 'RMSE': 3.9035, 'RMSE($)': 3.9035, 'MAPE(%)': 2.1854, 'SMAPE(%)': 2.177, 'R2': 0.9526, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'SARIMA', 'Horizon': 5, 'MAE': 3.7698, 'RMSE': 6.9018, 'RMSE($)': 6.9018, 'MAPE(%)': 3.8635, 'SMAPE(%)': 3.9068, 'R2': 0.8518, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
H=5 OOF fold 1: 2018-02-15 -> 2020-04-09 | MAE=1.5393
H=5 OOF fold 2: 2020-04-13 -> 2022-06-02 | MAE=1.8937
H=5 OOF fold 3: 2022-06-03 -> 2024-07-25 | MAE=2.9434
H=5 Jump-Gated ARIMAX-CatBoost MAPE=2.2352% | MAE=2.1905
  {'Model': 'Jump-Gated ARIMAX-CatBoost', 'Horizon': 5, 'MAE': 2.1905, 'RMSE': 4.0083, 'RMSE($)': 4.0083, 'MAPE(%)': 2.2352, 'SMAPE(%)': 2.222, 'R2': 0.9497, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'Ridge (Linear)', 'Horizon': 5, 'MAE': 3.8534, 'RMSE': 7.232, 'RMSE($)': 7.232, 'MAPE(%)': 3.9371, 'SMAPE(%)': 3.9261, 'R2': 0.8361, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LightGBM', 'Horizon': 5, 'MAE': 3.8153, 'RMSE': 6.9042, 'RMSE($)': 6.9042, 'MAPE(%)': 3.9524, 'SMAPE(%)': 4.0634, 'R2': 0.8506, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LSTM', 'Horizon': 5, 'MAE': 6.8251, 'RMSE': 12.3324, 'RMSE($)': 12.3324, 'MAPE(%)': 6.7628, 'SMAPE(%)': 7.133, 'R2': 0.526, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - loss: 1.0294 - mae: 0.3126 - val_loss: 1.6049 - val_mae: 0.4854 - learning_rate: 5.0000e-04
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.5321 - mae: 0.1693 - val_loss: 1.4267 - val_mae: 0.4337 - learning_rate: 5.0000e-04
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.4673 - mae: 0.1495 - val_loss: 1.3237 - val_mae: 0.4037 - learning_rate: 5.0000e-04
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.3819 - mae: 0.1230 - val_loss: 0.8816 - val_mae: 0.2749 - learning_rate: 5.0000e-04
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.3524 - mae: 0.1138 - val_loss: 0.8517 - val_mae: 0.2662 - learning_rate: 5.0000e-04
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.3404 - mae: 0.1100 - val_loss: 0.8260 - val_mae: 0.2585 - learning_rate: 5.0000e-04
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.3240 - mae: 0.1049 - val_loss: 0.6213 - val_mae: 0.1965 - learning_rate: 5.0000e-04
Epoch 8/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.3434 - mae: 0.1109 - val_loss: 0.7859 - val_mae: 0.2462 - learning_rate: 5.0000e-04
Epoch 9/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.3292 - mae: 0.1064 - val_loss: 0.5371 - val_mae: 0.1708 - learning_rate: 5.0000e-04
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.3078 - mae: 0.0998 - val_loss: 0.5266 - val_mae: 0.1679 - learning_rate: 5.0000e-04
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.2994 - mae: 0.0971 - val_loss: 0.5706 - val_mae: 0.1811 - learning_rate: 5.0000e-04
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 0.3237 - mae: 0.1048 - val_loss: 0.4963 - val_mae: 0.1586 - learning_rate: 5.0000e-04
Epoch 13/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - loss: 0.2971 - mae: 0.0964 - val_loss: 0.5793 - val_mae: 0.1838 - learning_rate: 5.0000e-04
Epoch 14/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - loss: 0.2983 - mae: 0.0967 - val_loss: 0.4778 - val_mae: 0.1532 - learning_rate: 5.0000e-04
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2807 - mae: 0.0912 - val_loss: 0.4481 - val_mae: 0.1438 - learning_rate: 5.0000e-04
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2934 - mae: 0.0952 - val_loss: 0.4795 - val_mae: 0.1533 - learning_rate: 5.0000e-04
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.3019 - mae: 0.0979 - val_loss: 0.4449 - val_mae: 0.1431 - learning_rate: 5.0000e-04
Epoch 18/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2676 - mae: 0.0870 - val_loss: 0.4334 - val_mae: 0.1393 - learning_rate: 5.0000e-04
Epoch 19/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2712 - mae: 0.0881 - val_loss: 0.5149 - val_mae: 0.1640 - learning_rate: 5.0000e-04
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2932 - mae: 0.0951 - val_loss: 0.4459 - val_mae: 0.1435 - learning_rate: 5.0000e-04
Epoch 21/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2771 - mae: 0.0900 - val_loss: 0.4631 - val_mae: 0.1486 - learning_rate: 5.0000e-04
Epoch 22/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2778 - mae: 0.0903 - val_loss: 0.4721 - val_mae: 0.1513 - learning_rate: 5.0000e-04
Epoch 23/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2895 - mae: 0.0939 - val_loss: 0.4217 - val_mae: 0.1358 - learning_rate: 5.0000e-04
Epoch 24/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2650 - mae: 0.0862 - val_loss: 0.4755 - val_mae: 0.1522 - learning_rate: 5.0000e-04
Epoch 25/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2649 - mae: 0.0861 - val_loss: 0.4070 - val_mae: 0.1313 - learning_rate: 5.0000e-04
Epoch 26/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2740 - mae: 0.0891 - val_loss: 0.4495 - val_mae: 0.1442 - learning_rate: 5.0000e-04
Epoch 27/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2584 - mae: 0.0841 - val_loss: 0.4236 - val_mae: 0.1363 - learning_rate: 5.0000e-04
Epoch 28/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2654 - mae: 0.0863 - val_loss: 0.4608 - val_mae: 0.1477 - learning_rate: 5.0000e-04
Epoch 29/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2659 - mae: 0.0865 - val_loss: 0.3645 - val_mae: 0.1179 - learning_rate: 5.0000e-04
Epoch 30/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2516 - mae: 0.0819 - val_loss: 0.3880 - val_mae: 0.1251 - learning_rate: 5.0000e-04
Restoring model weights from the end of the best epoch: 29.
  {'Model': 'iTransformer', 'Horizon': 5, 'MAE': 7.0743, 'RMSE': 14.8549, 'RMSE($)': 14.8549, 'MAPE(%)': 6.53, 'SMAPE(%)': 7.0757, 'R2': 0.3122, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 9s 23ms/step - loss: 1.8112 - mae: 0.5249 - val_loss: 0.4470 - val_mae: 0.1436 - learning_rate: 0.0010
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.5620 - mae: 0.1785 - val_loss: 0.4653 - val_mae: 0.1494 - learning_rate: 0.0010
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.4492 - mae: 0.1435 - val_loss: 0.3554 - val_mae: 0.1149 - learning_rate: 0.0010
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.4150 - mae: 0.1328 - val_loss: 0.4025 - val_mae: 0.1298 - learning_rate: 0.0010
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.3724 - mae: 0.1197 - val_loss: 0.4012 - val_mae: 0.1293 - learning_rate: 0.0010
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.3656 - mae: 0.1176 - val_loss: 0.3765 - val_mae: 0.1215 - learning_rate: 0.0010
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3495 - mae: 0.1126 - val_loss: 0.4069 - val_mae: 0.1309 - learning_rate: 0.0010
Epoch 8/30
56/58 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3572 - mae: 0.1149
Epoch 8: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.3569 - mae: 0.1148 - val_loss: 0.4338 - val_mae: 0.1394 - learning_rate: 0.0010
Epoch 9/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.3326 - mae: 0.1073 - val_loss: 0.4168 - val_mae: 0.1340 - learning_rate: 5.0000e-04
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3125 - mae: 0.1010 - val_loss: 0.4071 - val_mae: 0.1310 - learning_rate: 5.0000e-04
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2992 - mae: 0.0969 - val_loss: 0.4098 - val_mae: 0.1318 - learning_rate: 5.0000e-04
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2917 - mae: 0.0944 - val_loss: 0.4019 - val_mae: 0.1294 - learning_rate: 5.0000e-04
Epoch 13/30
57/58 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2894 - mae: 0.0938
Epoch 13: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2893 - mae: 0.0937 - val_loss: 0.3903 - val_mae: 0.1257 - learning_rate: 5.0000e-04
Epoch 14/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2838 - mae: 0.0920 - val_loss: 0.3804 - val_mae: 0.1226 - learning_rate: 2.5000e-04
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2756 - mae: 0.0893 - val_loss: 0.3894 - val_mae: 0.1255 - learning_rate: 2.5000e-04
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2614 - mae: 0.0849 - val_loss: 0.3844 - val_mae: 0.1239 - learning_rate: 2.5000e-04
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2569 - mae: 0.0834 - val_loss: 0.3576 - val_mae: 0.1154 - learning_rate: 2.5000e-04
Epoch 18/30
55/58 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2538 - mae: 0.0824
Epoch 18: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2539 - mae: 0.0824 - val_loss: 0.3793 - val_mae: 0.1222 - learning_rate: 2.5000e-04
Epoch 19/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2589 - mae: 0.0840 - val_loss: 0.3753 - val_mae: 0.1210 - learning_rate: 1.2500e-04
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2484 - mae: 0.0808 - val_loss: 0.3747 - val_mae: 0.1208 - learning_rate: 1.2500e-04
Epoch 21/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2514 - mae: 0.0817 - val_loss: 0.3766 - val_mae: 0.1215 - learning_rate: 1.2500e-04
Epoch 22/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2458 - mae: 0.0799 - val_loss: 0.3852 - val_mae: 0.1241 - learning_rate: 1.2500e-04
Epoch 23/30
51/58 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2482 - mae: 0.0806
Epoch 23: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2480 - mae: 0.0805 - val_loss: 0.3733 - val_mae: 0.1204 - learning_rate: 1.2500e-04
Epoch 23: early stopping
Restoring model weights from the end of the best epoch: 3.
  {'Model': 'GUMNet-Lite', 'Horizon': 5, 'MAE': 6.2243, 'RMSE': 11.6205, 'RMSE($)': 11.6205, 'MAPE(%)': 6.2457, 'SMAPE(%)': 6.6563, 'R2': 0.5791, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - loss: 1.1228 - mae: 0.3373 - val_loss: 0.6347 - val_mae: 0.2029 - learning_rate: 0.0010
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.4625 - mae: 0.1475 - val_loss: 0.5806 - val_mae: 0.1856 - learning_rate: 0.0010
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.3845 - mae: 0.1238 - val_loss: 0.4075 - val_mae: 0.1317 - learning_rate: 0.0010
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.3775 - mae: 0.1217 - val_loss: 0.3045 - val_mae: 0.0990 - learning_rate: 0.0010
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3338 - mae: 0.1080 - val_loss: 0.3231 - val_mae: 0.1049 - learning_rate: 0.0010
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.3231 - mae: 0.1046 - val_loss: 0.3721 - val_mae: 0.1205 - learning_rate: 0.0010
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.3147 - mae: 0.1019 - val_loss: 0.4618 - val_mae: 0.1484 - learning_rate: 0.0010
Epoch 8/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.3067 - mae: 0.0993 - val_loss: 0.4113 - val_mae: 0.1328 - learning_rate: 0.0010
Epoch 9/30
56/58 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2953 - mae: 0.0959
Epoch 9: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2950 - mae: 0.0958 - val_loss: 0.3792 - val_mae: 0.1226 - learning_rate: 0.0010
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2811 - mae: 0.0913 - val_loss: 0.3485 - val_mae: 0.1129 - learning_rate: 5.0000e-04
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2724 - mae: 0.0886 - val_loss: 0.3536 - val_mae: 0.1145 - learning_rate: 5.0000e-04
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2525 - mae: 0.0823 - val_loss: 0.3904 - val_mae: 0.1262 - learning_rate: 5.0000e-04
Epoch 13/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2586 - mae: 0.0841 - val_loss: 0.3428 - val_mae: 0.1111 - learning_rate: 5.0000e-04
Epoch 14/30
55/58 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2400 - mae: 0.0783
Epoch 14: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2400 - mae: 0.0783 - val_loss: 0.3449 - val_mae: 0.1118 - learning_rate: 5.0000e-04
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2297 - mae: 0.0749 - val_loss: 0.3347 - val_mae: 0.1085 - learning_rate: 2.5000e-04
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2347 - mae: 0.0765 - val_loss: 0.3416 - val_mae: 0.1107 - learning_rate: 2.5000e-04
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2237 - mae: 0.0730 - val_loss: 0.3342 - val_mae: 0.1084 - learning_rate: 2.5000e-04
Epoch 18/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2296 - mae: 0.0749 - val_loss: 0.3707 - val_mae: 0.1200 - learning_rate: 2.5000e-04
Epoch 19/30
55/58 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2226 - mae: 0.0726
Epoch 19: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2223 - mae: 0.0726 - val_loss: 0.3481 - val_mae: 0.1127 - learning_rate: 2.5000e-04
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2100 - mae: 0.0686 - val_loss: 0.3565 - val_mae: 0.1154 - learning_rate: 1.2500e-04
Epoch 21/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2121 - mae: 0.0693 - val_loss: 0.3310 - val_mae: 0.1074 - learning_rate: 1.2500e-04
Epoch 22/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2070 - mae: 0.0677 - val_loss: 0.3400 - val_mae: 0.1102 - learning_rate: 1.2500e-04
Epoch 23/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2142 - mae: 0.0700 - val_loss: 0.3171 - val_mae: 0.1030 - learning_rate: 1.2500e-04
Epoch 24/30
55/58 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2100 - mae: 0.0686
Epoch 24: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2099 - mae: 0.0686 - val_loss: 0.3346 - val_mae: 0.1086 - learning_rate: 1.2500e-04
Epoch 24: early stopping
Restoring model weights from the end of the best epoch: 4.

Seed set to 1

  {'Model': 'GUMNet-Ultra', 'Horizon': 5, 'MAE': 5.4584, 'RMSE': 9.7735, 'RMSE($)': 9.7735, 'MAPE(%)': 5.6176, 'SMAPE(%)': 5.6549, 'R2': 0.7023, 'MAPE_thr(%)': 3.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  PatchTST/TFT skipped: Exception('PatchTST does not support historical exogenous variables.')
  [H=5] done in 157.7s
======================================================================
HORIZON H = 10
======================================================================
  {'Model': 'ARIMAX', 'Horizon': 10, 'MAE': 2.7379, 'RMSE': 4.8061, 'RMSE($)': 4.8061, 'MAPE(%)': 2.7975, 'SMAPE(%)': 2.7803, 'R2': 0.9289, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'SARIMA', 'Horizon': 10, 'MAE': 4.8785, 'RMSE': 10.2419, 'RMSE($)': 10.2419, 'MAPE(%)': 4.8296, 'SMAPE(%)': 5.021, 'R2': 0.6771, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
H=10 OOF fold 1: 2018-02-19 -> 2020-04-14 | MAE=1.9814
H=10 OOF fold 2: 2020-04-15 -> 2022-06-03 | MAE=2.8079
H=10 OOF fold 3: 2022-06-06 -> 2024-07-25 | MAE=4.2950
H=10 Jump-Gated ARIMAX-CatBoost MAPE=3.0188% | MAE=3.0470
  {'Model': 'Jump-Gated ARIMAX-CatBoost', 'Horizon': 10, 'MAE': 3.047, 'RMSE': 5.928, 'RMSE($)': 5.928, 'MAPE(%)': 3.0188, 'SMAPE(%)': 2.9681, 'R2': 0.8899, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'Ridge (Linear)', 'Horizon': 10, 'MAE': 5.952, 'RMSE': 11.9623, 'RMSE($)': 11.9623, 'MAPE(%)': 5.8164, 'SMAPE(%)': 5.7541, 'R2': 0.5516, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LightGBM', 'Horizon': 10, 'MAE': 5.4593, 'RMSE': 10.7385, 'RMSE($)': 10.7385, 'MAPE(%)': 5.4704, 'SMAPE(%)': 5.7518, 'R2': 0.6386, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LSTM', 'Horizon': 10, 'MAE': 7.8261, 'RMSE': 13.6081, 'RMSE($)': 13.6081, 'MAPE(%)': 7.8811, 'SMAPE(%)': 8.1048, 'R2': 0.4251, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - loss: 1.0500 - mae: 0.3180 - val_loss: 1.4919 - val_mae: 0.4515 - learning_rate: 5.0000e-04
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.5751 - mae: 0.1819 - val_loss: 1.2677 - val_mae: 0.3866 - learning_rate: 5.0000e-04
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.5405 - mae: 0.1714 - val_loss: 1.2599 - val_mae: 0.3824 - learning_rate: 5.0000e-04
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.4997 - mae: 0.1592 - val_loss: 1.5622 - val_mae: 0.4700 - learning_rate: 5.0000e-04
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.4312 - mae: 0.1382 - val_loss: 0.9445 - val_mae: 0.2928 - learning_rate: 5.0000e-04
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 0.4378 - mae: 0.1403 - val_loss: 1.2120 - val_mae: 0.3714 - learning_rate: 5.0000e-04
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.3679 - mae: 0.1185 - val_loss: 1.0009 - val_mae: 0.3109 - learning_rate: 5.0000e-04
Epoch 8/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.3467 - mae: 0.1119 - val_loss: 0.7114 - val_mae: 0.2246 - learning_rate: 5.0000e-04
Epoch 9/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.3486 - mae: 0.1124 - val_loss: 0.7692 - val_mae: 0.2417 - learning_rate: 5.0000e-04
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.3410 - mae: 0.1101 - val_loss: 1.0404 - val_mae: 0.3216 - learning_rate: 5.0000e-04
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.3293 - mae: 0.1065 - val_loss: 0.8955 - val_mae: 0.2784 - learning_rate: 5.0000e-04
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.3201 - mae: 0.1036 - val_loss: 0.9305 - val_mae: 0.2896 - learning_rate: 5.0000e-04
Epoch 13/30
57/58 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.3181 - mae: 0.1030
Epoch 13: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.3180 - mae: 0.1030 - val_loss: 1.1366 - val_mae: 0.3491 - learning_rate: 5.0000e-04
Epoch 14/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.3037 - mae: 0.0984 - val_loss: 0.9001 - val_mae: 0.2812 - learning_rate: 2.5000e-04
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.2947 - mae: 0.0956 - val_loss: 0.9778 - val_mae: 0.3036 - learning_rate: 2.5000e-04
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2896 - mae: 0.0940 - val_loss: 0.9090 - val_mae: 0.2830 - learning_rate: 2.5000e-04
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.3006 - mae: 0.0974 - val_loss: 0.8997 - val_mae: 0.2807 - learning_rate: 2.5000e-04
Epoch 18/30
56/58 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.2945 - mae: 0.0956
Epoch 18: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2943 - mae: 0.0955 - val_loss: 0.8338 - val_mae: 0.2611 - learning_rate: 2.5000e-04
Epoch 19/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2696 - mae: 0.0876 - val_loss: 0.7852 - val_mae: 0.2467 - learning_rate: 1.2500e-04
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2695 - mae: 0.0876 - val_loss: 0.8169 - val_mae: 0.2561 - learning_rate: 1.2500e-04
Epoch 21/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.2685 - mae: 0.0872 - val_loss: 0.7867 - val_mae: 0.2471 - learning_rate: 1.2500e-04
Epoch 22/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2630 - mae: 0.0855 - val_loss: 0.8461 - val_mae: 0.2650 - learning_rate: 1.2500e-04
Epoch 23/30
57/58 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.2650 - mae: 0.0862
Epoch 23: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.2650 - mae: 0.0862 - val_loss: 0.9848 - val_mae: 0.3059 - learning_rate: 1.2500e-04
Epoch 24/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2616 - mae: 0.0850 - val_loss: 0.8425 - val_mae: 0.2638 - learning_rate: 6.2500e-05
Epoch 25/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2566 - mae: 0.0835 - val_loss: 0.8022 - val_mae: 0.2519 - learning_rate: 6.2500e-05
Epoch 26/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.2571 - mae: 0.0836 - val_loss: 0.8585 - val_mae: 0.2684 - learning_rate: 6.2500e-05
Epoch 27/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.2570 - mae: 0.0836 - val_loss: 0.8112 - val_mae: 0.2544 - learning_rate: 6.2500e-05
Epoch 28/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.2483 - mae: 0.0809
Epoch 28: ReduceLROnPlateau reducing learning rate to 3.125000148429535e-05.
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.2484 - mae: 0.0809 - val_loss: 0.8359 - val_mae: 0.2617 - learning_rate: 6.2500e-05
Epoch 28: early stopping
Restoring model weights from the end of the best epoch: 8.
  {'Model': 'iTransformer', 'Horizon': 10, 'MAE': 9.1345, 'RMSE': 17.4575, 'RMSE($)': 17.4575, 'MAPE(%)': 8.5999, 'SMAPE(%)': 9.3182, 'R2': 0.0538, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 9s 30ms/step - loss: 1.7626 - mae: 0.5108 - val_loss: 0.3985 - val_mae: 0.1286 - learning_rate: 0.0010
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.5363 - mae: 0.1699 - val_loss: 0.4500 - val_mae: 0.1448 - learning_rate: 0.0010
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.4396 - mae: 0.1406 - val_loss: 0.5233 - val_mae: 0.1676 - learning_rate: 0.0010
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.4117 - mae: 0.1319 - val_loss: 0.4849 - val_mae: 0.1553 - learning_rate: 0.0010
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.3965 - mae: 0.1272 - val_loss: 0.5810 - val_mae: 0.1853 - learning_rate: 0.0010
Epoch 6/30
55/58 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.3784 - mae: 0.1216
Epoch 6: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.3778 - mae: 0.1214 - val_loss: 0.5368 - val_mae: 0.1714 - learning_rate: 0.0010
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.3587 - mae: 0.1153 - val_loss: 0.6067 - val_mae: 0.1929 - learning_rate: 5.0000e-04
Epoch 8/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.3588 - mae: 0.1154 - val_loss: 0.5562 - val_mae: 0.1774 - learning_rate: 5.0000e-04
Epoch 9/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.3439 - mae: 0.1107 - val_loss: 0.5620 - val_mae: 0.1793 - learning_rate: 5.0000e-04
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.3303 - mae: 0.1064 - val_loss: 0.5732 - val_mae: 0.1826 - learning_rate: 5.0000e-04
Epoch 11/30
55/58 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.3220 - mae: 0.1038
Epoch 11: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.3219 - mae: 0.1038 - val_loss: 0.5284 - val_mae: 0.1688 - learning_rate: 5.0000e-04
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.3224 - mae: 0.1040 - val_loss: 0.5137 - val_mae: 0.1643 - learning_rate: 2.5000e-04
Epoch 13/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.3095 - mae: 0.1000 - val_loss: 0.5246 - val_mae: 0.1676 - learning_rate: 2.5000e-04
Epoch 14/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.3014 - mae: 0.0975 - val_loss: 0.5291 - val_mae: 0.1690 - learning_rate: 2.5000e-04
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.3089 - mae: 0.0998 - val_loss: 0.5316 - val_mae: 0.1698 - learning_rate: 2.5000e-04
Epoch 16/30
57/58 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.2944 - mae: 0.0953
Epoch 16: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.2946 - mae: 0.0953 - val_loss: 0.4967 - val_mae: 0.1590 - learning_rate: 2.5000e-04
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.2973 - mae: 0.0961 - val_loss: 0.5077 - val_mae: 0.1623 - learning_rate: 1.2500e-04
Epoch 18/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.2879 - mae: 0.0931 - val_loss: 0.5071 - val_mae: 0.1621 - learning_rate: 1.2500e-04
Epoch 19/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.2955 - mae: 0.0957 - val_loss: 0.5090 - val_mae: 0.1627 - learning_rate: 1.2500e-04
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.2899 - mae: 0.0938 - val_loss: 0.5245 - val_mae: 0.1675 - learning_rate: 1.2500e-04
Epoch 21/30
54/58 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.2910 - mae: 0.0941
Epoch 21: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.2910 - mae: 0.0941 - val_loss: 0.5336 - val_mae: 0.1704 - learning_rate: 1.2500e-04
Epoch 21: early stopping
Restoring model weights from the end of the best epoch: 1.
  {'Model': 'GUMNet-Lite', 'Horizon': 10, 'MAE': 8.145, 'RMSE': 14.3253, 'RMSE($)': 14.3253, 'MAPE(%)': 8.3814, 'SMAPE(%)': 8.5745, 'R2': 0.3628, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 1.1493 - mae: 0.3445 - val_loss: 0.8418 - val_mae: 0.2653 - learning_rate: 0.0010
Epoch 2/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.4510 - mae: 0.1443 - val_loss: 0.6468 - val_mae: 0.2047 - learning_rate: 0.0010
Epoch 3/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3846 - mae: 0.1238 - val_loss: 0.4496 - val_mae: 0.1443 - learning_rate: 0.0010
Epoch 4/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3499 - mae: 0.1130 - val_loss: 0.5679 - val_mae: 0.1802 - learning_rate: 0.0010
Epoch 5/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3426 - mae: 0.1108 - val_loss: 0.5120 - val_mae: 0.1632 - learning_rate: 0.0010
Epoch 6/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3727 - mae: 0.1201 - val_loss: 0.5510 - val_mae: 0.1757 - learning_rate: 0.0010
Epoch 7/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.3277 - mae: 0.1061 - val_loss: 0.4875 - val_mae: 0.1560 - learning_rate: 0.0010
Epoch 8/30
55/58 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3202 - mae: 0.1038
Epoch 8: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3197 - mae: 0.1036 - val_loss: 0.4816 - val_mae: 0.1544 - learning_rate: 0.0010
Epoch 9/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2968 - mae: 0.0963 - val_loss: 0.5501 - val_mae: 0.1754 - learning_rate: 5.0000e-04
Epoch 10/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2778 - mae: 0.0903 - val_loss: 0.4783 - val_mae: 0.1536 - learning_rate: 5.0000e-04
Epoch 11/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2687 - mae: 0.0874 - val_loss: 0.5151 - val_mae: 0.1648 - learning_rate: 5.0000e-04
Epoch 12/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.2785 - mae: 0.0906 - val_loss: 0.5745 - val_mae: 0.1830 - learning_rate: 5.0000e-04
Epoch 13/30
55/58 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.2664 - mae: 0.0866
Epoch 13: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2663 - mae: 0.0866 - val_loss: 0.4969 - val_mae: 0.1594 - learning_rate: 5.0000e-04
Epoch 14/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2639 - mae: 0.0858 - val_loss: 0.5478 - val_mae: 0.1748 - learning_rate: 2.5000e-04
Epoch 15/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2491 - mae: 0.0812 - val_loss: 0.5373 - val_mae: 0.1715 - learning_rate: 2.5000e-04
Epoch 16/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2456 - mae: 0.0800 - val_loss: 0.5302 - val_mae: 0.1692 - learning_rate: 2.5000e-04
Epoch 17/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2415 - mae: 0.0787 - val_loss: 0.5373 - val_mae: 0.1715 - learning_rate: 2.5000e-04
Epoch 18/30
55/58 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.2455 - mae: 0.0800
Epoch 18: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.2455 - mae: 0.0800 - val_loss: 0.5579 - val_mae: 0.1778 - learning_rate: 2.5000e-04
Epoch 19/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2366 - mae: 0.0772 - val_loss: 0.5736 - val_mae: 0.1826 - learning_rate: 1.2500e-04
Epoch 20/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2374 - mae: 0.0774 - val_loss: 0.5755 - val_mae: 0.1831 - learning_rate: 1.2500e-04
Epoch 21/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.2319 - mae: 0.0757 - val_loss: 0.5835 - val_mae: 0.1855 - learning_rate: 1.2500e-04
Epoch 22/30
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2305 - mae: 0.0752 - val_loss: 0.5875 - val_mae: 0.1866 - learning_rate: 1.2500e-04
Epoch 23/30
55/58 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.2295 - mae: 0.0749
Epoch 23: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.2296 - mae: 0.0749 - val_loss: 0.5685 - val_mae: 0.1808 - learning_rate: 1.2500e-04
Epoch 23: early stopping
Restoring model weights from the end of the best epoch: 3.

Seed set to 1

  {'Model': 'GUMNet-Ultra', 'Horizon': 10, 'MAE': 7.8783, 'RMSE': 13.7337, 'RMSE($)': 13.7337, 'MAPE(%)': 7.9132, 'SMAPE(%)': 7.8989, 'R2': 0.4144, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  PatchTST/TFT skipped: Exception('PatchTST does not support historical exogenous variables.')
  [H=10] done in 178.8s
======================================================================
HORIZON H = 15
======================================================================
  {'Model': 'ARIMAX', 'Horizon': 15, 'MAE': 3.3789, 'RMSE': 5.8498, 'RMSE($)': 5.8498, 'MAPE(%)': 3.4417, 'SMAPE(%)': 3.4112, 'R2': 0.8958, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'SARIMA', 'Horizon': 15, 'MAE': 5.989, 'RMSE': 13.2602, 'RMSE($)': 13.2602, 'MAPE(%)': 5.7751, 'SMAPE(%)': 6.1194, 'R2': 0.4644, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
H=15 OOF fold 1: 2018-02-21 -> 2020-04-15 | MAE=2.2336
H=15 OOF fold 2: 2020-04-16 -> 2022-06-06 | MAE=3.5654

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

H=15 OOF fold 3: 2022-06-07 -> 2024-07-26 | MAE=5.2861
H=15 Jump-Gated ARIMAX-CatBoost MAPE=3.6231% | MAE=3.6204
  {'Model': 'Jump-Gated ARIMAX-CatBoost', 'Horizon': 15, 'MAE': 3.6204, 'RMSE': 6.573, 'RMSE($)': 6.573, 'MAPE(%)': 3.6231, 'SMAPE(%)': 3.5652, 'R2': 0.8648, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'Ridge (Linear)', 'Horizon': 15, 'MAE': 7.7045, 'RMSE': 16.0423, 'RMSE($)': 16.0423, 'MAPE(%)': 7.3314, 'SMAPE(%)': 7.2034, 'R2': 0.1949, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LightGBM', 'Horizon': 15, 'MAE': 7.0923, 'RMSE': 14.088, 'RMSE($)': 14.088, 'MAPE(%)': 6.8966, 'SMAPE(%)': 7.275, 'R2': 0.3791, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LSTM', 'Horizon': 15, 'MAE': 8.4622, 'RMSE': 14.2932, 'RMSE($)': 14.2932, 'MAPE(%)': 8.6405, 'SMAPE(%)': 9.0361, 'R2': 0.3669, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - loss: 1.0451 - mae: 0.3170 - val_loss: 1.2271 - val_mae: 0.3774 - learning_rate: 5.0000e-04
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.5915 - mae: 0.1873 - val_loss: 1.4369 - val_mae: 0.4354 - learning_rate: 5.0000e-04
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.5131 - mae: 0.1633 - val_loss: 1.2307 - val_mae: 0.3769 - learning_rate: 5.0000e-04
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.4704 - mae: 0.1504 - val_loss: 1.0043 - val_mae: 0.3117 - learning_rate: 5.0000e-04
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.4456 - mae: 0.1426 - val_loss: 1.0828 - val_mae: 0.3329 - learning_rate: 5.0000e-04
Epoch 6/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.4029 - mae: 0.1294 - val_loss: 0.8415 - val_mae: 0.2639 - learning_rate: 5.0000e-04
Epoch 7/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.4042 - mae: 0.1299 - val_loss: 1.3836 - val_mae: 0.4233 - learning_rate: 5.0000e-04
Epoch 8/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.3759 - mae: 0.1210 - val_loss: 1.0612 - val_mae: 0.3278 - learning_rate: 5.0000e-04
Epoch 9/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.3638 - mae: 0.1171 - val_loss: 0.8652 - val_mae: 0.2712 - learning_rate: 5.0000e-04
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.3734 - mae: 0.1202 - val_loss: 0.7491 - val_mae: 0.2361 - learning_rate: 5.0000e-04
Epoch 11/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.3669 - mae: 0.1183 - val_loss: 0.8536 - val_mae: 0.2666 - learning_rate: 5.0000e-04
Epoch 12/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.3425 - mae: 0.1105 - val_loss: 0.9856 - val_mae: 0.3064 - learning_rate: 5.0000e-04
Epoch 13/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.3368 - mae: 0.1087 - val_loss: 0.8478 - val_mae: 0.2657 - learning_rate: 5.0000e-04
Epoch 14/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.3293 - mae: 0.1064 - val_loss: 0.8713 - val_mae: 0.2720 - learning_rate: 5.0000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.3425 - mae: 0.1107 - val_loss: 0.7159 - val_mae: 0.2261 - learning_rate: 5.0000e-04
Epoch 16/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.3271 - mae: 0.1057 - val_loss: 0.8222 - val_mae: 0.2580 - learning_rate: 5.0000e-04
Epoch 17/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.3081 - mae: 0.0998 - val_loss: 0.8771 - val_mae: 0.2741 - learning_rate: 5.0000e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.3012 - mae: 0.0976 - val_loss: 0.7998 - val_mae: 0.2512 - learning_rate: 5.0000e-04
Epoch 19/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.3212 - mae: 0.1039 - val_loss: 0.9633 - val_mae: 0.2997 - learning_rate: 5.0000e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.3192 - mae: 0.1032
Epoch 20: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.3192 - mae: 0.1032 - val_loss: 0.8020 - val_mae: 0.2520 - learning_rate: 5.0000e-04
Epoch 21/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.2943 - mae: 0.0954 - val_loss: 0.8246 - val_mae: 0.2588 - learning_rate: 2.5000e-04
Epoch 22/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.2887 - mae: 0.0936 - val_loss: 0.8152 - val_mae: 0.2561 - learning_rate: 2.5000e-04
Epoch 23/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.2861 - mae: 0.0929 - val_loss: 0.8059 - val_mae: 0.2533 - learning_rate: 2.5000e-04
Epoch 24/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.2858 - mae: 0.0928 - val_loss: 0.8593 - val_mae: 0.2689 - learning_rate: 2.5000e-04
Epoch 25/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2718 - mae: 0.0883
Epoch 25: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.2717 - mae: 0.0883 - val_loss: 0.7402 - val_mae: 0.2334 - learning_rate: 2.5000e-04
Epoch 26/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.2692 - mae: 0.0875 - val_loss: 0.7788 - val_mae: 0.2450 - learning_rate: 1.2500e-04
Epoch 27/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 0.2581 - mae: 0.0840 - val_loss: 0.8843 - val_mae: 0.2761 - learning_rate: 1.2500e-04
Epoch 28/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 0.2574 - mae: 0.0837 - val_loss: 0.8590 - val_mae: 0.2687 - learning_rate: 1.2500e-04
Epoch 29/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 0.2560 - mae: 0.0833 - val_loss: 0.9754 - val_mae: 0.3029 - learning_rate: 1.2500e-04
Epoch 30/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.2510 - mae: 0.0817
Epoch 30: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 0.2509 - mae: 0.0817 - val_loss: 0.8226 - val_mae: 0.2579 - learning_rate: 1.2500e-04
Restoring model weights from the end of the best epoch: 15.
  {'Model': 'iTransformer', 'Horizon': 15, 'MAE': 10.7986, 'RMSE': 17.2642, 'RMSE($)': 17.2642, 'MAPE(%)': 10.8965, 'SMAPE(%)': 11.1848, 'R2': 0.0764, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - loss: 1.7814 - mae: 0.5156 - val_loss: 0.5147 - val_mae: 0.1642 - learning_rate: 0.0010
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.5370 - mae: 0.1705 - val_loss: 0.5502 - val_mae: 0.1750 - learning_rate: 0.0010
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.4548 - mae: 0.1455 - val_loss: 0.6141 - val_mae: 0.1950 - learning_rate: 0.0010
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.4100 - mae: 0.1313 - val_loss: 0.5416 - val_mae: 0.1729 - learning_rate: 0.0010
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.3877 - mae: 0.1245 - val_loss: 0.5788 - val_mae: 0.1840 - learning_rate: 0.0010
Epoch 6/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.3773 - mae: 0.1214
Epoch 6: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.3773 - mae: 0.1214 - val_loss: 0.5597 - val_mae: 0.1783 - learning_rate: 0.0010
Epoch 7/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.3639 - mae: 0.1171 - val_loss: 0.5652 - val_mae: 0.1801 - learning_rate: 5.0000e-04
Epoch 8/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.3400 - mae: 0.1097 - val_loss: 0.6111 - val_mae: 0.1942 - learning_rate: 5.0000e-04
Epoch 9/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.3306 - mae: 0.1067 - val_loss: 0.5709 - val_mae: 0.1814 - learning_rate: 5.0000e-04
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.3314 - mae: 0.1069 - val_loss: 0.6071 - val_mae: 0.1927 - learning_rate: 5.0000e-04
Epoch 11/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.3241 - mae: 0.1046
Epoch 11: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.3240 - mae: 0.1045 - val_loss: 0.6398 - val_mae: 0.2026 - learning_rate: 5.0000e-04
Epoch 12/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.3202 - mae: 0.1034 - val_loss: 0.6103 - val_mae: 0.1939 - learning_rate: 2.5000e-04
Epoch 13/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.3131 - mae: 0.1012 - val_loss: 0.6143 - val_mae: 0.1950 - learning_rate: 2.5000e-04
Epoch 14/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.3020 - mae: 0.0976 - val_loss: 0.5798 - val_mae: 0.1843 - learning_rate: 2.5000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.3102 - mae: 0.1001 - val_loss: 0.5725 - val_mae: 0.1820 - learning_rate: 2.5000e-04
Epoch 16/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2999 - mae: 0.0970
Epoch 16: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2998 - mae: 0.0969 - val_loss: 0.6309 - val_mae: 0.2000 - learning_rate: 2.5000e-04
Epoch 17/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.3016 - mae: 0.0975 - val_loss: 0.6158 - val_mae: 0.1953 - learning_rate: 1.2500e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2962 - mae: 0.0958 - val_loss: 0.6259 - val_mae: 0.1984 - learning_rate: 1.2500e-04
Epoch 19/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.3013 - mae: 0.0973 - val_loss: 0.6201 - val_mae: 0.1964 - learning_rate: 1.2500e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2934 - mae: 0.0949 - val_loss: 0.6377 - val_mae: 0.2019 - learning_rate: 1.2500e-04
Epoch 21/30
55/57 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.2872 - mae: 0.0931
Epoch 21: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2873 - mae: 0.0931 - val_loss: 0.6463 - val_mae: 0.2047 - learning_rate: 1.2500e-04
Epoch 21: early stopping
Restoring model weights from the end of the best epoch: 1.
  {'Model': 'GUMNet-Lite', 'Horizon': 15, 'MAE': 7.8937, 'RMSE': 16.4001, 'RMSE($)': 16.4001, 'MAPE(%)': 7.625, 'SMAPE(%)': 8.416, 'R2': 0.1666, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 9s 35ms/step - loss: 1.0988 - mae: 0.3311 - val_loss: 0.6127 - val_mae: 0.1947 - learning_rate: 0.0010
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.5006 - mae: 0.1593 - val_loss: 0.4796 - val_mae: 0.1534 - learning_rate: 0.0010
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.4096 - mae: 0.1316 - val_loss: 0.4654 - val_mae: 0.1491 - learning_rate: 0.0010
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.3860 - mae: 0.1242 - val_loss: 0.5172 - val_mae: 0.1652 - learning_rate: 0.0010
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.3623 - mae: 0.1168 - val_loss: 0.5316 - val_mae: 0.1696 - learning_rate: 0.0010
Epoch 6/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.3461 - mae: 0.1117 - val_loss: 0.5027 - val_mae: 0.1608 - learning_rate: 0.0010
Epoch 7/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.3337 - mae: 0.1079 - val_loss: 0.5375 - val_mae: 0.1718 - learning_rate: 0.0010
Epoch 8/30
55/57 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.3210 - mae: 0.1038
Epoch 8: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.3210 - mae: 0.1039 - val_loss: 0.6127 - val_mae: 0.1944 - learning_rate: 0.0010
Epoch 9/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.3010 - mae: 0.0976 - val_loss: 0.6477 - val_mae: 0.2049 - learning_rate: 5.0000e-04
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2907 - mae: 0.0943 - val_loss: 0.6509 - val_mae: 0.2059 - learning_rate: 5.0000e-04
Epoch 11/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2897 - mae: 0.0940 - val_loss: 0.6129 - val_mae: 0.1945 - learning_rate: 5.0000e-04
Epoch 12/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2771 - mae: 0.0900 - val_loss: 0.6387 - val_mae: 0.2022 - learning_rate: 5.0000e-04
Epoch 13/30
55/57 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.2681 - mae: 0.0872
Epoch 13: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.2684 - mae: 0.0873 - val_loss: 0.6147 - val_mae: 0.1949 - learning_rate: 5.0000e-04
Epoch 14/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.2585 - mae: 0.0842 - val_loss: 0.5807 - val_mae: 0.1847 - learning_rate: 2.5000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2550 - mae: 0.0830 - val_loss: 0.6019 - val_mae: 0.1913 - learning_rate: 2.5000e-04
Epoch 16/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2495 - mae: 0.0812 - val_loss: 0.6176 - val_mae: 0.1959 - learning_rate: 2.5000e-04
Epoch 17/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2452 - mae: 0.0799 - val_loss: 0.6387 - val_mae: 0.2024 - learning_rate: 2.5000e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.2419 - mae: 0.0788
Epoch 18: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2419 - mae: 0.0789 - val_loss: 0.5893 - val_mae: 0.1875 - learning_rate: 2.5000e-04
Epoch 19/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2383 - mae: 0.0777 - val_loss: 0.6252 - val_mae: 0.1983 - learning_rate: 1.2500e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2381 - mae: 0.0776 - val_loss: 0.6164 - val_mae: 0.1956 - learning_rate: 1.2500e-04
Epoch 21/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2319 - mae: 0.0756 - val_loss: 0.6133 - val_mae: 0.1947 - learning_rate: 1.2500e-04
Epoch 22/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.2302 - mae: 0.0750 - val_loss: 0.6122 - val_mae: 0.1943 - learning_rate: 1.2500e-04
Epoch 23/30
54/57 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.2250 - mae: 0.0734
Epoch 23: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2250 - mae: 0.0734 - val_loss: 0.6318 - val_mae: 0.2003 - learning_rate: 1.2500e-04
Epoch 23: early stopping
Restoring model weights from the end of the best epoch: 3.

Seed set to 1

  {'Model': 'GUMNet-Ultra', 'Horizon': 15, 'MAE': 8.6778, 'RMSE': 14.3927, 'RMSE($)': 14.3927, 'MAPE(%)': 9.0427, 'SMAPE(%)': 9.1386, 'R2': 0.3581, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  PatchTST/TFT skipped: Exception('PatchTST does not support historical exogenous variables.')
  [H=15] done in 169.1s
======================================================================
HORIZON H = 20
======================================================================
  {'Model': 'ARIMAX', 'Horizon': 20, 'MAE': 3.7386, 'RMSE': 6.5276, 'RMSE($)': 6.5276, 'MAPE(%)': 3.8345, 'SMAPE(%)': 3.78, 'R2': 0.8716, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'SARIMA', 'Horizon': 20, 'MAE': 7.1636, 'RMSE': 15.4098, 'RMSE($)': 15.4098, 'MAPE(%)': 6.833, 'SMAPE(%)': 7.3191, 'R2': 0.2847, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
H=20 OOF fold 1: 2018-02-23 -> 2020-04-17 | MAE=2.4458
H=20 OOF fold 2: 2020-04-20 -> 2022-06-07 | MAE=4.1986
H=20 OOF fold 3: 2022-06-08 -> 2024-07-26 | MAE=6.0306
H=20 Jump-Gated ARIMAX-CatBoost MAPE=4.3699% | MAE=4.3960
  {'Model': 'Jump-Gated ARIMAX-CatBoost', 'Horizon': 20, 'MAE': 4.396, 'RMSE': 8.511, 'RMSE($)': 8.511, 'MAPE(%)': 4.3699, 'SMAPE(%)': 4.2544, 'R2': 0.7734, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'Ridge (Linear)', 'Horizon': 20, 'MAE': 9.4052, 'RMSE': 19.4577, 'RMSE($)': 19.4577, 'MAPE(%)': 8.8387, 'SMAPE(%)': 8.5801, 'R2': -0.1843, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LightGBM', 'Horizon': 20, 'MAE': 9.1808, 'RMSE': 16.4714, 'RMSE($)': 16.4714, 'MAPE(%)': 9.1007, 'SMAPE(%)': 9.5536, 'R2': 0.1513, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LSTM', 'Horizon': 20, 'MAE': 10.2704, 'RMSE': 18.0289, 'RMSE($)': 18.0289, 'MAPE(%)': 10.1972, 'SMAPE(%)': 11.1663, 'R2': -0.0028, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - loss: 0.9370 - mae: 0.2869 - val_loss: 1.9117 - val_mae: 0.5682 - learning_rate: 5.0000e-04
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.5846 - mae: 0.1850 - val_loss: 1.7382 - val_mae: 0.5174 - learning_rate: 5.0000e-04
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.5175 - mae: 0.1647 - val_loss: 2.1163 - val_mae: 0.6238 - learning_rate: 5.0000e-04
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.4847 - mae: 0.1544 - val_loss: 1.4902 - val_mae: 0.4498 - learning_rate: 5.0000e-04
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.4415 - mae: 0.1412 - val_loss: 1.4132 - val_mae: 0.4295 - learning_rate: 5.0000e-04
Epoch 6/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.4224 - mae: 0.1353 - val_loss: 1.4108 - val_mae: 0.4288 - learning_rate: 5.0000e-04
Epoch 7/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.4039 - mae: 0.1295 - val_loss: 1.4034 - val_mae: 0.4259 - learning_rate: 5.0000e-04
Epoch 8/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.3888 - mae: 0.1248 - val_loss: 1.3268 - val_mae: 0.4049 - learning_rate: 5.0000e-04
Epoch 9/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.3690 - mae: 0.1187 - val_loss: 1.4094 - val_mae: 0.4281 - learning_rate: 5.0000e-04
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.3701 - mae: 0.1190 - val_loss: 1.2789 - val_mae: 0.3917 - learning_rate: 5.0000e-04
Epoch 11/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.3595 - mae: 0.1157 - val_loss: 1.2296 - val_mae: 0.3779 - learning_rate: 5.0000e-04
Epoch 12/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.3494 - mae: 0.1126 - val_loss: 1.2822 - val_mae: 0.3930 - learning_rate: 5.0000e-04
Epoch 13/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.3331 - mae: 0.1075 - val_loss: 1.3357 - val_mae: 0.4077 - learning_rate: 5.0000e-04
Epoch 14/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.3354 - mae: 0.1082 - val_loss: 1.4264 - val_mae: 0.4338 - learning_rate: 5.0000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.3525 - mae: 0.1136 - val_loss: 1.1715 - val_mae: 0.3612 - learning_rate: 5.0000e-04
Epoch 16/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.3205 - mae: 0.1036 - val_loss: 1.2465 - val_mae: 0.3825 - learning_rate: 5.0000e-04
Epoch 17/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.3200 - mae: 0.1035 - val_loss: 1.2651 - val_mae: 0.3881 - learning_rate: 5.0000e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.3053 - mae: 0.0988 - val_loss: 1.4128 - val_mae: 0.4310 - learning_rate: 5.0000e-04
Epoch 19/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 57ms/step - loss: 0.3005 - mae: 0.0973 - val_loss: 1.2247 - val_mae: 0.3759 - learning_rate: 5.0000e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2881 - mae: 0.0934
Epoch 20: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.2883 - mae: 0.0934 - val_loss: 1.3824 - val_mae: 0.4219 - learning_rate: 5.0000e-04
Epoch 21/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.2801 - mae: 0.0909 - val_loss: 1.2078 - val_mae: 0.3717 - learning_rate: 2.5000e-04
Epoch 22/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - loss: 0.2789 - mae: 0.0906 - val_loss: 1.1616 - val_mae: 0.3586 - learning_rate: 2.5000e-04
Epoch 23/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.2790 - mae: 0.0906 - val_loss: 1.1381 - val_mae: 0.3518 - learning_rate: 2.5000e-04
Epoch 24/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 61ms/step - loss: 0.2695 - mae: 0.0876 - val_loss: 1.1672 - val_mae: 0.3601 - learning_rate: 2.5000e-04
Epoch 25/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - loss: 0.2599 - mae: 0.0845 - val_loss: 1.0879 - val_mae: 0.3370 - learning_rate: 2.5000e-04
Epoch 26/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.2658 - mae: 0.0865 - val_loss: 1.1041 - val_mae: 0.3416 - learning_rate: 2.5000e-04
Epoch 27/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.2561 - mae: 0.0834 - val_loss: 1.1729 - val_mae: 0.3624 - learning_rate: 2.5000e-04
Epoch 28/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.2548 - mae: 0.0829 - val_loss: 1.0642 - val_mae: 0.3301 - learning_rate: 2.5000e-04
Epoch 29/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2415 - mae: 0.0788 - val_loss: 1.0396 - val_mae: 0.3230 - learning_rate: 2.5000e-04
Epoch 30/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.2416 - mae: 0.0787 - val_loss: 1.0773 - val_mae: 0.3340 - learning_rate: 2.5000e-04
Restoring model weights from the end of the best epoch: 29.
  {'Model': 'iTransformer', 'Horizon': 20, 'MAE': 12.5963, 'RMSE': 20.1559, 'RMSE($)': 20.1559, 'MAPE(%)': 12.6546, 'SMAPE(%)': 13.0461, 'R2': -0.2534, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 5s 24ms/step - loss: 1.6987 - mae: 0.4946 - val_loss: 0.5942 - val_mae: 0.1893 - learning_rate: 0.0010
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.5549 - mae: 0.1758 - val_loss: 0.6503 - val_mae: 0.2064 - learning_rate: 0.0010
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.4745 - mae: 0.1514 - val_loss: 0.5991 - val_mae: 0.1899 - learning_rate: 0.0010
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.3980 - mae: 0.1277 - val_loss: 0.6195 - val_mae: 0.1964 - learning_rate: 0.0010
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.3890 - mae: 0.1248 - val_loss: 0.5840 - val_mae: 0.1859 - learning_rate: 0.0010
Epoch 6/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.3965 - mae: 0.1272 - val_loss: 0.6862 - val_mae: 0.2172 - learning_rate: 0.0010
Epoch 7/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.3720 - mae: 0.1196 - val_loss: 0.5919 - val_mae: 0.1888 - learning_rate: 0.0010
Epoch 8/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.3633 - mae: 0.1169 - val_loss: 0.5975 - val_mae: 0.1900 - learning_rate: 0.0010
Epoch 9/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.3437 - mae: 0.1107 - val_loss: 0.6529 - val_mae: 0.2075 - learning_rate: 0.0010
Epoch 10/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.3445 - mae: 0.1110
Epoch 10: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.3447 - mae: 0.1110 - val_loss: 0.6818 - val_mae: 0.2163 - learning_rate: 0.0010
Epoch 11/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.3406 - mae: 0.1097 - val_loss: 0.6299 - val_mae: 0.2000 - learning_rate: 5.0000e-04
Epoch 12/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.3137 - mae: 0.1013 - val_loss: 0.6619 - val_mae: 0.2101 - learning_rate: 5.0000e-04
Epoch 13/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.3195 - mae: 0.1031 - val_loss: 0.5776 - val_mae: 0.1845 - learning_rate: 5.0000e-04
Epoch 14/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.3124 - mae: 0.1009 - val_loss: 0.5954 - val_mae: 0.1898 - learning_rate: 5.0000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.2995 - mae: 0.0968 - val_loss: 0.6165 - val_mae: 0.1962 - learning_rate: 5.0000e-04
Epoch 16/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.3164 - mae: 0.1021 - val_loss: 0.6612 - val_mae: 0.2098 - learning_rate: 5.0000e-04
Epoch 17/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.3119 - mae: 0.1007 - val_loss: 0.6266 - val_mae: 0.1995 - learning_rate: 5.0000e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.2819 - mae: 0.0913
Epoch 18: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.2821 - mae: 0.0914 - val_loss: 0.6351 - val_mae: 0.2021 - learning_rate: 5.0000e-04
Epoch 19/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.3082 - mae: 0.0994 - val_loss: 0.6120 - val_mae: 0.1949 - learning_rate: 2.5000e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.2887 - mae: 0.0933 - val_loss: 0.6384 - val_mae: 0.2031 - learning_rate: 2.5000e-04
Epoch 21/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.2845 - mae: 0.0921 - val_loss: 0.6676 - val_mae: 0.2124 - learning_rate: 2.5000e-04
Epoch 22/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.2838 - mae: 0.0918 - val_loss: 0.6830 - val_mae: 0.2171 - learning_rate: 2.5000e-04
Epoch 23/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.2862 - mae: 0.0925
Epoch 23: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.2864 - mae: 0.0926 - val_loss: 0.6071 - val_mae: 0.1935 - learning_rate: 2.5000e-04
Epoch 24/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.2728 - mae: 0.0884 - val_loss: 0.6195 - val_mae: 0.1975 - learning_rate: 1.2500e-04
Epoch 25/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.2798 - mae: 0.0906 - val_loss: 0.6357 - val_mae: 0.2024 - learning_rate: 1.2500e-04
Epoch 26/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.2679 - mae: 0.0868 - val_loss: 0.6318 - val_mae: 0.2012 - learning_rate: 1.2500e-04
Epoch 27/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.2740 - mae: 0.0887 - val_loss: 0.6426 - val_mae: 0.2047 - learning_rate: 1.2500e-04
Epoch 28/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.2653 - mae: 0.0859
Epoch 28: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.2654 - mae: 0.0859 - val_loss: 0.6462 - val_mae: 0.2058 - learning_rate: 1.2500e-04
Epoch 29/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.2644 - mae: 0.0857 - val_loss: 0.6430 - val_mae: 0.2048 - learning_rate: 6.2500e-05
Epoch 30/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.2669 - mae: 0.0864 - val_loss: 0.6502 - val_mae: 0.2070 - learning_rate: 6.2500e-05
Restoring model weights from the end of the best epoch: 13.
  {'Model': 'GUMNet-Lite', 'Horizon': 20, 'MAE': 11.956, 'RMSE': 18.4918, 'RMSE($)': 18.4918, 'MAPE(%)': 12.3671, 'SMAPE(%)': 12.6297, 'R2': -0.055, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - loss: 1.1319 - mae: 0.3400 - val_loss: 0.4007 - val_mae: 0.1291 - learning_rate: 0.0010
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.4948 - mae: 0.1575 - val_loss: 0.4354 - val_mae: 0.1399 - learning_rate: 0.0010
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.4152 - mae: 0.1332 - val_loss: 0.4324 - val_mae: 0.1392 - learning_rate: 0.0010
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.3887 - mae: 0.1251 - val_loss: 0.4835 - val_mae: 0.1550 - learning_rate: 0.0010
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.3598 - mae: 0.1159 - val_loss: 0.4905 - val_mae: 0.1573 - learning_rate: 0.0010
Epoch 6/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.3518 - mae: 0.1135
Epoch 6: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.3519 - mae: 0.1135 - val_loss: 0.5727 - val_mae: 0.1820 - learning_rate: 0.0010
Epoch 7/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.3227 - mae: 0.1043 - val_loss: 0.5174 - val_mae: 0.1656 - learning_rate: 5.0000e-04
Epoch 8/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.3074 - mae: 0.0997 - val_loss: 0.5738 - val_mae: 0.1831 - learning_rate: 5.0000e-04
Epoch 9/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.3000 - mae: 0.0973 - val_loss: 0.5674 - val_mae: 0.1810 - learning_rate: 5.0000e-04
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.2894 - mae: 0.0940 - val_loss: 0.5613 - val_mae: 0.1789 - learning_rate: 5.0000e-04
Epoch 11/30
55/57 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.2920 - mae: 0.0948
Epoch 11: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 27ms/step - loss: 0.2919 - mae: 0.0947 - val_loss: 0.5333 - val_mae: 0.1704 - learning_rate: 5.0000e-04
Epoch 12/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.2644 - mae: 0.0860 - val_loss: 0.5864 - val_mae: 0.1869 - learning_rate: 2.5000e-04
Epoch 13/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.2575 - mae: 0.0838 - val_loss: 0.5559 - val_mae: 0.1775 - learning_rate: 2.5000e-04
Epoch 14/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.2554 - mae: 0.0831 - val_loss: 0.5834 - val_mae: 0.1858 - learning_rate: 2.5000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.2619 - mae: 0.0853 - val_loss: 0.5482 - val_mae: 0.1749 - learning_rate: 2.5000e-04
Epoch 16/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.2556 - mae: 0.0832
Epoch 16: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.2556 - mae: 0.0832 - val_loss: 0.5356 - val_mae: 0.1712 - learning_rate: 2.5000e-04
Epoch 17/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.2500 - mae: 0.0814 - val_loss: 0.5492 - val_mae: 0.1753 - learning_rate: 1.2500e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.2508 - mae: 0.0816 - val_loss: 0.5551 - val_mae: 0.1770 - learning_rate: 1.2500e-04
Epoch 19/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.2396 - mae: 0.0781 - val_loss: 0.5353 - val_mae: 0.1709 - learning_rate: 1.2500e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2411 - mae: 0.0786 - val_loss: 0.5568 - val_mae: 0.1776 - learning_rate: 1.2500e-04
Epoch 21/30
55/57 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.2441 - mae: 0.0795
Epoch 21: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.2442 - mae: 0.0796 - val_loss: 0.5503 - val_mae: 0.1755 - learning_rate: 1.2500e-04
Epoch 21: early stopping
Restoring model weights from the end of the best epoch: 1.

Seed set to 1

  {'Model': 'GUMNet-Ultra', 'Horizon': 20, 'MAE': 8.8756, 'RMSE': 15.6793, 'RMSE($)': 15.6793, 'MAPE(%)': 8.9295, 'SMAPE(%)': 9.2951, 'R2': 0.2415, 'MAPE_thr(%)': 5.0, 'RMSE_thr($)': 2.0, 'Pass': False}
  PatchTST/TFT skipped: Exception('PatchTST does not support historical exogenous variables.')
  [H=20] done in 233.0s
======================================================================
HORIZON H = 30
======================================================================
  {'Model': 'ARIMAX', 'Horizon': 30, 'MAE': 4.1985, 'RMSE': 6.9632, 'RMSE($)': 6.9632, 'MAPE(%)': 4.3397, 'SMAPE(%)': 4.2629, 'R2': 0.8572, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'SARIMA', 'Horizon': 30, 'MAE': 8.5796, 'RMSE': 18.1749, 'RMSE($)': 18.1749, 'MAPE(%)': 8.0477, 'SMAPE(%)': 8.8458, 'R2': 0.0272, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
H=30 OOF fold 1: 2018-03-02 -> 2020-04-22 | MAE=2.8651
H=30 OOF fold 2: 2020-04-23 -> 2022-06-09 | MAE=5.1132
H=30 OOF fold 3: 2022-06-10 -> 2024-07-29 | MAE=7.0304
H=30 Jump-Gated ARIMAX-CatBoost MAPE=5.0640% | MAE=4.9834
  {'Model': 'Jump-Gated ARIMAX-CatBoost', 'Horizon': 30, 'MAE': 4.9834, 'RMSE': 9.2263, 'RMSE($)': 9.2263, 'MAPE(%)': 5.064, 'SMAPE(%)': 4.9402, 'R2': 0.7342, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'Ridge (Linear)', 'Horizon': 30, 'MAE': 10.157, 'RMSE': 20.3332, 'RMSE($)': 20.3332, 'MAPE(%)': 9.6942, 'SMAPE(%)': 9.5842, 'R2': -0.2911, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LightGBM', 'Horizon': 30, 'MAE': 9.3202, 'RMSE': 17.4758, 'RMSE($)': 17.4758, 'MAPE(%)': 9.0389, 'SMAPE(%)': 9.6594, 'R2': 0.0463, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LSTM', 'Horizon': 30, 'MAE': 10.9441, 'RMSE': 21.6421, 'RMSE($)': 21.6421, 'MAPE(%)': 10.4672, 'SMAPE(%)': 12.029, 'R2': -0.4418, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 10s 45ms/step - loss: 0.9539 - mae: 0.2909 - val_loss: 1.8685 - val_mae: 0.5565 - learning_rate: 5.0000e-04
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.6325 - mae: 0.1987 - val_loss: 1.6947 - val_mae: 0.5070 - learning_rate: 5.0000e-04
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.5802 - mae: 0.1832 - val_loss: 1.6089 - val_mae: 0.4828 - learning_rate: 5.0000e-04
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.5458 - mae: 0.1725 - val_loss: 1.5169 - val_mae: 0.4577 - learning_rate: 5.0000e-04
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.5230 - mae: 0.1656 - val_loss: 1.5014 - val_mae: 0.4540 - learning_rate: 5.0000e-04
Epoch 6/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.5049 - mae: 0.1602 - val_loss: 1.4161 - val_mae: 0.4302 - learning_rate: 5.0000e-04
Epoch 7/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.4878 - mae: 0.1549 - val_loss: 1.1246 - val_mae: 0.3454 - learning_rate: 5.0000e-04
Epoch 8/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - loss: 0.4780 - mae: 0.1517 - val_loss: 1.0706 - val_mae: 0.3311 - learning_rate: 5.0000e-04
Epoch 9/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.4583 - mae: 0.1458 - val_loss: 1.2862 - val_mae: 0.3930 - learning_rate: 5.0000e-04
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.4404 - mae: 0.1405 - val_loss: 1.2579 - val_mae: 0.3848 - learning_rate: 5.0000e-04
Epoch 11/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.4404 - mae: 0.1403 - val_loss: 1.2025 - val_mae: 0.3691 - learning_rate: 5.0000e-04
Epoch 12/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.4298 - mae: 0.1370 - val_loss: 1.1643 - val_mae: 0.3594 - learning_rate: 5.0000e-04
Epoch 13/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.4143 - mae: 0.1324
Epoch 13: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.4141 - mae: 0.1324 - val_loss: 1.2706 - val_mae: 0.3895 - learning_rate: 5.0000e-04
Epoch 14/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.3956 - mae: 0.1265 - val_loss: 1.2082 - val_mae: 0.3727 - learning_rate: 2.5000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.3769 - mae: 0.1207 - val_loss: 1.2326 - val_mae: 0.3794 - learning_rate: 2.5000e-04
Epoch 16/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.3800 - mae: 0.1218 - val_loss: 1.2475 - val_mae: 0.3842 - learning_rate: 2.5000e-04
Epoch 17/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.3597 - mae: 0.1153 - val_loss: 1.2940 - val_mae: 0.3971 - learning_rate: 2.5000e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.3551 - mae: 0.1141
Epoch 18: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.3550 - mae: 0.1141 - val_loss: 1.1707 - val_mae: 0.3615 - learning_rate: 2.5000e-04
Epoch 19/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.3506 - mae: 0.1128 - val_loss: 1.3675 - val_mae: 0.4179 - learning_rate: 1.2500e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.3409 - mae: 0.1097 - val_loss: 1.4300 - val_mae: 0.4360 - learning_rate: 1.2500e-04
Epoch 21/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.3372 - mae: 0.1085 - val_loss: 1.4210 - val_mae: 0.4332 - learning_rate: 1.2500e-04
Epoch 22/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.3299 - mae: 0.1063 - val_loss: 1.3252 - val_mae: 0.4062 - learning_rate: 1.2500e-04
Epoch 23/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.3342 - mae: 0.1077
Epoch 23: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.3341 - mae: 0.1076 - val_loss: 1.4007 - val_mae: 0.4278 - learning_rate: 1.2500e-04
Epoch 24/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.3191 - mae: 0.1029 - val_loss: 1.4645 - val_mae: 0.4460 - learning_rate: 6.2500e-05
Epoch 25/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - loss: 0.3113 - mae: 0.1005 - val_loss: 1.4289 - val_mae: 0.4358 - learning_rate: 6.2500e-05
Epoch 26/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.3070 - mae: 0.0991 - val_loss: 1.3866 - val_mae: 0.4238 - learning_rate: 6.2500e-05
Epoch 27/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - loss: 0.3078 - mae: 0.0993 - val_loss: 1.4596 - val_mae: 0.4444 - learning_rate: 6.2500e-05
Epoch 28/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.3021 - mae: 0.0976
Epoch 28: ReduceLROnPlateau reducing learning rate to 3.125000148429535e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - loss: 0.3021 - mae: 0.0976 - val_loss: 1.4949 - val_mae: 0.4540 - learning_rate: 6.2500e-05
Epoch 28: early stopping
Restoring model weights from the end of the best epoch: 8.
  {'Model': 'iTransformer', 'Horizon': 30, 'MAE': 13.6775, 'RMSE': 22.9434, 'RMSE($)': 22.9434, 'MAPE(%)': 13.5192, 'SMAPE(%)': 14.4518, 'R2': -0.6204, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - loss: 1.7914 - mae: 0.5186 - val_loss: 0.8296 - val_mae: 0.2600 - learning_rate: 0.0010
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.6119 - mae: 0.1928 - val_loss: 0.6538 - val_mae: 0.2062 - learning_rate: 0.0010
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.4637 - mae: 0.1479 - val_loss: 0.7672 - val_mae: 0.2404 - learning_rate: 0.0010
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.4163 - mae: 0.1333 - val_loss: 0.7440 - val_mae: 0.2344 - learning_rate: 0.0010
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.4154 - mae: 0.1331 - val_loss: 0.8141 - val_mae: 0.2547 - learning_rate: 0.0010
Epoch 6/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.3808 - mae: 0.1224 - val_loss: 0.7119 - val_mae: 0.2237 - learning_rate: 0.0010
Epoch 7/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.3813 - mae: 0.1223
Epoch 7: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.3811 - mae: 0.1222 - val_loss: 0.7569 - val_mae: 0.2383 - learning_rate: 0.0010
Epoch 8/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.3651 - mae: 0.1174 - val_loss: 0.7577 - val_mae: 0.2382 - learning_rate: 5.0000e-04
Epoch 9/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.3379 - mae: 0.1089 - val_loss: 0.7350 - val_mae: 0.2312 - learning_rate: 5.0000e-04
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.3227 - mae: 0.1041 - val_loss: 0.8018 - val_mae: 0.2517 - learning_rate: 5.0000e-04
Epoch 11/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.3264 - mae: 0.1051 - val_loss: 0.6985 - val_mae: 0.2206 - learning_rate: 5.0000e-04
Epoch 12/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.3140 - mae: 0.1013
Epoch 12: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.3144 - mae: 0.1015 - val_loss: 0.8207 - val_mae: 0.2569 - learning_rate: 5.0000e-04
Epoch 13/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.3255 - mae: 0.1049 - val_loss: 0.7867 - val_mae: 0.2468 - learning_rate: 2.5000e-04
Epoch 14/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.3063 - mae: 0.0989 - val_loss: 0.7487 - val_mae: 0.2357 - learning_rate: 2.5000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.2962 - mae: 0.0958 - val_loss: 0.7501 - val_mae: 0.2359 - learning_rate: 2.5000e-04
Epoch 16/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.2980 - mae: 0.0963 - val_loss: 0.7635 - val_mae: 0.2399 - learning_rate: 2.5000e-04
Epoch 17/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.3027 - mae: 0.0978
Epoch 17: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - loss: 0.3027 - mae: 0.0978 - val_loss: 0.8034 - val_mae: 0.2518 - learning_rate: 2.5000e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.2960 - mae: 0.0957 - val_loss: 0.7822 - val_mae: 0.2457 - learning_rate: 1.2500e-04
Epoch 19/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.3035 - mae: 0.0979 - val_loss: 0.7685 - val_mae: 0.2415 - learning_rate: 1.2500e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step - loss: 0.2919 - mae: 0.0943 - val_loss: 0.7944 - val_mae: 0.2491 - learning_rate: 1.2500e-04
Epoch 21/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.2959 - mae: 0.0957 - val_loss: 0.7794 - val_mae: 0.2449 - learning_rate: 1.2500e-04
Epoch 22/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.2935 - mae: 0.0949
Epoch 22: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 0.2936 - mae: 0.0949 - val_loss: 0.7620 - val_mae: 0.2396 - learning_rate: 1.2500e-04
Epoch 22: early stopping
Restoring model weights from the end of the best epoch: 2.
  {'Model': 'GUMNet-Lite', 'Horizon': 30, 'MAE': 11.0275, 'RMSE': 20.173, 'RMSE($)': 20.173, 'MAPE(%)': 10.6063, 'SMAPE(%)': 12.0555, 'R2': -0.2527, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 26s 92ms/step - loss: 1.2300 - mae: 0.3688 - val_loss: 0.8334 - val_mae: 0.2621 - learning_rate: 0.0010
Epoch 2/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 68ms/step - loss: 0.5267 - mae: 0.1672 - val_loss: 0.6228 - val_mae: 0.1972 - learning_rate: 0.0010
Epoch 3/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.4433 - mae: 0.1416 - val_loss: 0.6508 - val_mae: 0.2057 - learning_rate: 0.0010
Epoch 4/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.4116 - mae: 0.1318 - val_loss: 0.6809 - val_mae: 0.2151 - learning_rate: 0.0010
Epoch 5/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - loss: 0.3927 - mae: 0.1261 - val_loss: 0.7377 - val_mae: 0.2322 - learning_rate: 0.0010
Epoch 6/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.3747 - mae: 0.1206 - val_loss: 0.6202 - val_mae: 0.1964 - learning_rate: 0.0010
Epoch 7/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - loss: 0.3497 - mae: 0.1130 - val_loss: 0.7298 - val_mae: 0.2299 - learning_rate: 0.0010
Epoch 8/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - loss: 0.3368 - mae: 0.1088 - val_loss: 0.8627 - val_mae: 0.2695 - learning_rate: 0.0010
Epoch 9/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - loss: 0.3281 - mae: 0.1061 - val_loss: 0.7044 - val_mae: 0.2220 - learning_rate: 0.0010
Epoch 10/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - loss: 0.2949 - mae: 0.0957 - val_loss: 0.6741 - val_mae: 0.2128 - learning_rate: 0.0010
Epoch 11/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.2845 - mae: 0.0924
Epoch 11: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2845 - mae: 0.0924 - val_loss: 0.7617 - val_mae: 0.2392 - learning_rate: 0.0010
Epoch 12/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.2655 - mae: 0.0863 - val_loss: 0.7416 - val_mae: 0.2329 - learning_rate: 5.0000e-04
Epoch 13/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2596 - mae: 0.0845 - val_loss: 0.7299 - val_mae: 0.2293 - learning_rate: 5.0000e-04
Epoch 14/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.2602 - mae: 0.0847 - val_loss: 0.7368 - val_mae: 0.2314 - learning_rate: 5.0000e-04
Epoch 15/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.2555 - mae: 0.0832 - val_loss: 0.7334 - val_mae: 0.2306 - learning_rate: 5.0000e-04
Epoch 16/30
55/57 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2362 - mae: 0.0770
Epoch 16: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.2364 - mae: 0.0771 - val_loss: 0.6991 - val_mae: 0.2203 - learning_rate: 5.0000e-04
Epoch 17/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - loss: 0.2319 - mae: 0.0756 - val_loss: 0.7119 - val_mae: 0.2243 - learning_rate: 2.5000e-04
Epoch 18/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - loss: 0.2414 - mae: 0.0786 - val_loss: 0.7179 - val_mae: 0.2260 - learning_rate: 2.5000e-04
Epoch 19/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - loss: 0.2370 - mae: 0.0772 - val_loss: 0.7238 - val_mae: 0.2278 - learning_rate: 2.5000e-04
Epoch 20/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - loss: 0.2272 - mae: 0.0742 - val_loss: 0.7365 - val_mae: 0.2317 - learning_rate: 2.5000e-04
Epoch 21/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.2220 - mae: 0.0725
Epoch 21: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - loss: 0.2220 - mae: 0.0725 - val_loss: 0.7606 - val_mae: 0.2390 - learning_rate: 2.5000e-04
Epoch 22/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.2304 - mae: 0.0751 - val_loss: 0.7248 - val_mae: 0.2281 - learning_rate: 1.2500e-04
Epoch 23/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - loss: 0.2148 - mae: 0.0702 - val_loss: 0.7505 - val_mae: 0.2359 - learning_rate: 1.2500e-04
Epoch 24/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.2161 - mae: 0.0705 - val_loss: 0.7650 - val_mae: 0.2403 - learning_rate: 1.2500e-04
Epoch 25/30
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2209 - mae: 0.0721 - val_loss: 0.7383 - val_mae: 0.2323 - learning_rate: 1.2500e-04
Epoch 26/30
56/57 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2152 - mae: 0.0703
Epoch 26: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
57/57 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - loss: 0.2153 - mae: 0.0703 - val_loss: 0.7504 - val_mae: 0.2361 - learning_rate: 1.2500e-04
Epoch 26: early stopping
Restoring model weights from the end of the best epoch: 6.

Seed set to 1

  {'Model': 'GUMNet-Ultra', 'Horizon': 30, 'MAE': 12.3398, 'RMSE': 20.3316, 'RMSE($)': 20.3316, 'MAPE(%)': 12.5847, 'SMAPE(%)': 13.9785, 'R2': -0.2725, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  PatchTST/TFT skipped: Exception('PatchTST does not support historical exogenous variables.')
  [H=30] done in 289.8s
======================================================================
HORIZON H = 60
======================================================================
  {'Model': 'ARIMAX', 'Horizon': 60, 'MAE': 3.7506, 'RMSE': 5.1157, 'RMSE($)': 5.1157, 'MAPE(%)': 4.1664, 'SMAPE(%)': 4.1186, 'R2': 0.928, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'SARIMA', 'Horizon': 60, 'MAE': 10.9924, 'RMSE': 22.4086, 'RMSE($)': 22.4086, 'MAPE(%)': 9.9718, 'SMAPE(%)': 11.3846, 'R2': -0.382, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
H=60 OOF fold 1: 2018-03-22 -> 2020-05-07 | MAE=3.9968
H=60 OOF fold 2: 2020-05-08 -> 2022-06-20 | MAE=7.1781
H=60 OOF fold 3: 2022-06-21 -> 2024-08-01 | MAE=7.1871
H=60 Jump-Gated ARIMAX-CatBoost MAPE=5.4410% | MAE=4.8030
  {'Model': 'Jump-Gated ARIMAX-CatBoost', 'Horizon': 60, 'MAE': 4.803, 'RMSE': 5.7508, 'RMSE($)': 5.7508, 'MAPE(%)': 5.441, 'SMAPE(%)': 5.4958, 'R2': 0.8973, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'Ridge (Linear)', 'Horizon': 60, 'MAE': 9.7696, 'RMSE': 19.1115, 'RMSE($)': 19.1115, 'MAPE(%)': 9.0596, 'SMAPE(%)': 10.2188, 'R2': -0.134, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LightGBM', 'Horizon': 60, 'MAE': 12.7022, 'RMSE': 20.8011, 'RMSE($)': 20.8011, 'MAPE(%)': 12.8031, 'SMAPE(%)': 13.3254, 'R2': -0.3434, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  {'Model': 'LSTM', 'Horizon': 60, 'MAE': 16.4406, 'RMSE': 28.3382, 'RMSE($)': 28.3382, 'MAPE(%)': 16.0541, 'SMAPE(%)': 18.9576, 'R2': -1.4406, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 10s 46ms/step - loss: 1.0852 - mae: 0.3270 - val_loss: 1.7929 - val_mae: 0.5343 - learning_rate: 5.0000e-04
Epoch 2/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.7175 - mae: 0.2241 - val_loss: 1.5261 - val_mae: 0.4615 - learning_rate: 5.0000e-04
Epoch 3/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.6729 - mae: 0.2106 - val_loss: 1.5531 - val_mae: 0.4687 - learning_rate: 5.0000e-04
Epoch 4/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.6289 - mae: 0.1973 - val_loss: 1.5508 - val_mae: 0.4692 - learning_rate: 5.0000e-04
Epoch 5/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.5953 - mae: 0.1870 - val_loss: 1.4506 - val_mae: 0.4408 - learning_rate: 5.0000e-04
Epoch 6/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.5639 - mae: 0.1778 - val_loss: 1.4736 - val_mae: 0.4480 - learning_rate: 5.0000e-04
Epoch 7/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.5273 - mae: 0.1669 - val_loss: 1.2151 - val_mae: 0.3743 - learning_rate: 5.0000e-04
Epoch 8/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.4930 - mae: 0.1563 - val_loss: 1.2605 - val_mae: 0.3880 - learning_rate: 5.0000e-04
Epoch 9/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.4592 - mae: 0.1460 - val_loss: 1.3108 - val_mae: 0.4031 - learning_rate: 5.0000e-04
Epoch 10/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.4538 - mae: 0.1444 - val_loss: 1.2657 - val_mae: 0.3882 - learning_rate: 5.0000e-04
Epoch 11/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.4546 - mae: 0.1445 - val_loss: 1.0787 - val_mae: 0.3331 - learning_rate: 5.0000e-04
Epoch 12/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.4049 - mae: 0.1294 - val_loss: 1.3201 - val_mae: 0.4037 - learning_rate: 5.0000e-04
Epoch 13/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.3863 - mae: 0.1237 - val_loss: 1.3772 - val_mae: 0.4200 - learning_rate: 5.0000e-04
Epoch 14/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.3832 - mae: 0.1228 - val_loss: 1.2501 - val_mae: 0.3828 - learning_rate: 5.0000e-04
Epoch 15/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.3704 - mae: 0.1188 - val_loss: 1.1097 - val_mae: 0.3420 - learning_rate: 5.0000e-04
Epoch 16/30
55/56 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.3392 - mae: 0.1091
Epoch 16: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.3391 - mae: 0.1090 - val_loss: 1.1706 - val_mae: 0.3602 - learning_rate: 5.0000e-04
Epoch 17/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.3257 - mae: 0.1048 - val_loss: 1.2658 - val_mae: 0.3860 - learning_rate: 2.5000e-04
Epoch 18/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.3162 - mae: 0.1019 - val_loss: 1.3800 - val_mae: 0.4192 - learning_rate: 2.5000e-04
Epoch 19/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.3053 - mae: 0.0985 - val_loss: 1.1860 - val_mae: 0.3632 - learning_rate: 2.5000e-04
Epoch 20/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step - loss: 0.3049 - mae: 0.0983 - val_loss: 1.4504 - val_mae: 0.4384 - learning_rate: 2.5000e-04
Epoch 21/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 6s 62ms/step - loss: 0.3011 - mae: 0.0972 - val_loss: 0.9744 - val_mae: 0.3004 - learning_rate: 2.5000e-04
Epoch 22/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 61ms/step - loss: 0.3043 - mae: 0.0982 - val_loss: 1.1346 - val_mae: 0.3477 - learning_rate: 2.5000e-04
Epoch 23/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 57ms/step - loss: 0.2813 - mae: 0.0910 - val_loss: 1.0641 - val_mae: 0.3269 - learning_rate: 2.5000e-04
Epoch 24/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - loss: 0.2796 - mae: 0.0905 - val_loss: 0.8877 - val_mae: 0.2751 - learning_rate: 2.5000e-04
Epoch 25/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.2895 - mae: 0.0936 - val_loss: 1.0874 - val_mae: 0.3332 - learning_rate: 2.5000e-04
Epoch 26/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 54ms/step - loss: 0.2812 - mae: 0.0911 - val_loss: 1.0252 - val_mae: 0.3154 - learning_rate: 2.5000e-04
Epoch 27/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.2740 - mae: 0.0887 - val_loss: 0.9702 - val_mae: 0.2994 - learning_rate: 2.5000e-04
Epoch 28/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 54ms/step - loss: 0.2619 - mae: 0.0850 - val_loss: 1.3227 - val_mae: 0.4017 - learning_rate: 2.5000e-04
Epoch 29/30
55/56 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.2596 - mae: 0.0842
Epoch 29: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.2596 - mae: 0.0842 - val_loss: 1.0869 - val_mae: 0.3340 - learning_rate: 2.5000e-04
Epoch 30/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 54ms/step - loss: 0.2527 - mae: 0.0820 - val_loss: 1.0667 - val_mae: 0.3274 - learning_rate: 1.2500e-04
Restoring model weights from the end of the best epoch: 24.
  {'Model': 'iTransformer', 'Horizon': 60, 'MAE': 16.6548, 'RMSE': 29.2886, 'RMSE($)': 29.2886, 'MAPE(%)': 16.0514, 'SMAPE(%)': 18.0405, 'R2': -1.607, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 15s 87ms/step - loss: 1.7949 - mae: 0.5198 - val_loss: 1.1055 - val_mae: 0.3429 - learning_rate: 0.0010
Epoch 2/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step - loss: 0.5942 - mae: 0.1872 - val_loss: 0.9855 - val_mae: 0.3058 - learning_rate: 0.0010
Epoch 3/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 53ms/step - loss: 0.5005 - mae: 0.1590 - val_loss: 0.8199 - val_mae: 0.2564 - learning_rate: 0.0010
Epoch 4/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.4428 - mae: 0.1413 - val_loss: 0.8273 - val_mae: 0.2587 - learning_rate: 0.0010
Epoch 5/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.4069 - mae: 0.1302 - val_loss: 0.7165 - val_mae: 0.2251 - learning_rate: 0.0010
Epoch 6/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - loss: 0.3844 - mae: 0.1234 - val_loss: 0.9374 - val_mae: 0.2935 - learning_rate: 0.0010
Epoch 7/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 4s 60ms/step - loss: 0.3784 - mae: 0.1215 - val_loss: 0.7207 - val_mae: 0.2282 - learning_rate: 0.0010
Epoch 8/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - loss: 0.3758 - mae: 0.1207 - val_loss: 0.7300 - val_mae: 0.2308 - learning_rate: 0.0010
Epoch 9/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.3586 - mae: 0.1153 - val_loss: 0.9402 - val_mae: 0.2943 - learning_rate: 0.0010
Epoch 10/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.3336 - mae: 0.1076
Epoch 10: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step - loss: 0.3338 - mae: 0.1077 - val_loss: 0.7615 - val_mae: 0.2400 - learning_rate: 0.0010
Epoch 11/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - loss: 0.3297 - mae: 0.1064 - val_loss: 0.8476 - val_mae: 0.2668 - learning_rate: 5.0000e-04
Epoch 12/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - loss: 0.3102 - mae: 0.1002 - val_loss: 0.7976 - val_mae: 0.2515 - learning_rate: 5.0000e-04
Epoch 13/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.3139 - mae: 0.1013 - val_loss: 0.7626 - val_mae: 0.2408 - learning_rate: 5.0000e-04
Epoch 14/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.3217 - mae: 0.1036 - val_loss: 0.8305 - val_mae: 0.2614 - learning_rate: 5.0000e-04
Epoch 15/30
55/56 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.2923 - mae: 0.0947
Epoch 15: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - loss: 0.2924 - mae: 0.0947 - val_loss: 0.7544 - val_mae: 0.2384 - learning_rate: 5.0000e-04
Epoch 16/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.2999 - mae: 0.0969 - val_loss: 0.7756 - val_mae: 0.2447 - learning_rate: 2.5000e-04
Epoch 17/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.2875 - mae: 0.0930 - val_loss: 0.7724 - val_mae: 0.2435 - learning_rate: 2.5000e-04
Epoch 18/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.2814 - mae: 0.0912 - val_loss: 0.7897 - val_mae: 0.2489 - learning_rate: 2.5000e-04
Epoch 19/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.3097 - mae: 0.1000 - val_loss: 0.7967 - val_mae: 0.2510 - learning_rate: 2.5000e-04
Epoch 20/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.2844 - mae: 0.0921
Epoch 20: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.2844 - mae: 0.0921 - val_loss: 0.7932 - val_mae: 0.2501 - learning_rate: 2.5000e-04
Epoch 21/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.2786 - mae: 0.0902 - val_loss: 0.8027 - val_mae: 0.2530 - learning_rate: 1.2500e-04
Epoch 22/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.2754 - mae: 0.0891 - val_loss: 0.8001 - val_mae: 0.2523 - learning_rate: 1.2500e-04
Epoch 23/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - loss: 0.2792 - mae: 0.0904 - val_loss: 0.7921 - val_mae: 0.2499 - learning_rate: 1.2500e-04
Epoch 24/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - loss: 0.2836 - mae: 0.0916 - val_loss: 0.8139 - val_mae: 0.2564 - learning_rate: 1.2500e-04
Epoch 25/30
55/56 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.2760 - mae: 0.0893
Epoch 25: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - loss: 0.2762 - mae: 0.0894 - val_loss: 0.8040 - val_mae: 0.2533 - learning_rate: 1.2500e-04
Epoch 25: early stopping
Restoring model weights from the end of the best epoch: 5.
  {'Model': 'GUMNet-Lite', 'Horizon': 60, 'MAE': 15.9289, 'RMSE': 27.5929, 'RMSE($)': 27.5929, 'MAPE(%)': 15.5697, 'SMAPE(%)': 17.1971, 'R2': -1.3139, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
Epoch 1/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 1.2760 - mae: 0.3806 - val_loss: 0.6866 - val_mae: 0.2170 - learning_rate: 0.0010
Epoch 2/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.5708 - mae: 0.1801 - val_loss: 0.8026 - val_mae: 0.2522 - learning_rate: 0.0010
Epoch 3/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.4862 - mae: 0.1549 - val_loss: 0.8531 - val_mae: 0.2665 - learning_rate: 0.0010
Epoch 4/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.4305 - mae: 0.1376 - val_loss: 0.9271 - val_mae: 0.2878 - learning_rate: 0.0010
Epoch 5/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.3996 - mae: 0.1283 - val_loss: 1.0660 - val_mae: 0.3277 - learning_rate: 0.0010
Epoch 6/30
55/56 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.3568 - mae: 0.1152
Epoch 6: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - loss: 0.3568 - mae: 0.1152 - val_loss: 0.8908 - val_mae: 0.2755 - learning_rate: 0.0010
Epoch 7/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 5s 51ms/step - loss: 0.3527 - mae: 0.1137 - val_loss: 0.8557 - val_mae: 0.2651 - learning_rate: 5.0000e-04
Epoch 8/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - loss: 0.3259 - mae: 0.1055 - val_loss: 0.8262 - val_mae: 0.2567 - learning_rate: 5.0000e-04
Epoch 9/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - loss: 0.3143 - mae: 0.1018 - val_loss: 0.8750 - val_mae: 0.2717 - learning_rate: 5.0000e-04
Epoch 10/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - loss: 0.3071 - mae: 0.0995 - val_loss: 0.9035 - val_mae: 0.2801 - learning_rate: 5.0000e-04
Epoch 11/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2939 - mae: 0.0953
Epoch 11: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.2940 - mae: 0.0953 - val_loss: 0.8107 - val_mae: 0.2526 - learning_rate: 5.0000e-04
Epoch 12/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - loss: 0.2749 - mae: 0.0893 - val_loss: 0.9104 - val_mae: 0.2824 - learning_rate: 2.5000e-04
Epoch 13/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - loss: 0.2600 - mae: 0.0846 - val_loss: 0.8787 - val_mae: 0.2733 - learning_rate: 2.5000e-04
Epoch 14/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 5s 45ms/step - loss: 0.2632 - mae: 0.0856 - val_loss: 0.8175 - val_mae: 0.2550 - learning_rate: 2.5000e-04
Epoch 15/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.2626 - mae: 0.0854 - val_loss: 0.7739 - val_mae: 0.2419 - learning_rate: 2.5000e-04
Epoch 16/30
55/56 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.2616 - mae: 0.0851
Epoch 16: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.2616 - mae: 0.0851 - val_loss: 0.8075 - val_mae: 0.2518 - learning_rate: 2.5000e-04
Epoch 17/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.2520 - mae: 0.0820 - val_loss: 0.8155 - val_mae: 0.2544 - learning_rate: 1.2500e-04
Epoch 18/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.2465 - mae: 0.0803 - val_loss: 0.7946 - val_mae: 0.2483 - learning_rate: 1.2500e-04
Epoch 19/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.2545 - mae: 0.0828 - val_loss: 0.8107 - val_mae: 0.2531 - learning_rate: 1.2500e-04
Epoch 20/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.2437 - mae: 0.0794 - val_loss: 0.8485 - val_mae: 0.2644 - learning_rate: 1.2500e-04
Epoch 21/30
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.2468 - mae: 0.0804
Epoch 21: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.2468 - mae: 0.0803 - val_loss: 0.8174 - val_mae: 0.2552 - learning_rate: 1.2500e-04
Epoch 21: early stopping
Restoring model weights from the end of the best epoch: 1.

Seed set to 1

  {'Model': 'GUMNet-Ultra', 'Horizon': 60, 'MAE': 11.8844, 'RMSE': 21.7267, 'RMSE($)': 21.7267, 'MAPE(%)': 11.2516, 'SMAPE(%)': 12.8971, 'R2': -0.4346, 'MAPE_thr(%)': nan, 'RMSE_thr($)': 2.0, 'Pass': False}
  PatchTST/TFT skipped: Exception('PatchTST does not support historical exogenous variables.')
  [H=60] done in 350.8s

ALL HORIZONS DONE. rows: 63

## 8. Ket qua - bang + signal decay theo horizon

In [9]:
res_df = pd.DataFrame(results)
res_df.insert(0, "Target", TARGET)
target_csv = TARGET_RESULT_DIR / "multihorizon_results.csv"
res_df.to_csv(target_csv, index=False)

combined_path = ROOT / "results" / DATA_TAG / "multihorizon_results_all_targets_11.csv"
if combined_path.exists():
    previous_rows = pd.read_csv(combined_path)
    previous_rows = previous_rows[previous_rows["Target"] != TARGET]
    combined_rows = pd.concat([previous_rows, res_df], ignore_index=True)
else:
    combined_rows = res_df.copy()
combined_rows.to_csv(combined_path, index=False)

if TARGET == "MG95":
    res_df.drop(columns=["Target"]).to_csv(ROOT / "results" / DATA_TAG / "multihorizon_results_11.csv", index=False)

print("=== Full results (long) ===")
display(res_df)

# Pivot: metrics theo (Model x Horizon)
for met in ["R2", "MAPE(%)", "MAE", "RMSE", "RMSE($)", "SMAPE(%)"]:
    piv = res_df.pivot_table(index="Model", columns="Horizon", values=met)
    print(f"\n--- {met} (Model x Horizon) ---"); display(piv)

# --- Quality-standard check: MAPE<3% (H1-5), MAPE<5% (H10-20), RMSE($)<2 ---
qa = res_df[["Model", "Horizon", "MAPE(%)", "MAPE_thr(%)", "RMSE($)", "RMSE_thr($)", "Pass"]].copy()
print("\n=== Quality check vs standard (MAPE<3% H1-5 | MAPE<5% H10-20 | RMSE($)<2) ===")
display(qa)
pass_piv = res_df.pivot_table(index="Model", columns="Horizon", values="Pass", aggfunc="first")
print("\n--- Pass (Model x Horizon) ---"); display(pass_piv)
print(f"Models meeting standard: {int(res_df['Pass'].sum())}/{len(res_df)}")

print(f"Saved -> {target_csv}")
print(f"Updated -> {combined_path}")

=== Full results (long) ===

,Target,Model,Horizon,MAE,RMSE,RMSE($),MAPE(%),SMAPE(%),R2,MAPE_thr(%),RMSE_thr($),Pass
0,MG95,ARIMAX,1,0.9543,2.0175,2.0175,0.9639,0.9608,0.9872,3.0,2.0,False
1,MG95,SARIMA,1,1.5108,3.0496,3.0496,1.5540,1.5528,0.9709,3.0,2.0,False
2,MG95,Jump-Gated ARIMAX-CatBoost,1,1.0608,2.7247,2.7247,1.0239,1.0211,0.9767,3.0,2.0,False
3,MG95,Ridge (Linear),1,1.3958,2.8454,2.8454,1.4263,1.4276,0.9746,3.0,2.0,False
4,MG95,LightGBM,1,1.9601,3.6035,3.6035,2.0137,2.0422,0.9592,3.0,2.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...
58,MG95,LightGBM,60,12.7022,20.8011,20.8011,12.8031,13.3254,-0.3434,NaN,2.0,False
59,MG95,LSTM,60,16.4406,28.3382,28.3382,16.0541,18.9576,-1.4406,NaN,2.0,False
60,MG95,iTransformer,60,16.6548,29.2886,29.2886,16.0514,18.0405,-1.6070,NaN,2.0,False
61,MG95,GUMNet-Lite,60,15.9289,27.5929,27.5929,15.5697,17.1971,-1.3139,NaN,2.0,False
62,MG95,GUMNet-Ultra,60,11.8844,21.7267,21.7267,11.2516,12.8971,-0.4346,NaN,2.0,False

--- R2 (Model x Horizon) ---

Horizon,1,5,10,15,20,30,60
Model,,,,,,,
ARIMAX,0.9872,0.9526,0.9289,0.8958,0.8716,0.8572,0.9280
GUMNet-Lite,0.7027,0.5791,0.3628,0.1666,-0.0550,-0.2527,-1.3139
GUMNet-Ultra,0.8074,0.7023,0.4144,0.3581,0.2415,-0.2725,-0.4346
Jump-Gated ARIMAX-CatBoost,0.9767,0.9497,0.8899,0.8648,0.7734,0.7342,0.8973
LSTM,0.8357,0.5260,0.4251,0.3669,-0.0028,-0.4418,-1.4406
LightGBM,0.9592,0.8506,0.6386,0.3791,0.1513,0.0463,-0.3434
Ridge (Linear),0.9746,0.8361,0.5516,0.1949,-0.1843,-0.2911,-0.1340
SARIMA,0.9709,0.8518,0.6771,0.4644,0.2847,0.0272,-0.3820
iTransformer,0.5494,0.3122,0.0538,0.0764,-0.2534,-0.6204,-1.6070

--- MAPE(%) (Model x Horizon) ---

Horizon,1,5,10,15,20,30,60
Model,,,,,,,
ARIMAX,0.9639,2.1854,2.7975,3.4417,3.8345,4.3397,4.1664
GUMNet-Lite,5.1384,6.2457,8.3814,7.6250,12.3671,10.6063,15.5697
GUMNet-Ultra,5.1781,5.6176,7.9132,9.0427,8.9295,12.5847,11.2516
Jump-Gated ARIMAX-CatBoost,1.0239,2.2352,3.0188,3.6231,4.3699,5.0640,5.4410
LSTM,3.9658,6.7628,7.8811,8.6405,10.1972,10.4672,16.0541
LightGBM,2.0137,3.9524,5.4704,6.8966,9.1007,9.0389,12.8031
Ridge (Linear),1.4263,3.9371,5.8164,7.3314,8.8387,9.6942,9.0596
SARIMA,1.5540,3.8635,4.8296,5.7751,6.8330,8.0477,9.9718
iTransformer,5.3123,6.5300,8.5999,10.8965,12.6546,13.5192,16.0514

--- MAE (Model x Horizon) ---

Horizon,1,5,10,15,20,30,60
Model,,,,,,,
ARIMAX,0.9543,2.1357,2.7379,3.3789,3.7386,4.1985,3.7506
GUMNet-Lite,5.0667,6.2243,8.1450,7.8937,11.9560,11.0275,15.9289
GUMNet-Ultra,4.9087,5.4584,7.8783,8.6778,8.8756,12.3398,11.8844
Jump-Gated ARIMAX-CatBoost,1.0608,2.1905,3.0470,3.6204,4.3960,4.9834,4.8030
LSTM,3.9072,6.8251,7.8261,8.4622,10.2704,10.9441,16.4406
LightGBM,1.9601,3.8153,5.4593,7.0923,9.1808,9.3202,12.7022
Ridge (Linear),1.3958,3.8534,5.9520,7.7045,9.4052,10.1570,9.7696
SARIMA,1.5108,3.7698,4.8785,5.9890,7.1636,8.5796,10.9924
iTransformer,5.7601,7.0743,9.1345,10.7986,12.5963,13.6775,16.6548

--- RMSE (Model x Horizon) ---

Horizon,1,5,10,15,20,30,60
Model,,,,,,,
ARIMAX,2.0175,3.9035,4.8061,5.8498,6.5276,6.9632,5.1157
GUMNet-Lite,9.7570,11.6205,14.3253,16.4001,18.4918,20.1730,27.5929
GUMNet-Ultra,7.8533,9.7735,13.7337,14.3927,15.6793,20.3316,21.7267
Jump-Gated ARIMAX-CatBoost,2.7247,4.0083,5.9280,6.5730,8.5110,9.2263,5.7508
LSTM,7.2541,12.3324,13.6081,14.2932,18.0289,21.6421,28.3382
LightGBM,3.6035,6.9042,10.7385,14.0880,16.4714,17.4758,20.8011
Ridge (Linear),2.8454,7.2320,11.9623,16.0423,19.4577,20.3332,19.1115
SARIMA,3.0496,6.9018,10.2419,13.2602,15.4098,18.1749,22.4086
iTransformer,12.0129,14.8549,17.4575,17.2642,20.1559,22.9434,29.2886

--- RMSE($) (Model x Horizon) ---

Horizon,1,5,10,15,20,30,60
Model,,,,,,,
ARIMAX,2.0175,3.9035,4.8061,5.8498,6.5276,6.9632,5.1157
GUMNet-Lite,9.7570,11.6205,14.3253,16.4001,18.4918,20.1730,27.5929
GUMNet-Ultra,7.8533,9.7735,13.7337,14.3927,15.6793,20.3316,21.7267
Jump-Gated ARIMAX-CatBoost,2.7247,4.0083,5.9280,6.5730,8.5110,9.2263,5.7508
LSTM,7.2541,12.3324,13.6081,14.2932,18.0289,21.6421,28.3382
LightGBM,3.6035,6.9042,10.7385,14.0880,16.4714,17.4758,20.8011
Ridge (Linear),2.8454,7.2320,11.9623,16.0423,19.4577,20.3332,19.1115
SARIMA,3.0496,6.9018,10.2419,13.2602,15.4098,18.1749,22.4086
iTransformer,12.0129,14.8549,17.4575,17.2642,20.1559,22.9434,29.2886

--- SMAPE(%) (Model x Horizon) ---

Horizon,1,5,10,15,20,30,60
Model,,,,,,,
ARIMAX,0.9608,2.1770,2.7803,3.4112,3.7800,4.2629,4.1186
GUMNet-Lite,5.2097,6.6563,8.5745,8.4160,12.6297,12.0555,17.1971
GUMNet-Ultra,5.0668,5.6549,7.8989,9.1386,9.2951,13.9785,12.8971
Jump-Gated ARIMAX-CatBoost,1.0211,2.2220,2.9681,3.5652,4.2544,4.9402,5.4958
LSTM,4.0746,7.1330,8.1048,9.0361,11.1663,12.0290,18.9576
LightGBM,2.0422,4.0634,5.7518,7.2750,9.5536,9.6594,13.3254
Ridge (Linear),1.4276,3.9261,5.7541,7.2034,8.5801,9.5842,10.2188
SARIMA,1.5528,3.9068,5.0210,6.1194,7.3191,8.8458,11.3846
iTransformer,5.6518,7.0757,9.3182,11.1848,13.0461,14.4518,18.0405

=== Quality check vs standard (MAPE<3% H1-5 | MAPE<5% H10-20 | RMSE($)<2) ===

,Model,Horizon,MAPE(%),MAPE_thr(%),RMSE($),RMSE_thr($),Pass
0,ARIMAX,1,0.9639,3.0,2.0175,2.0,False
1,SARIMA,1,1.5540,3.0,3.0496,2.0,False
2,Jump-Gated ARIMAX-CatBoost,1,1.0239,3.0,2.7247,2.0,False
3,Ridge (Linear),1,1.4263,3.0,2.8454,2.0,False
4,LightGBM,1,2.0137,3.0,3.6035,2.0,False
...,...,...,...,...,...,...,...
58,LightGBM,60,12.8031,NaN,20.8011,2.0,False
59,LSTM,60,16.0541,NaN,28.3382,2.0,False
60,iTransformer,60,16.0514,NaN,29.2886,2.0,False
61,GUMNet-Lite,60,15.5697,NaN,27.5929,2.0,False
62,GUMNet-Ultra,60,11.2516,NaN,21.7267,2.0,False

--- Pass (Model x Horizon) ---

Horizon                        1      5      10     15     20     30     60
Model
ARIMAX                      False  False  False  False  False  False  False
GUMNet-Lite                 False  False  False  False  False  False  False
GUMNet-Ultra                False  False  False  False  False  False  False
Jump-Gated ARIMAX-CatBoost  False  False  False  False  False  False  False
LSTM                        False  False  False  False  False  False  False
LightGBM                    False  False  False  False  False  False  False
Ridge (Linear)              False  False  False  False  False  False  False
SARIMA                      False  False  False  False  False  False  False
iTransformer                False  False  False  False  False  False  False

Models meeting standard: 0/63
Saved -> e:\PCDOC\xangdau\XANG_DAU_FORECAST\XANG_DAU_FORECAST\results\data_exo_ver2\by_target\MG95\multihorizon_results.csv
Updated -> e:\PCDOC\xangdau\XANG_DAU_FORECAST\XANG_DAU_FORECAST\results\data_exo_ver2\multihorizon_results_all_targets_11.csv

## 9. Ghi chu

- **Signal decay:** do chinh xac giam khi H tang (R2 giam, MAPE/MAE tang) — bang pivot (Model x Horizon) o tren dinh luong dieu nay cho tung mo hinh. **Khong ve chart, chi in bang.**
- **Dataset:** `data/processed/data_exo_ver2.csv` (doc tuong minh qua `DATA_FILENAME`). Ket qua luu theo tag dataset: `results/{DATA_TAG}/...`.
- **Sin(Date)/Cos(Date):** `DOY_sin/cos` (chu ky nam) bo sung mua vu; co the giup nhat o H lon (30/60).
- ARIMA/SARIMA: rolling H-step (append, khong refit) — nhanh va cong bang.
- DL Keras + PatchTST/TFT skip neu thieu thu vien; cai xong chay lai. Giam `CONFIG['horizons']` hoac tat `run_seq_dl`/`run_nf` neu muon nhanh.
- Ket qua: `results/{DATA_TAG}/multihorizon_results.csv`, `results/{DATA_TAG}/multihorizon_results_all_targets.csv`.

In [10]:
# Chay cac target con lai bang kernel phu, khong tao them file notebook.
is_batch_child = os.environ.get("FORECAST_BATCH_CHILD") == "1"
if CONFIG.get("run_all_targets", False) and not is_batch_child:
    from src.notebook_batch_runner import run_notebook_targets

    os.environ["FORECAST_DATA_FILE"] = DATA_FILENAME   # children inherit the same dataset
    remaining_targets = [t for t in CONFIG["targets"] if t != TARGET]
    run_notebook_targets(
        ROOT / "notebooks" / NB_FILENAME,
        remaining_targets,
        timeout=None,
    )

    all_results_path = ROOT / "results" / DATA_TAG / "multihorizon_results_all_targets_11.csv"
    all_results = pd.read_csv(all_results_path)
    target_order = {name: pos for pos, name in enumerate(CONFIG["targets"])}
    all_results["__target_order"] = all_results["Target"].map(target_order)
    all_results = all_results.sort_values(["__target_order", "Horizon", "MAPE(%)"]).drop(columns="__target_order")
    print("HOAN TAT 4 TARGETS - KET QUA MULTIHORIZON")
    display(all_results)

[Batch 1/3] Bat dau target: MG92
[Batch 1/3] Hoan tat MG92 sau 2243.8s
[Batch 2/3] Bat dau target: DO 0.001%
[Batch 2/3] Hoan tat DO 0.001% sau 2097.1s
[Batch 3/3] Bat dau target: DO 0.05%
[Batch 3/3] Hoan tat DO 0.05% sau 2139.8s
HOAN TAT 4 TARGETS - KET QUA MULTIHORIZON

,Target,Model,Horizon,MAE,RMSE,RMSE($),MAPE(%),SMAPE(%),R2,MAPE_thr(%),RMSE_thr($),Pass
0,MG95,ARIMAX,1,0.9543,2.0175,2.0175,0.9639,0.9608,0.9872,3.0,2.0,False
2,MG95,Jump-Gated ARIMAX-CatBoost,1,1.0608,2.7247,2.7247,1.0239,1.0211,0.9767,3.0,2.0,False
3,MG95,Ridge (Linear),1,1.3958,2.8454,2.8454,1.4263,1.4276,0.9746,3.0,2.0,False
1,MG95,SARIMA,1,1.5108,3.0496,3.0496,1.5540,1.5528,0.9709,3.0,2.0,False
4,MG95,LightGBM,1,1.9601,3.6035,3.6035,2.0137,2.0422,0.9592,3.0,2.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...
250,DO 0.05%,GUMNet-Lite,60,18.2917,41.1034,41.1034,13.3584,16.5405,-0.5825,NaN,2.0,False
247,DO 0.05%,LightGBM,60,18.0994,37.9559,37.9559,14.0273,16.2112,-0.3788,NaN,2.0,False
251,DO 0.05%,GUMNet-Ultra,60,18.9513,38.3635,38.3635,14.7594,17.6054,-0.3786,NaN,2.0,False
248,DO 0.05%,LSTM,60,23.5025,47.7837,47.7837,18.2667,23.0224,-1.1387,NaN,2.0,False
249,DO 0.05%,iTransformer,60,26.7017,43.9612,43.9612,23.1763,25.4514,-0.8102,NaN,2.0,False